### ISSUE TITLE
Video encoder - Image set to video

### ISSUE THREAD

**Issue by 1100594** [Ruslan-B/FFmpeg.AutoGen#10]
Hi! Hope all is okay...

Your lib is awesome!

Can you tell me if I can use FFmpeg.AutoGen to encode a image sequence to a video? I know that is possible with ffmpeg, but I want to know if is possible to do this with your lib in Mono.
Can you also indicate me a nice tutorial or samples of how to do this with the recent ffmpeg?(because I only find samples in c that use old ffmpeg dlls).

Best regards,
1100594

**Comment by Ruslan-B** [comment]
Question is irrelevant or not related to wrapper. I can consider to write another example but cant give any ets.

**Comment by 1100594** [comment]
Hi,
Humm... thanks for the quick answer, so you are saying that is possible to do this, right? If you can provide another example (when you have time) it will fine for me too, I don't need any ETS.
Thanks again,
1100594

**Comment by Ruslan-B** [comment]
Np, I'm saying that is issue is not an issue.
In general, yes, it is possible - again if it possible with ffmpeg (there are few exclusions). 
But if you couldn't find any examples with respect to recent version of ffmpeg, it means there are not a lot of them in general. 
Thus this is irrelevant to auto generated wrapper.
I may consider to research this question thoroughly. 
As seems it shouldn't too complex.

**Comment by 1100594** [comment]
Okay, Thanks... :)

I will continue my research too and let you know if i'm having any issues with the wrapper.

**Comment by 1100594** [comment]
Hi,

I don't want to open another issue, so:

I dunno if only with my generation of FFmpeg.AutoGen (I think not, cause I can't find in your AutoGen too), but i can't find the signature of method "int av_image_alloc(uint8_t *pointers[4], int linesizes[4], int w, int h, enum AVPixelFormat pix_fmt, int align)" that is defined in the lib avutil-54 (same version as yours)...it is a bug or this method is not support by your wrapper?

Best regards, 
1100594

**Comment by Ruslan-B** [comment]
Well, it was an issue. 
As FFmpeg include files listed manually per library but looks like not all of them including all necessary headers.
I added imgutils.h to the generation script - thus av_image_alloc function did appear in wrapper.

Please let me know if you are missing anything else.

**Comment by 1100594** [comment]
Tested & Worked, thanks...
