### ISSUE TITLE
Update for 4.1

### ISSUE THREAD

**Issue by iamcarbon** [Ruslan-B/FFmpeg.AutoGen#100]
ffmpeg 4.1 was just released. it would be nice to get updated bindings.

**Comment by Ruslan-B** [comment]
Ok, on it.

**Comment by Ruslan-B** [comment]
Update, there is no build yet for 4.1 https://ffmpeg.zeranoe.com/builds/

**Comment by iamcarbon** [comment]
@Ruslan-B Looks like Zerano hasn't caught up with the official release (https://ffmpeg.org/download.html). Guessing it will land soon.

**Comment by Ruslan-B** [comment]
I've send a message to zeranoe will see how fast it going to take to update the build.

**Comment by iamcarbon** [comment]
@Ruslan-B Looks like the builds were just updated on zeranoe. https://ffmpeg.zeranoe.com/builds/

**Comment by Ruslan-B** [comment]
Will do right in the morning tomorrow.

**Comment by Ruslan-B** [comment]
Well it took a little bit more time than I anticipated. I've updated the package.
