### ISSUE TITLE
not loading correct dll on xbox

### ISSUE THREAD

**Issue by ispysoftware** [Ruslan-B/FFmpeg.AutoGen#102]
* **I'm submitting a ... **
  - [ ] bug report
  
* **What is the current behavior?**
when i deploy my app to an Xbox one, it's crashing saying

Unable to load DLL 'avdevice.58': The specified module could not be found. avdevice-58.dll is in the same directory as the executable and it works fine on the PC (64 bit).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

deploy a UWP app using ffmpeg to an xbox

* **What is the expected behavior?**

should load the avdevice-58.dll file

* **What is the motivation / use case for changing the behavior?**

get it working on xbox UWP platform

* **Please tell us about your environment:**

- version: 3.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

works fine locally on windows 10

**Comment by ispysoftware** [comment]
I think LoadLibrary should be using this on UWP:

[DllImport("API-MS-WIN-CORE-LIBRARYLOADER-L2-1-0.DLL", SetLastError = true)]
public static extern IntPtr LoadPackagedLibrary([MarshalAs(UnmanagedType.LPWStr)]string libraryName, int reserved = 0);

instead of

[DllImport(Kernel32, SetLastError = true)]
public static extern IntPtr LoadLibrary(string dllToLoad);

https://stackoverflow.com/questions/45620704/calling-loadlibrary-using-pinvoke-from-uwp-c-sharp-application

**Comment by Ruslan-B** [comment]
Maybe, but have you look here #101? I don't think you will be able to load win32/64 libriaries in WinRT enviroment. https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app?view=vs-2017
As I don't have xbox (never will 😛), could help to test proposed solution first? 
You can try to redifine ```ffmpeg.GetOrLoadLibrary```, but I guess next challage will be finding substitute for  ```GetProcAddress```.

**Comment by ispysoftware** [comment]
xbox is basically windows x64 so it should (in theory) work. I'll try it and let you know

**Comment by ispysoftware** [comment]
Yeah ok, doesn't work. bugger. Just throws the same error. Seems like a bit of a show stopper.. several months work down the drain.

**Comment by Ruslan-B** [comment]
A few extra hits: try just try to import something simple like av_init with dll import attribute. As next step would be to compile ffmpeg for WinRT.

**Comment by ispysoftware** [comment]
that worked! changing the loadlibrary to loadpackagedlibrary and building and including the winrt ffmpeg dlls works.. now onto opencv :(

thanks for your super quick responses, much appreciated.

**Comment by Ruslan-B** [comment]
@ispysoftware I glad you found solution, and  thank you for the sharing end result, I'm going to work with UWA any way, however, not with this library but I'll try to make something generic from it. As might conflict with .NET Core apps.
Besides, what way did you used to compile WinRT FFmpeg?

**Comment by ispysoftware** [comment]
I went through this
https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT
- now i need to add support for h264 encoding to the UWP ffmpeg build which is proving to be quite painful..

**Comment by Ruslan-B** [comment]
Closing issue as not releated to bindings itself .
