### ISSUE TITLE
"avutil.56" not found on Ubuntu 18.04

### ISSUE THREAD

**Issue by jmacato** [Ruslan-B/FFmpeg.AutoGen#103]
This may not be a bug/feature request however, so I'd like to ask on what package should be installed on Ubuntu 18.04, i've tried running the example project (w/ .NET Core) and got the ff. exception:

```
An unhandled exception of type 'System.DllNotFoundException' occurred in FFmpeg.AutoGen.dll: 'Unable to load DLL 'avutil.56': The specified module could not be found.'
```

I've updated+upgraded all necessary ffmpeg libs on apt so i'm not quite sure how to proceed on this one.

**Comment by Ruslan-B** [comment]
You have to set static ```ffmpeg.RootPath``` to your FFmpeg library location.

**Comment by jmacato** [comment]
FYI: for everyone using LTS versions of Ubuntu, the upstream apt didn't update their FFmpeg versions to 4.0, hence the error i encountered. Install FFmpeg 4.0 on your distros so that this wrapper lib work :)

**Comment by Trapov** [comment]
@Ruslan-B 

I've set the `ffmpeg.RootPath` property before initializing the library, yet one of the deps didn't load. It did load `libavutil` tho.
```csharp
ffmpeg.RootPath = @"/usr/local/lib/";
// this line works, hence libavutil was loaded.
Console.WriteLine($"FFmpeg version info: {ffmpeg.av_version_info()}");
```

```bash
08:29 $ ls "/usr/local/lib/libavformat.so.58"
/usr/local/lib/libavformat.so.58
```
```csharp
Exception has occurred: CLR/System.DllNotFoundException
An unhandled exception of type 'System.DllNotFoundException' occurred in FFmpeg.AutoGen.dll: 'Unable to load DLL 'avformat.58': The specified module could not be found.'
```

**Comment by Ruslan-B** [comment]
Get new package if problem is reacquiring fell free to reopen
