### ISSUE TITLE
avcodec and RootPath

### ISSUE THREAD

**Issue by vnmone** [Ruslan-B/FFmpeg.AutoGen#105]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug report

* **What is the current behavior?**
avcodec-58.dll
swresample-3.dll

This dll's must be in the program folder and the RootPath specification does not work for these files.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

1) place all ffmpeg libraries in lib\ffmpeg

2) code example
ffmpeg.RootPath = @"lib\ffmpeg";
var fmt = ffmpeg.av_guess_format("avi", null, null);

3) throws error 
System.DllNotFoundException: "Unable to load DLL 'avformat.58': The specified module could not be found."

* **What is the expected behavior?**
avformat.58 is in specified path and no errors.

* **What is the motivation / use case for changing the behavior?**
order in 3rd libs

* **Please tell us about your environment:**
- win10
- version: 4.1.0.2
-x64

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

System.DllNotFoundException
  HResult=0x80131524
  Сообщение = Unable to load DLL 'avformat.58': The specified module could not be found.
  Источник = FFmpeg.AutoGen
  Трассировка стека:
   at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass4_0.<.cctor>b__0(String name, Int32 version)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__4_274(String short_name, String filename, String mime_type)

**Comment by Ruslan-B** [comment]
Yay, how come you got linux dll naming convention on windows system?

Cheers,
Ruslan

**Comment by vnmone** [comment]
Hi, Ruslan!
Do you mean "avformat.58" in error message?

**Comment by Ruslan-B** [comment]
Right, this is just a message, has nothing to do with linux. However, I found source of the problem it is dll loading sequence as ffmpeg internally linked against each other in this particular case OS cannot resolve dependency as it not included in dll search pass. As a fast workaround, I can advise to use SetDllDirectory to include root path into dll search path. Meanwhile, I'll take a look how to resolve it properly.

**Comment by daverobo** [comment]
I had a similar issue when trying to set the ffmpeg.RootPath property. I resolved it by specifying the DLL load order. I was able to do this because I am using the costura.fody library. The unmanaged DLLs are embedded as resources, and copied to a temporary directory during module initialisation. Not entirely sure but it appears to also call SetDllLibrary(temp-dir) and LoadLibrary(*.dll). The ffmpeg.autogen.dll assembly is also embedded as a resource and loaded into memory during initialisation. Costura has an option to specify the load order (see FodyWeavers.xml below). The upside is that there is only a single program file. The downside is my tiny library + ffmpeg DLLs (x86 and x64) + ffmpeg.autogen.dll is 110MB in size, and program launch takes 10+ seconds.

```
***** FodyWeavers.xml *****
<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
	<Costura LoadAtModuleInit="true">
		<PreloadOrder>
			avutil-56
			postproc-55
			swresample-3
			swscale-5
			avcodec-58
			avformat-58
			avfilter-7
			avdevice-58
		</PreloadOrder>
	</Costura>
</Weavers>
```

**Comment by esmelov** [comment]
I have same problem in gnu linux docker image.

**Comment by Ruslan-B** [comment]
Get new package if problem is reacquiring fell free to reopen

**Comment by jihye-back** [comment]
I have a same problem in Visual Studio 2019. I think FFmpeg.Autogen can't load  DLL('avformat-58.dll)....😂

**Comment by zgabi** [comment]
I have the same (can't load avformat.58) problem with a newer (4.3) ffmpeg vesion on a windows server core 2012 R2. (but not on my Win10).. I reverted to an older version of ffmpeg, which works.

**Comment by Ruslan-B** [comment]
I recently updated binaries from different build source, just in case you are using binaries from repository (keep in mind they are GPL i.e. not free).
All seems to be working fine in my environment. At least calling of ```avformat_alloc_context()``` gives a valid context.
It also might be helpful to check Windows Defender and any other antivirus if happens you have one.

**Comment by zgabi** [comment]
The binaries uploaded here on 2020.10.06 works for me too.
But the ones which was commited on 2020.06.17 and 2020.06.29 are not working.

Earlier I never used binaries from this repo, I always downloaded them from zeranoe. So I guess you used that too in june.

I don't have defender or any other antivirus software on the Win Server 2012 R2 Core.

**Comment by Ruslan-B** [comment]
Zeranoe, closed his website last month, besides, last stable release was published was a bit messy as it was LGPL instead of GPL so I guess that was the reason. Now I'm using different source.

**Comment by zgabi** [comment]
By the way, do you know any other alternative, which provides the same builds as it was on Zeranoe?
I mean the shared not full builds.... the full build on gyan.dev is 30MB bigger, and I don't need them. And the BtbN builds are not release builds :(

**Comment by Ruslan-B** [comment]
No, I don’t know, but you always can build ffmpeg yourself in the configuration you need to, atm it is not big deal - just google or search on github - plenty of projects and guides.
As for this project - gyan.dev is more than enough for bindings generation.

**Comment by et-hh** [comment]
我测试了下，项目配置文件里加上<ImplicitUsings>enable</ImplicitUsings>，就会出现这个报错，去掉就好了。
估计是自动添加的引用有问题，怀疑是字符串处理相关的引用
