### ISSUE TITLE
Cannot implicitly convert type 'int' to 'uint'. 

### ISSUE THREAD

**Issue by IOL0ol1** [Ruslan-B/FFmpeg.AutoGen#106]
1 clone from git 
2 compile and run FFmpeg.AutoGen.CppSharpUnsafeGenerator with **VS2017 , Windows10**
3 only FFmpeg.functions.inline.g.cs file has been updated and some errors in it.

for example，the  function in old FFmpeg.functions.inline.g.cs is like this
```csharp
public static int av_ceil_log2_c(int @x)
{
    return av_log2((uint)(x - 1) << 1);
}
public static int av_clip_intp2_c(int @a, int @p)
{
    if ((((uint)a + (1 << p)) & ~((2 << p) - 1)) != 0)
        return (a >> 31) ^ ((1 << p) - 1);
    else
        return a;
}
```
but in new FFmpeg.functions.inline.g.cs is like this
```csharp
public static int av_ceil_log2_c(int @x)
{
    return av_log2((x - 1) << 1);
}
public static int av_clip_intp2_c(int @a, int @p)
{
    if (((unsigned int)a + (1 << p)) & ~((2 << p) - 1))
        return (a >> 31) ^ ((1 << p) - 1);
    else
        return a;
}
```

Seems to be a direct copy of the contents of the inline function in the header file.

there is some console output shows the version of my windows 10 SDK and msvc
```shell
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0
#include "..." search starts here:
#include <...> search starts here:
 E:\Projects\FFmpeg.AutoGen\ffmpeg\include
 E:\Projects\FFmpeg.AutoGen\FFmpeg.AutoGen.CppSharpUnsafeGenerator\bin\x64\Debug\lib\clang\8.0.0\include
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\atlmfc\include
 C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared
 C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um
 C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt
 C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt
End of search list.
```

**Comment by Ruslan-B** [comment]
It is known issue there is no way (yet, may be never will be) to auto convert inline expressions. They are converted manualy right now. However, there are hash computed in order to determen change in function. I'll add ability to keep existing C# fuction body later on.
But if you like to have a custom build right now just revert ffmpeg.functions.inline.g.cs to the original state.
Keep this issue open as reminder to improve generation.
