### ISSUE TITLE
Update to Ffmpeg 4.1.2

### ISSUE THREAD

**Issue by Krakean** [Ruslan-B/FFmpeg.AutoGen#107]
Hello
Can you please binaries to Ffmpeg 4.1.2 (currently in release/4.1 branch only, but I guess its safe to take this version as-is from ffmpeg git)?
Also, can you also please provide linux/osx binaries in Ffmpeg/bin/x64 folder?

**Comment by Ruslan-B** [comment]
Hi there,

For starters keep in mind binaries in this reposiotry are GPL binaries so be careful here.
The only reasone they are in repository as they used during generatrion to extract exported functions. Next FFmpeg uses semantic versioning so 4.1.2 means bugfixes and no changes in API. 
Thus it is not important for generation and as a consiquence I'm not going to update them. 
With respect to linux/osx binaries - it is rather strange request, as you can install them from package manager and they are linked agains your system anyway so they are not reusable like on Windows.
Cheers,
Ruslan
