### ISSUE TITLE
Use av_image_fill_arrays with AVFrame

### ISSUE THREAD

**Issue by feliwir** [Ruslan-B/FFmpeg.AutoGen#108]
Hey, how can i use `av_image_fill_arrays` with AVFrame? 
The problem here is that `av_image_fill_arrays` expects a `byte_ptrArray4`, but AVFrame->data returns `byte_ptrArray8`, which are non convertible in FFmpeg.AutoGen. I saw the example in `VideoFrameConverter`, but it avoided using an AVFrame

**Comment by Ruslan-B** [comment]
Any fixed array has to methods ```ToArray()``` and ``UpdateFrom(array)```

For example:
```
var byte_ptrArray8 = new byte_ptrArray8();
var byte_ptrArray4 = new byte_ptrArray4();
byte_ptrArray4.UpdateFrom(byte_ptrArray8);
```

**Comment by feliwir** [comment]
I saw that, but it copies the data, which isn't necessary there.

**Comment by Ruslan-B** [comment]
It is just 4 pointers, right?

**Comment by feliwir** [comment]
True, i missed that 👍

**Comment by JohnsonGao** [comment]
Meet the same prblem when I transform AVFrame from ARGB to YUV420P. 
How to resolve this ?

**Comment by Ruslan-B** [comment]
@JohnsonGao stackoverflow?

**Comment by JohnsonGao** [comment]
Sorry for having no enough reputation to send questions in stackoverflow :)

**Comment by Ruslan-B** [comment]
Sorry I don’t have a skill to read your mind directly, if you have a problem try to express your self better, this issue is closed and I think it has enough information to do not even post here anymore.

**Comment by sd3326852** [comment]
Hi, I got some problem with this function.
I got some code works fine with version 4.4 but I want to update it to version 6.0, like this
`
            int out_buffer_size = ffmpeg.avpicture_get_size(AVPixelFormat.AV_PIX_FMT_YUV420P, width, height);
            byte* out_buffer = (byte*)ffmpeg.av_malloc((ulong)out_buffer_size);
            ffmpeg.avpicture_fill((AVPicture*)pFrameYUV, out_buffer, AVPixelFormat.AV_PIX_FMT_YUV420P, width, height);
`
Then I replace it with the new function into this
`
            var n_buffer_size = ffmpeg.av_image_get_buffer_size(AVPixelFormat.AV_PIX_FMT_YUV420P, width, height, 1);
            byte* out_buffer = (byte*)ffmpeg.av_malloc((ulong)out_buffer_size);
            var ptr_data = new byte_ptrArray4();
            var ptr_size = new int_array4(); 
            ptr_data.UpdateFrom(pFrameYUV->data);
            ptr_size.UpdateFrom(pFrameYUV->linesize);
            ffmpeg.av_image_fill_arrays(ref ptr_data, ref ptr_size, out_buffer, AVPixelFormat.AV_PIX_FMT_YUV420P, width, height, 1);
`
Then the new code doesn't work.
Can you show me the right way to do it?

**Comment by forlayo** [comment]
@sd3326852 you can just:

```
AVFrame avFrame = new AVFrame
{
    width = width,
    height = height,
    format = (int) AVPixelFormat.AV_PIX_FMT_YUV420P,
};

var data = new byte_ptrArray4();
var linesize = new int_array4();
ffmpeg.av_image_fill_arrays(ref data, ref linesize, ptr_byte_buffer, AVPixelFormat.AV_PIX_FMT_YUV420P width, height, 1);

avFrame.data.UpdateFrom(data);
avFrame.linesize.UpdateFrom(linesize);
```
