### ISSUE TITLE
Invalid ddlName for swresample

### ISSUE THREAD

**Issue by CyrilPaulus** [Ruslan-B/FFmpeg.AutoGen#11]
It seems that all the functions of swresample point to the wrong dll.
They are mapped to AVCODEC_LIBRARY which is avcodec-56.dll, but I think they should be mapped to swresample-1.dll

Could you check ?

**Comment by Ruslan-B** [comment]
It appears this dll is not mapped at all, I'll check.

**Comment by Ruslan-B** [comment]
Should be fine by now.

**Comment by Kagamia** [comment]
This bug came back after your Merge work...
