### ISSUE TITLE
Adding ffmpeg.autogen to windows uwp project breaks release build

### ISSUE THREAD

**Issue by ispysoftware** [Ruslan-B/FFmpeg.AutoGen#111]
Empty UWP project, add ffmpeg.autogen as a reference.
Build with release build it causes an exception:

2>  App1 -> D:\Projects\App1\bin\x86\Release\App1.exe
2>  Processing application code
2>C:\Users\sean\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Internal compiler error: Object reference not set to an instance of an object.

-not sure if this is an issue with ffmpeg.autogen or the compiler but i've repro'd it on 3 pc's..

**Comment by Ruslan-B** [comment]
Can I have an example solution?

**Comment by ispysoftware** [comment]
it's trivial - just create a new UWP project, add a reference to ffmpeg.autogen, change to release build and compile - should through that compiler error.

**Comment by ispysoftware** [comment]
.. add the ffmpeg.autogen nuget package to it

**Comment by Ruslan-B** [comment]
ok gonna try

**Comment by ispysoftware** [comment]
tried it on vs 2017 and vs 2019, builds 16299 through to 17134, 32 bit and 64 bit

**Comment by ispysoftware** [comment]
did you manage to repro this? I've logged a support request with Microcrap - but not very hopeful on a response

**Comment by ispysoftware** [comment]
i've got a bug logged here 
https://developercommunity.visualstudio.com/content/problem/536403/internal-compiler-error-26.html
managed to repro it with a few lines of code from the autogen project

**Comment by ispysoftware** [comment]
Adding:

    <Type Name="FFmpeg.AutoGen.long_array4" Dynamic="Excluded"/>
    <Type Name="FFmpeg.AutoGen.ulong_array8" Dynamic="Excluded"/>
    <Type Name="FFmpeg.AutoGen.long_array17" Dynamic="Excluded"/>
    <Type Name="FFmpeg.AutoGen.double_array399" Dynamic="Excluded"/>
    
to properties/default.rd.xml in the UWP project works around this issue

**Comment by Ruslan-B** [comment]
I'm sorry been on vacation for a while but glad you found a workaround. Do you have any idea as for root couse?

**Comment by ispysoftware** [comment]
yeah it's a bug in their new native compiler - they're working on a fix but won't get it done for a while

**Comment by comfr3ak** [comment]
This issue still exists and the workaround doesn't fix the issue in my case. Is there an example of what the Default.rd.xml should look like for the workaround the compile in release?
