### ISSUE TITLE
Can't seek to specified frame with av_seek_frame

### ISSUE THREAD

**Issue by quocdai92** [Ruslan-B/FFmpeg.AutoGen#115]
Hi these,
I have got a problem when I try to seek my video to special frame. This is my code:

`public void GetFrame(int index)`
`{`
`long timeBase = (_pCodecContext->time_base.num) * ffmpeg.AV_TIME_BASE / _pCodecContext->time_base.den;`
`long seekTarget = index * timeBase;`
`int result = ffmpeg.av_seek_frame(_pFormatContext, -1, seekTarget, ffmpeg.AVSEEK_FLAG_ANY);`
`if (result < 0)`
`{
Console.WriteLine("Error");
}`
`}`

the video always reset to first frame even though I seek to any frame index.
Please help me, Thanks.

**Comment by Ruslan-B** [comment]
I do appreciate your effort to explain a problem  and must admit it has all necessary information, but please in future try to do not ignore issue temple, as this kind of questions seems to be more related to [stackoverflow.com](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) kind of questions as they have a solid community and reputation system which encourage to proved an answer.

**Comment by zpmmehrdad** [comment]
@quocdai92 Hi,

Is your problem solved? I have the same problem
