### ISSUE TITLE
How can I convert a h264 raw stream to rgb and play it with ffmpeg.autogen

### ISSUE THREAD

**Issue by liuyuqingenglish** [Ruslan-B/FFmpeg.AutoGen#116]
How can I convert a h264 raw stream to rgb and play it with ffmpeg.autogen。Below is my code, but it doesn't work，Dear author can help me see what went wrong?
******************************************************************************************
       /// <summary>
        /// 对读取的264数据包进行解码和转换
        /// </summary>
        /// <param name="show">解码完成回调函数</param>
        /// <param name="url">播放地址，也可以是本地文件地址</param>
        public unsafe void Start( byte[] pData)
        {
           

            Console.WriteLine(@"Current directory: " + Environment.CurrentDirectory);
            Console.WriteLine(@"Runnung in {0}-bit mode.", Environment.Is64BitProcess ? @"64" : @"32");

            #region ffmpeg 初始化

            // 初始化注册ffmpeg相关的编码器
            ffmpeg.av_register_all();
            ffmpeg.avcodec_register_all();
            ffmpeg.avformat_network_init();

            //Console.WriteLine($"FFmpeg version info: {ffmpeg.av_version_info()}");

            #endregion ffmpeg 初始化

            #region ffmpeg 日志

            // 设置记录ffmpeg日志级别
            ffmpeg.av_log_set_level(ffmpeg.AV_LOG_VERBOSE);
            av_log_set_callback_callback logCallback = (p0, level, format, vl) =>
            {
                if (level > ffmpeg.av_log_get_level()) return;

                var lineSize = 1024;
                var lineBuffer = stackalloc byte[lineSize];
                var printPrefix = 1;
                ffmpeg.av_log_format_line(p0, level, format, vl, lineBuffer, lineSize, &printPrefix);
                var line = Marshal.PtrToStringAnsi((IntPtr)lineBuffer);
                Console.Write(line);
            };
            ffmpeg.av_log_set_callback(logCallback);

            #endregion ffmpeg 日志

            #region ffmpeg 转码

            // 获取图像的宽、高及像素格式
            var width = 320;
            var height = 480;
            var sourcePixFmt = AVPixelFormat.AV_PIX_FMT_YUV420P;

            // 得到编码器ID
            var codecId = AVCodecID.AV_CODEC_ID_H264;
            // 目标像素格式
            var destinationPixFmt = AVPixelFormat.AV_PIX_FMT_BGR24;

            // 某些264格式codecContext.pix_fmt获取到的格式是AV_PIX_FMT_NONE 统一都认为是YUV420P
            //if (sourcePixFmt == AVPixelFormat.AV_PIX_FMT_NONE && codecId == AVCodecID.AV_CODEC_ID_H264)
            //{
            //    sourcePixFmt = AVPixelFormat.AV_PIX_FMT_YUV420P;
            //}

            // 得到SwsContext对象：用于图像的缩放和转换操作
            var pConvertContext = ffmpeg.sws_getContext(width, height, sourcePixFmt,
                width, height, destinationPixFmt,
                ffmpeg.SWS_FAST_BILINEAR, null, null, null);
            if (pConvertContext == null) throw new ApplicationException(@"Could not initialize the conversion context.");

            //分配一个默认的帧对象:AVFrame
            var pConvertedFrame = ffmpeg.av_frame_alloc();
            // 目标媒体格式需要的字节长度
            var convertedFrameBufferSize = ffmpeg.av_image_get_buffer_size(destinationPixFmt, width, height, 1);
            // 分配目标媒体格式内存使用
            var convertedFrameBufferPtr = Marshal.AllocHGlobal(convertedFrameBufferSize);
            var dstData = new byte_ptrArray4();
            var dstLinesize = new int_array4();
            // 设置图像填充参数
            ffmpeg.av_image_fill_arrays(ref dstData, ref dstLinesize, (byte*)convertedFrameBufferPtr, destinationPixFmt, width, height, 1);

            #endregion ffmpeg 转码

            #region ffmpeg 解码

            // 根据编码器ID获取对应的解码器
            var pCodec = ffmpeg.avcodec_find_decoder(codecId);
            if (pCodec == null) throw new ApplicationException(@"Unsupported codec.");

            /* 初始化AVCodecContext,只是分配，还没打开 */
            AVCodecContext* pCodecCtx = null;
            pCodecCtx = ffmpeg.avcodec_alloc_context3(pCodec);

            var pCodecContext = pCodecCtx;

            if ((pCodec->capabilities & ffmpeg.AV_CODEC_CAP_TRUNCATED) == ffmpeg.AV_CODEC_CAP_TRUNCATED)
                pCodecContext->flags |= ffmpeg.AV_CODEC_FLAG_TRUNCATED;

            // 通过解码器打开解码器上下文:AVCodecContext pCodecContext
            var error = ffmpeg.avcodec_open2(pCodecContext, pCodec, null);
            if (error < 0) throw new ApplicationException(GetErrorMessage(error));

            // 分配解码帧对象：AVFrame pDecodedFrame
            var pDecodedFrame = ffmpeg.av_frame_alloc();

            // 初始化媒体数据包
            var packet = new AVPacket();
            var pPacket = &packet;
            ffmpeg.av_init_packet(pPacket);

            var frameNumber = 0;

            try
            {
                fixed (byte* temp = pData)
                {
                    packet.size = pData.Length;
                    packet.data = temp;
                    // 解码
                    error = ffmpeg.avcodec_send_packet(pCodecContext, pPacket);
                    if (error < 0) throw new ApplicationException(GetErrorMessage(error));
                    // 解码输出解码数据
                    error = ffmpeg.avcodec_receive_frame(pCodecContext, pDecodedFrame);

                    if (error == ffmpeg.AVERROR_EOF) return;
                    if (error < 0) throw new ApplicationException(GetErrorMessage(error));

                    //if (pPacket->stream_index != pStream->index) continue;

                    //Console.WriteLine($@"frame: {frameNumber}");
                    // YUV->RGB
                    ffmpeg.sws_scale(pConvertContext, pDecodedFrame->data, pDecodedFrame->linesize, 0, height, dstData, dstLinesize);
                }
            }
            finally
            {
                ffmpeg.av_packet_unref(pPacket);//释放数据包对象引用
                ffmpeg.av_frame_unref(pDecodedFrame);//释放解码帧对象引用
            }

            // 封装Bitmap图片
            var bitmap = new Bitmap(width, height, dstLinesize[0], PixelFormat.Format24bppRgb, convertedFrameBufferPtr);
            // 回调
            //show(bitmap);
            int i = 0;
            bitmap.Save("e:\\a"+i.ToString()+".bmp");
            //bitmap.Save(AppDomain.CurrentDomain.BaseDirectory + "\\264\\frame.buffer."+ frameNumber + ".jpg", ImageFormat.Jpeg);

            frameNumber++;

            //播放完置空播放图片
            //show(null);

            #endregion ffmpeg 解码

            #region 释放资源

            Marshal.FreeHGlobal(convertedFrameBufferPtr);
            ffmpeg.av_free(pConvertedFrame);
            ffmpeg.sws_freeContext(pConvertContext);

            ffmpeg.av_free(pDecodedFrame);
            ffmpeg.avcodec_close(pCodecContext);

            #endregion 释放资源
        }

- version: 41

**Comment by Ruslan-B** [comment]
Going to keep it as an art - please don't try to repeat this, looks miserable.

**Comment by Ruslan-B** [comment]
P.S. chinese adds a colorrite but not the reason why, eventually 99% ignores an issue  template and call to post question on stackoverflow.com. Human nature - unfortunately.

**Comment by Ruslan-B** [comment]
I **do** give you a tool - **not the solution**.

**Comment by liuyuqingenglish** [comment]
sorry  But I really don't know ffmpeg very well.

**Comment by liuyuqingenglish** [comment]
How should I package a piece of h264 naked stream into AvPacket?

**Comment by Ruslan-B** [comment]
I'll give a hint this not the place to ask questions about ffmpeg as it doesn't matter - are you suing c# or C or C++.

**Comment by liuyuqingenglish** [comment]
Sorry again, I should follow the template to ask questions, but I didn’t pay attention.

**Comment by liuyuqingenglish** [comment]
I have been afflicted with this problem for several weeks (using c# to convert h264 to rgb), I am not very familiar with the native ffmpeg, found that this tool can use ffmpeg through c#, but do not know how to pass h264 array to this tool, I hope the author can help me see this question. Thank you very much.

**Comment by Ruslan-B** [comment]
that is exactly what the example project is doing - converting h264 stream to rgb bitmaps
