### ISSUE TITLE
How to convert video?

### ISSUE THREAD

**Issue by ASalihov** [Ruslan-B/FFmpeg.AutoGen#118]
Hi! 
Can you please explain how can I convert video file from one format to another using this library?
Thanks!

**Comment by popcatalin81** [comment]
You'll have to look at [C transcoding samples](https://ffmpeg.org/doxygen/3.3/transcode__aac_8c_source.html) or use [StackOverflow ](https://stackoverflow.com/questions/tagged/ffmpeg)to accomplish this. 

This is on the fist page:

> The FFmpeg API is vast and complex and this project exposes it with minimum modifications - support is very limited. Please consider to ask how to questions on stackoverflow.com. The community may be able to offer some assistance but you will largely be on your own. As another option you can search for a solution in C(lang) as with some effort you can convert it to C#

**Comment by Ruslan-B** [comment]
@popcatalin81 thank you. Closing this.

**Comment by Ruslan-B** [comment]
dig a little bit the history here is transcoding example  https://gist.github.com/Ruslan-B/43d3a4219f39b99f0c9685290dcd23cc
