### ISSUE TITLE
MarshalDirectiveException in av_log_set_callback_callback_func.op_Implicit

### ISSUE THREAD

**Issue by CyberSinh** [Ruslan-B/FFmpeg.AutoGen#119]
I have compiled my own build of FFmpeg (with the Visual C++ 2019 compiler) and everything is fine but several users have reported me the following issue (I cannot reproduce the issue on my system):

``` 
System.Runtime.InteropServices.MarshalDirectiveException: "Cannot marshal 'parameter #3': Invalid managed/unmanaged type combination (String parameters and return types must be paired with LPStr, LPWStr, LPTStr, BStr, TBStr, VBByRefStr, or AnsiBStr)."

-> System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegateInternal(Delegate d)
-> System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(Delegate d)
-> FFmpeg.AutoGen.av_log_set_callback_callback_func.op_Implicit(av_log_set_callback_callback func)
-> FFmpeg.AutoGen.FFInterop.Initialize(String overridePath, Int32 libIdentifiers)
```

I use the nuget package v4.1.0.4. Is it a bug on my side or on your side?

Thanks for your help.

**Comment by Ruslan-B** [comment]
Good question and by default it your side(s) I think, as example projects uses such function and works perfectly in VS2019 preview using C# 8. Besides, Visual C++ 2019 has nothing to do here as it not used at all here.

**Comment by CyberSinh** [comment]
Just to be sure, could you try to run your tests with the following FFmpeg build:
[FFmpeg.zip](https://github.com/Ruslan-B/FFmpeg.AutoGen/files/3323926/FFmpeg.zip)

Thanks!

**Comment by Ruslan-B** [comment]
You cannot do it yourself? What you asking is beyond normal - why should I run your binaries on my system? Rhetorical question though.  
Nevertheless, I don't how you managed to get them seems they have a mixed platforms 86-64:
![image](https://user-images.githubusercontent.com/3823565/60080593-82c9d300-9730-11e9-8208-a22f311c14aa.png)
Left is from zeranoe build right is yours.

**Comment by Ruslan-B** [comment]
Reread the question and got the problem - you  got the head version of ffmpeg right?

**Comment by CyberSinh** [comment]
I have compiled FFmpeg v4.1.3 (in x86) that should be compatible with your v4.1.0.4 nuget package.

DependencyWalker has not been updated for 13 years now and seems not to like DLL compiled with the latest versions of Visual Studio. I have no problem with loading the DLL with https://github.com/lucasg/Dependencies.

**Comment by Ruslan-B** [comment]
Well, than it supposed to work. I tried but cannot load you binaries  LoadLibrary from Kernel32 gives null back right on avutil-56.dll in x64 mode. My Windows Version is 10.0.17134 Build 17134
It might just bug in a preview version of VC++ 2019.

**Comment by Ruslan-B** [comment]
Guess what - your binaries are build for i386 i.e. 32-bit and I simply cannot load them in 64 bit mode and .net core refuses to start in 32 bit.

**Comment by Ruslan-B** [comment]
After tinkering a bit with full framework got it "working" with your binaries in 32 bit mode:
![image](https://user-images.githubusercontent.com/3823565/60095433-d6e3b000-974e-11e9-83e5-e882cdd7c07d.png)
As you see av_log_set_callback invocation went fine, it fail to resolve coded but that's normal looks like your binaries is a LGPL comparable build.

**Comment by CyberSinh** [comment]
So, neither my custom FFmpeg builds nor your project seems to be buggy. Maybe the problem comes from the user (deployment problem, file overwriting,...). Anyway, thank you very much for taking the time to check that everything was okay on your side.

**Comment by CyberSinh** [comment]
Another hypothesis, which seems more likely:
https://github.com/unosquare/ffmediaelement/issues/404#issuecomment-505420428

What do you think?

**Comment by CyberSinh** [comment]
After verification, .NET 4.7 or .NET Standard 2.1 is required for `UnmanagedType.LPUTF8Str`.
Perhaps you could target .NET 4.7 or .NET Standard 2.1 for your nuget package. 
That would avoid troublesome crash at runtime.

**Comment by Ruslan-B** [comment]
Right, could be connected with https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/96 as fix was a hack. Thank for digging further on I'll reopen the issue and update the package any time soon.

**Comment by Ruslan-B** [comment]
Seams something really-really wrong with Microsoft as I simply can't target to 2.1(+) .NET Standard - have to keep this issue open (the .net471 works okay).

**Comment by Ruslan-B** [comment]
Had some time to dig deeper. I can compile library targeting netstandard2.1 only in VS2019 and example project must to be targeted to .NET Core 3.0. As long all this stuff still preview I would rather stick to the hack as it mostly works.
Maybe I can add a check in runtime if the .net version is correct but not sure if it going to work.

**Comment by Ruslan-B** [comment]
I updated nuget with:
- netstandard2.1, net472 - the are legally doing UTF8 marshaling;
- netstandard2.0, net45 - using hack from #96, but I'll remove this during major upgrade of FFmpeg;
- net40 - not suing any UTF8 marshaling.
