### ISSUE TITLE
Linux getting started

### ISSUE THREAD

**Issue by billHaggerty** [Ruslan-B/FFmpeg.AutoGen#120]
Is there a better getting started guide for linux? It says 'You need to patch FFmpeg.AutoGen.config with full path to FFmpeg libraries.', but that file doesn't even exist to begin with. Is that a file I need to make or is generated via using the CppSharpUnsafeGenerator? 

I was hoping I could just use the nuget package or clone and build FFmpeg.Autogen/FFmpeg.Autogen.csproj without using CppSharpUnsafeGenerator since I'm on ubuntu.

**Comment by Ruslan-B** [comment]
It is outdated you just can use nuget package and specify path to binaries via ffmpeg.RootPath - check example project.

**Comment by billHaggerty** [comment]
Ok, how do we know what version of ffmpeg and the underlying binaries are the correct ones to use?

**Comment by Ruslan-B** [comment]
nuget package version is in sync with ffmpeg  version. However,  ffmpeg.RootPath will work only for v4.1

**Comment by billHaggerty** [comment]
So since im using FFmpeg.AutoGen v4.1.0.5 I should downgrade my ffmpeg from version 4.1.3-0york1~16.04 to a 4.1.0 version?

**Comment by Ruslan-B** [comment]
No you don't need to do so ffmpeg using semantic versioning means 4.1.x it is only bug fixes in ffmpeg and no changes in api.

**Comment by billHaggerty** [comment]
Ok, Thanks for your help!

**Comment by Ruslan-B** [comment]
No problem, you're welcome.
