### ISSUE TITLE
Update to 4.2

### ISSUE THREAD

**Issue by iamcarbon** [Ruslan-B/FFmpeg.AutoGen#123]
* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

NOTE: We're still waiting for Windows builds to land.

**Comment by Ruslan-B** [comment]
Will do, but I need a widows build.

**Comment by iamcarbon** [comment]
And the build is live. https://ffmpeg.zeranoe.com/builds/
