### ISSUE TITLE
How to transcode audio streams ?

### ISSUE THREAD

**Issue by JohnsonGao** [Ruslan-B/FFmpeg.AutoGen#125]
Hi , I saw your video transcoding class in examples you gave, looks great. Would you please give another example on audio stream transcoding just like ffmpeg classic samples? for instance, from opus to aac ? Thank you !

**Comment by Ruslan-B** [comment]
Sorry as you might read we do not provide such help. Besides, it is fairly easy to convert C example to C#. Otherwise, you can try to use stackoverflow.
