### ISSUE TITLE
 play video files

### ISSUE THREAD

**Issue by jinyuttt** [Ruslan-B/FFmpeg.AutoGen#126]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

* **What is the expected behavior?**

How to use it to play video files？

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- version: 3.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
you don’t read plain English aren’t you?

**Comment by Ruslan-B** [comment]
I'm closing this issue as this not lays within a scope of this library and next time please read issue template carefully, otherwise you will get a permanent ban.
