### ISSUE TITLE
Compile for custom ffmpeg build in Linux

### ISSUE THREAD

**Issue by cyberdecker** [Ruslan-B/FFmpeg.AutoGen#129]
Hi, I noticed that the README is not updated in how to build for Linux version. I would like to compile for Linux for a custom build with specific flags of ffmpeg. It is that possible? 

Thanks!

* **Please tell us about your environment:**
Ubuntu 18.04
NetCore 2.2

**Comment by Ruslan-B** [comment]
Do you experience some build issues, or it just dead end question here?

**Comment by Ruslan-B** [comment]
Fell free to reopen in case you can provide any meaningful feedback

**Comment by cyberdecker** [comment]
I was referring to:
- `FFmpeg.AutoGen.config` was mentioned in the Readme to be used to compile in Linux, but I saw another issue, #120 , it is clear that is deprecated. So I would like to suggest to update the README to remove this reference to `FFmpeg.AutoGen.config`, as it can confuse other people wanting to build in Linux versions.
 
Thanks!

**Comment by Ruslan-B** [comment]
Right it used to be mono particularly- thanks for brining up I will clean  up this.
