### ISSUE TITLE
ffmpeg.sws_scale  IntPtr to byte*[] 

### ISSUE THREAD

**Issue by txgr** [Ruslan-B/FFmpeg.AutoGen#130]
Hey, how can i use sws_scale with opencv mat?
The problem here is that sws_scale expects a byte*[], but Mat image.data returns IntPtr,
How to deal with this situation.

**Comment by Ruslan-B** [comment]
I'm closing this as you ignored template and frankly you should post it on stackoverflow first.
Why should I know what is IntPtr of the Mat - rhetorical question. 
However,  I guess you are taking about srcSlice - and if so you could bother to check function documentation.
```/// <param name="srcSlice">the array containing the pointers to the planes of the source slice</param>```
Besides you could check the example which is using byte_ptrArray8
