### ISSUE TITLE
Example doesn't work properly when encoding

### ISSUE THREAD

**Issue by VincentZe** [Ruslan-B/FFmpeg.AutoGen#131]
Running FFmpeg.AutoGen.Example. 
The first frame of out.h264 has extra duration, and lost some frames in the end.

**Comment by popcatalin81** [comment]
Yes, you need a better encoding loop. It's described here: https://ffmpeg.org/doxygen/4.1/group__lavc__encdec.html The one in Demo does not handle all cases.

**Comment by Ruslan-B** [comment]
Yes, indeed it was ported before 4.0, but I don't have enough time too keep track of all changes. As you know almost all API is auto generated. Even though examples are working but they might be outdated.

**Comment by VincentZe** [comment]
Oh thanks for telling, I'll go read the documents.

**Comment by Ruslan-B** [comment]
@popcatalin81 my kudos to you personally! As looks like my annoyance to vaguely formed questions is a braking point in this repo development.

**Comment by waleswood** [comment]
> Oh thanks for telling, I'll go read the documents.
Have you solved the problem？

**Comment by waleswood** [comment]
> Oh thanks for telling, I'll go read the documents.

Have you solved the problem

**Comment by waleswood** [comment]
> Oh thanks for telling, I'll go read the documents.
@VincentZe 
Have you solved the problem

**Comment by waleswood** [comment]
> Oh thanks for telling, I'll go read the documents.

@VincentZe Have you solved the problem

**Comment by popcatalin81** [comment]
@waleswood The Sample does not make the codec go intro draining mode, that's why the last frames are dropped.

From the documentation I've linked above:

> End of stream situations. These require "flushing" (aka draining) the codec, as the codec might buffer multiple frames or packets internally for performance or out of necessity (consider B-frames). This is handled as follows:
>
>    Instead of valid input, send NULL to the avcodec_send_packet() (decoding) or avcodec_send_frame() (encoding) functions. This will enter draining mode.

**Comment by waleswood** [comment]
@popcatalin81 I have tried it but it still doesn't work. Can you provide code examples? thank you very much.

**Comment by popcatalin81** [comment]
@waleswood Sorry I don't have a code sample available right now.

One day I might take the time to create one and make a PR, but since Ive strayed from this topic in the past year might take a bit longer until I can make the time to get back into the topic. 

Best of luck
