### ISSUE TITLE
EAGAIN value is -35 on OSx environment

### ISSUE THREAD

**Issue by AddictedCS** [Ruslan-B/FFmpeg.AutoGen#134]
- [x] bug report (potential)

* **What is the current behavior?**
Running on OSx (.NET Core 3.1). FFMpeg installed using brew (v4.2.2)
`EAGAIN` value is -35. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

When decoding frames we iterate until `EAGAIN` is false, meaning `AVFrame*` contains actual data. Code may look like this:
```csharp
int error = ffmpeg.AVERROR(ffmpeg.EAGAIN);
while(error == ffmpeg.AVERROR(ffmpeg.EAGAIN)) {
   // receive frame until no more EAGAIN is returned
   error = ffmpeg.avcodec_receive_frame(context, receivedFrame);
}
```

* **What is the expected behavior?**
On OSx environment error code returned from `ffmpeg.avcodec_receive_frame(context, receivedFrame);` is -35. We need to treat -35 similar to -11 (EAGAIN), otherwise, receive frame exits the capture loop earlier than needed.

* **What is the motivation / use case for changing the behavior?**
-35 should be treated similar to -11 on OSx, otherwise, frame decoding will not work.

It took me quite a bit to dig into this. Posting this information here may help others to handle Unix env.

Did anyone had a similar experience, or am I missing something with the way how error codes should be treated?

**Comment by popcatalin81** [comment]
@AddictedCS Do you believe this is a FFmpeg.AutoGen or FFmpeg issue?

**Comment by zgabi** [comment]
EAGAIN = 11 is hardcoded in FFmpeg.AutoGen/FFmpeg.cs so for me it seems to be an FFmpeg.AutoGen issue.

**Comment by popcatalin81** [comment]
@zgabi EAGAIN is imported in ffmpeg (see [avcodec.h](https://github.com/FFmpeg/FFmpeg/blob/722547996c27b871c9288c45de9887b98a076750/libavcodec/avcodec.h#L30)) from the standard [erno.h C standard library ](https://en.wikipedia.org/wiki/Errno.h)

EAGAIN is defined as:

#define	EAGAIN 11
and ffmpeg defines [AVEROR](https://github.com/FFmpeg/FFmpeg/blob/722547996c27b871c9288c45de9887b98a076750/libavutil/error.h#L39) as:

```c
/* error handling */
#if EDOM > 0
#define AVERROR(e) (-(e))   ///< Returns a negative error code from a POSIX error code, to return from library functions.
#define AVUNERROR(e) (-(e)) ///< Returns a POSIX error code from a library function error return value.
#else
/* Some platforms have E* and errno already negated. */
#define AVERROR(e) (e)
#define AVUNERROR(e) (e)
#endif
```

So EAGAIN in FFmpeg should be -11. -35 is actually ENOMSG

**Comment by zgabi** [comment]
Yeah, but it has different value in OSx and Linux/Windows:
https://android.googlesource.com/kernel/lk/+/dima/for-travis/include/errno.h

https://github.com/st3fan/osx-10.9/blob/master/xnu-2422.1.72/bsd/sys/errno.h

Which is strange, but seems to be true (haven't tested)

**Comment by popcatalin81** [comment]
@zgabi Good catch.

@Ruslan-B FYI  `errno.h` in OSX has a different value for EAGAIN please see [here](https://github.com/st3fan/osx-10.9/blob/34e34a6a539b5a822cda4074e56a7ced9b57da71/xnu-2422.1.72/bsd/sys/errno.h#L132). 

This is a good candidate for contributor PR.

**Comment by Ruslan-B** [comment]
I don’t think it is FFmpeg.Autgen issue as hardcoded value is just for convince. Besides, example project is ported by the book and supports handling of EAGAIN.

**Comment by AddictedCS** [comment]
@Ruslan-B no rush from my side. Thanks @zgabi for the reference to the error codes.
