### ISSUE TITLE
library fails to run on non-gpl builds

### ISSUE THREAD

**Issue by ispysoftware** [Ruslan-B/FFmpeg.AutoGen#137]
postproc is GPL only so if ffmpeg is distributed without postproc ffmpeg autogen fails to load with a postproc missing exception.

**Comment by Ruslan-B** [comment]
I think library loading is lazy function and it supposed to happens when you trying to call function from postproc library. I don't violate GPL in project because I'm not distributing GPL libraries and API is out of licensing limitations afaik.
What kind behavior are you expecting?

**Comment by Ruslan-B** [comment]
I now I see avfilter uses it.

**Comment by Ruslan-B** [comment]
Fixed new nuget in feed.
