### ISSUE TITLE
Update to 4.3

### ISSUE THREAD

**Issue by iamcarbon** [Ruslan-B/FFmpeg.AutoGen#138]
We have nightly builds, but still waiting for the final Windows build to land.

https://ffmpeg.zeranoe.com/builds/

**Comment by Ruslan-B** [comment]
Yes, I'll monitor for new release build. As seems zeranoe nightly builds slaking behind for about 48 hours.

**Comment by Ruslan-B** [comment]
I looked over ffmpeg repository it seems I can use nightly ffmpeg-20200615-9d80f3e from zeranoe for generation, but I wouldn't recommend usage of the binaries as I see few bug fixes been done.

**Comment by Ruslan-B** [comment]
I've updated nuget package, like I mentioned ffmpeg binaries not latest released as it is still 9d80f3e, but it does not impact generated API.

**Comment by Ruslan-B** [comment]
We have a build now but less likely others binaries will change

**Comment by Ruslan-B** [comment]
Okay here we go https://ffmpeg.zeranoe.com/builds/ updated to 4.3 but in "GPL" build libpostproc is missing including headers. Which me me think it is LGPL build after all and example can't encode h264 using these binaries.
I also don't see any obvious  way to constant zeranoe to let them know about inconsistency.
Technically, I can post updated package as I have to rollback some of the functions, enums, and structures as seems to be the hash I used is post 4.3 release. Mess.

**Comment by Ruslan-B** [comment]
I updated binaries to released 4.3 GPL version, no changes needed to latest nuget package (4.3..0.1).

**Comment by Zeranoe** [comment]
Sorry for the inconvenience here, and the delay on my end.

**Comment by Ruslan-B** [comment]
@Zeranoe no need for apology, thank you for the swift response!
