### ISSUE TITLE
Wrong channel layout flags

### ISSUE THREAD

**Issue by EchterAgo** [Ruslan-B/FFmpeg.AutoGen#14]
The channel layout flags like "AV_CH_LAYOUT_STEREO" get generated wrongly as zero. In the FFmpeg source code they are set using a bitwise or of other flags like "AV_CH_FRONT_LEFT | AV_CH_FRONT_RIGHT" in the case of stereo. Anyway, thank you for this great wrapper!

**Comment by EchterAgo** [comment]
```C#
    public static class FFmpegInvoke
    {
...
        public const int AV_CH_LAYOUT_STEREO = 0;
```

versus channel_layout.h from ffmpeg-2.5.2

```C++
#define AV_CH_FRONT_LEFT             0x00000001
#define AV_CH_FRONT_RIGHT            0x00000002
...
#define AV_CH_LAYOUT_STEREO            (AV_CH_FRONT_LEFT|AV_CH_FRONT_RIGHT)
```

**Comment by Ruslan-B** [comment]
It look like a bug in python ctypesgen across preprocessor. I'll take a look but cannot promise it will be fixed. 
I'm considering switch to gccxml but it will take some time and will lead to breaking changes.

**Comment by EchterAgo** [comment]
No need to hurry, I am just combining the flags myself and it seems to work. I just wanted to have this documented in case someone else runs into it.

**Comment by mariodivece** [comment]
+1 here. I had to do some down-mixing from 6 channels to stereo and I noticed it was not working. Combining the flags manually worked like a charm :)
This project is really the only one that provides complete access to all of FFmpeg's features. Great Work!

**Comment by Ruslan-B** [comment]
@EchterAgo, I switched generator and it looks like flag recombination is working fine, but is very experimental (check corresponding branch if so).

**Comment by Ruslan-B** [comment]
merged to master
