### ISSUE TITLE
av_image_copy segmentation fault on CentOS 8

### ISSUE THREAD

**Issue by EvK** [Ruslan-B/FFmpeg.AutoGen#140]
I'm submitting a bug report.

I'm using FFmpeg.AutoGen on CentOS 8 (64bit), with default ffmpeg available from package there (of version 4.2.3). I tried below with FFmpeg.AutoGen nuget packages of versions 4.2.1, 4.2.2, 4.3, with the same results.

I have two frames named `canvasFrame` and `cellFrame` and using `av_image_copy` to copy certain data from one to another, using the following code:

```
var dstData = new byte_ptrArray4();
dstData[0] = canvasFrame->data[0] + yStartOffset;
dstData[1] = canvasFrame->data[1] + uStartOffset;
dstData[2] = canvasFrame->data[2] + vStartOffset;
var canvasLineSize = new int_array4();
canvasLineSize.UpdateFrom(canvasFrame->linesize);
var cellFrameData = new byte_ptrArray4();
cellFrameData.UpdateFrom(cellFrame->data);
var cellLineSize = new int_array4();
cellLineSize.UpdateFrom(cellFrame->linesize);
ffmpeg.av_image_copy(ref dstData, ref canvasLineSize, ref cellFrameData, cellLineSize, (AVPixelFormat) cellFrame->format, cellFrame->width, cellFrame->height);
```
I'm creating separate `canvasLineSize` etc variables, because, for example, `canvasFrame->lineSize` is int_array8, while `av_image_copy` expects `int_array4`.

This code works fine on windows 10, using ffmpeg libraries provided in this repository, and performs the required copying. However, on linux (CentOS 8), it fails with segmentation fault. Analyzing dump shows the last function in callstack is `av_image_copy`.

I copied definition of `av_image_copy` in the following way, for debugging purposes:

```
[SuppressUnmanagedCodeSecurity]
[DllImport("avutil", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_image_copy")]
public static extern void av_image_copy(ref byte_ptrArray4 dst_data, ref int_array4 dst_lineSize, ref byte_ptrArray4 src_data, int_array4 src_linesizes, AVPixelFormat pix_fmt, int width, int height);
```
As expected, it fails with segfault the same way as original `ffmpeg.av_image_copy`. However, if I add `ref` to `src_linesizes`, or change int to `int[] src_linesizes`, without changing anything else in the code (except passing it by ref at calling site) - it starts to work on CentOS 8 too

```
 public static extern void av_image_copy(ref byte_ptrArray4 dst_data, ref int_array4 dst_lineSize, ref byte_ptrArray4 src_data, ref int_array4 src_linesizes, AVPixelFormat pix_fmt, int width, int height);
```
With the change above it continues to work on Windows 10 too.

Unfortunately I cannot provide minimal reproducable example right now, but maybe information above can help investigate the issue.

**Comment by Ruslan-B** [comment]
Hi there it seems to be inconsistency in garbage collection between platforms, besides all fixed array types being brought to eliminate all others errors. I know for a long time difference in ffmpeg api wrt 4 and 8  fixed arrays it is not something I invented, but C is more forgiving than C#. Any way I can setup a virtual machine, however, it would be nice to have minimal falling example for CentOS.

**Comment by EvK** [comment]
Here is standalone sample code which roughly represents the path in my real code where it segfaults, and which you can copy-paste and run:

```
        static unsafe void AvFrameCopySegfaultRepro(bool segfault) {
            ffmpeg.RootPath = @"/usr/lib64";
            var input = "http://techslides.com/demos/sample-videos/small.mp4";
            AVFormatContext* fmtCtx = null;
            ffmpeg.avformat_open_input(&fmtCtx, input, null, null);
            ffmpeg.avformat_find_stream_info(fmtCtx, null);
            for (int i = 0; i < fmtCtx->nb_streams; i++) {
                var st = fmtCtx->streams[i];
                if (st->codecpar->codec_type == AVMediaType.AVMEDIA_TYPE_VIDEO) {
                    var codec = ffmpeg.avcodec_find_decoder(st->codecpar->codec_id);
                    var decCtx = ffmpeg.avcodec_alloc_context3(codec);
                    ffmpeg.avcodec_parameters_to_context(decCtx, st->codecpar);
                    ffmpeg.avcodec_open2(decCtx, codec, null);
                    var pkt = ffmpeg.av_packet_alloc();
                    var frame = ffmpeg.av_frame_alloc();
                    ffmpeg.av_read_frame(fmtCtx, pkt);
                    ffmpeg.avcodec_send_packet(decCtx, pkt);
                    ffmpeg.avcodec_receive_frame(decCtx, frame);

                    var canvasFrame = ffmpeg.av_frame_alloc();
                    canvasFrame->width = frame->width;
                    canvasFrame->height = frame->height;
                    canvasFrame->format = frame->format;
                    ffmpeg.av_frame_get_buffer(canvasFrame, 0);

                    var dstData = new byte_ptrArray4();
                    dstData[0] = canvasFrame->data[0];
                    dstData[1] = canvasFrame->data[1];
                    dstData[2] = canvasFrame->data[2];
                    var canvasLineSize = new int_array4();
                    canvasLineSize.UpdateFrom(canvasFrame->linesize);
                    var cellFrameData = new byte_ptrArray4();
                    cellFrameData.UpdateFrom(frame->data);
                    var cellLineSize = new int_array4();
                    cellLineSize.UpdateFrom(frame->linesize);
                    if (segfault)
                        ffmpeg.av_image_copy(ref dstData, ref canvasLineSize, ref cellFrameData, cellLineSize, (AVPixelFormat) frame->format, frame->width, frame->height);
                    else
                        working_av_image_copy(ref dstData, ref canvasLineSize, ref cellFrameData, ref cellLineSize, (AVPixelFormat) frame->format, frame->width, frame->height);
                }
            }
        }
        
        [SuppressUnmanagedCodeSecurity]
        [DllImport("avutil", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            CharSet = CharSet.Ansi, ExactSpelling = true,
            EntryPoint="av_image_copy")]
        public static extern void working_av_image_copy(ref byte_ptrArray4 dst_data, ref int_array4 dst_lineSize, ref byte_ptrArray4 src_data, ref int_array4 src_linesizes, AVPixelFormat pix_fmt, int width, int height);
```
If called with `segfault` parameter as `true` - it uses native FFMpeg.AutoGen `av_image_copy` and segfaults on CentOS 8 as descirbed above. Otherwise it uses "fixed" (though I have no idea if it's really a viable fix or not) version and does not segfault.

**Comment by Ruslan-B** [comment]
Thank you, I'll look into and most-probably try to change generation if possible in general way. I do predict to get some unhappy windows users, it basically breaking change but it never being fully possible to maintain simplicity and backwards comparability.

**Comment by Ruslan-B** [comment]
After investigation it can be garbage collection I think as value types already fixed stack and it looks like marshaling issue and bug in dotnet. I'll try to workaround this but going to take some time.

**Comment by Ruslan-B** [comment]
I think we should close this issue as it seems to be working fine on other platforms and feels like a bug in .net marshaling on specific platform. Could you please retest this using .net5?

**Comment by Ruslan-B** [comment]
closing issue as it stalled
