### ISSUE TITLE
sizeof(AVOption) should be 64 instead of 88 in x64

### ISSUE THREAD

**Issue by sdcb** [Ruslan-B/FFmpeg.AutoGen#141]
[x] bug report

* Summary
sizeof(AVOption) should be 64 in x64 and 48 in x86, but turns out it's 88.

* Code to reproduce: 
Console.WriteLine(sizeof(AVOption); // 88, should be 64

I believe the C `union` caused this issue, which generate more size than expected.:
```c
    /**
     * the default value for scalar options
     */
    union {
        int64_t i64;
        double dbl;
        const char* str;
        /* TODO those are unused now */
        AVRational q;
    } default_val;
```

It will generate: 
```csharp
public struct AVOption_default_val
{
	public long i64;

	public double dbl;

	public unsafe byte* str;

	public AVRational q;
}
```

* **motivation / use case **
Just research and fun :)

* Environment info
FFmpeg: 4.3.1 x64 GPL from https://ffmpeg.zeranoe.com/builds/
FFmpeg.AutoGen: 4.3.0.1 from NuGet

**Comment by Ruslan-B** [comment]
Thank you, indeed It is a serious issue, by the fact all union types generated in a wrong way. I'll this fix asap.

**Comment by sdcb** [comment]
Also maybe you also want add `[StructLayout(LayoutKind.Sequential)]` in every struct generated from ffmpeg :)

**Comment by sdcb** [comment]
Bug fix demo:
```csharp
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct AVOptionBugFixed
    {
        public byte* name;
        public byte* help;
        public int offset;
        public AVOptionType type;
        public AVOptionDefaultBugFixed default_val;
        public double min;
        public double max;
        public int flags;
        public byte* unit;
    }

    [StructLayout(LayoutKind.Explicit)]
    public unsafe struct AVOptionDefaultBugFixed
    {
        [FieldOffset(0)]
        public long i64;

        [FieldOffset(0)]
        public double dbl;

        [FieldOffset(0)]
        public byte* str;

        [FieldOffset(0)]
        public AVRational q;
    }
```

**Comment by Ruslan-B** [comment]
Thanks, yes, I'm aware. However, ```[StructLayout(LayoutKind.Sequential)]``` is redundant.

**Comment by sdcb** [comment]
Hey @Ruslan-B you got any progress for this?
