### ISSUE TITLE
Checks in encode example can fail on valid YUV420P frames

### ISSUE THREAD

**Issue by sipsorcery** [Ruslan-B/FFmpeg.AutoGen#144]
Thx for all the work put into this library! I wouldn't have believed it was possible to make `ffmpeg` easier to use from C# than C++ but this library has done it!

This is a trivial issue for the H264 video encode example. I thought I'd log it in case it helps someone else avoid some head scratching.

The checks [here](https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/077355e86d3f801b4ad63ab0d2e2ae4a7940a9a0/FFmpeg.AutoGen.Example/H264VideoStreamEncoder.cs#L57) can fail in cases where the `AVFrame` is valid.

Specifically if a frame is using padding then the linesizes won't be exact. In my case my I420 frame is 540x360 and the `YUV420P` line sizes are [640, 320, 320]. The frame has come from using ffmpeg to decode an `mp4` file rather than being manually created. I changed the checks below to use `<` rather than `!=`.

```
if (frame.linesize[0] != _linesizeY) throw new ArgumentException("Invalid Y linesize.", nameof(frame));
if (frame.linesize[1] != _linesizeU) throw new ArgumentException("Invalid U linesize.", nameof(frame));
if (frame.linesize[2] != _linesizeV) throw new ArgumentException("Invalid V linesize.", nameof(frame));
```

I also encountered a case on `macosx` where the `data` pointers are not in contiguous memory meaning the checks below will always fail. I removed these two checks in my app.

```
if (i420Frame.data[1] - i420Frame.data[0] < _ySize) throw new ArgumentException("Invalid Y data size.", nameof(i420Frame));
if (i420Frame.data[2] - i420Frame.data[1] < _uSize) throw new ArgumentException("Invalid U data size.", nameof(i420Frame));
```

**Comment by Ruslan-B** [comment]
Thank you for sharing with us. I've updated example.
