### ISSUE TITLE
Clarification about generation on Windows

### ISSUE THREAD

**Issue by ksze** [Ruslan-B/FFmpeg.AutoGen#15]
Can you provide more clarifications about running `python generate.py` on Windows?

First of all, it appears that you can't use Python 2.7 from Cygwin (64-bit), as it doesn't know about `WindowsError` and results in a name error.

Second of all, can I use MinGW-w64? If so, what installation option should I use?

  - Threads: posix or win32?
  - Exceptions: seh or sjlj?

**Comment by Ruslan-B** [comment]
Python 2.7 (x64) for Windows
https://www.python.org/downloads/release/python-2710/
As for MinGW - only basic gcc is needed the rest is by default as it not suppose to compile anything.
After generation some minor tweaks are needed in FFmpegInvoke.cs in order to compile it.

**Comment by Ruslan-B** [comment]
closing #15 - generation is moving from python to clangsharp
