### ISSUE TITLE
gpu decode broken on linux

### ISSUE THREAD

**Issue by ispysoftware** [Ruslan-B/FFmpeg.AutoGen#150]
Linux uses the VAAPI decoder which is set in the example program.cs to use the AV_PIX_FMT_VAAPI pixel format. This format is not supported by sws_getContext and returns null when the convertcontext is created (and then crashes). Should be modified to use AV_PIX_FMT_NV12 which works.

case AVHWDeviceType.AV_HWDEVICE_TYPE_VAAPI:
                    return AVPixelFormat.AV_PIX_FMT_NV12;

https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/db9bcd4b9dfad5d117ffd71fe1a2d073e96a3520/FFmpeg.AutoGen.Example/Program.cs

**Comment by ispysoftware** [comment]
same with cuda:
```
case AVHWDeviceType.AV_HWDEVICE_TYPE_CUDA:
                    return AVPixelFormat.AV_PIX_FMT_NV12; //AV_PIX_FMT_CUDA;
```

**Comment by Ruslan-B** [comment]
I'll update example as suggested.
