### ISSUE TITLE
Where is the download of the relevant DLL library resources?

### ISSUE THREAD

**Issue by 527395632** [Ruslan-B/FFmpeg.AutoGen#153]
Thread ERROR Message：Unable to load DLL 'swscale.5': The specified module could not be found.

![image](https://user-images.githubusercontent.com/20411721/110093171-5a371f00-7dd5-11eb-83b1-d23b38da7880.png)

**Comment by zgabi** [comment]
Just read the readme, it is written there.......
https://github.com/Ruslan-B/FFmpeg.AutoGen

**Comment by 527395632** [comment]
According to the prompt, I found the corresponding library file, but an error was reported after running. The specific error location is shown in the figure below

Main Method:  EncodeImagesToH264();
![image](https://user-images.githubusercontent.com/20411721/110101384-6bd0f480-7dde-11eb-9f60-b852aea5a59d.png)

EncodeImagesToH264 Method: using (var vse = new H264VideoStreamEncoder(fs, fps, destinationSize))
![image](https://user-images.githubusercontent.com/20411721/110101417-75f2f300-7dde-11eb-9176-31f5c0f303c9.png)

H264VideoStreamEncoder ConstructorMethod: ffmpeg.avcodec_open2(_pCodecContext, _pCodec, null); retCore=-542398533, ErrorMessage: Generic error in an external library
![image](https://user-images.githubusercontent.com/20411721/110101146-2dd3d080-7dde-11eb-9438-a14259b6dd0f.png)

**Comment by Ruslan-B** [comment]
Can you provide log file from app console?

**Comment by 527395632** [comment]
The console log information is as follows:

Current directory: C:\Users\Administrator\Desktop\FFmpeg.AutoGen-master\FFmpeg.AutoGen.Example\bin\x64\Debug\netcoreapp2.0
Running in 64-bit mode.
FFmpeg binaries found in: C:\Users\Administrator\Desktop\FFmpeg.AutoGen-master\FFmpeg.AutoGen.Example\bin\x64\Debug\netcoreapp2.0\FFmpeg\bin\x64
FFmpeg version info: 4.3.1-2020-10-01-full_build-www.gyan.dev
[libx264 @ 0000024ab7108f00] width not divisible by 2 (871x531)

C:\Program Files\dotnet\dotnet.exe (进程 9428)已退出，代码为 -1。
要在调试停止时自动关闭控制台，请启用“工具”->“选项”->“调试”->“调试停止时自动关闭控制台”。
按任意键关闭此窗口. . .

![image](https://user-images.githubusercontent.com/20411721/110276428-0c592b80-800e-11eb-8c3c-e4dae8dc5f43.png)
At the same time, I also zip the whole project and put it on Alibaba cloud server. The download address is: http://47.101.161.139:8080/FFmpeg.AutoGen-master.zip

**Comment by Ruslan-B** [comment]
hmm apparently you over did something if you checkout fresh repo it should look like this:
```
Current directory: C:\dev\FFmpeg.AutoGen\FFmpeg.AutoGen.Example\bin\x64\Debug\netcoreapp2.0
Running in 64-bit mode.
FFmpeg binaries found in: C:\dev\FFmpeg.AutoGen\FFmpeg\bin\x64
FFmpeg version info: 4.3.1-2020-10-01-full_build-www.gyan.dev
Use hardware acceleration for decoding?[n]
```
However I don't see that much wrong with exception you already modified example and you question falls in the none bindings problem rather than ffmpeg usage. 
I am closing the issue.

**Comment by Ruslan-B** [comment]
I am closing

**Comment by Ruslan-B** [comment]
Downloaded you project the thing here you are commented decode step and it creates a set images to encode and uses the first image to set encoding parameters.
You should be a aware FFMPEG is complex an unforgiving beast - it is better to look and read the code you have - and triple check check on it - instead of investing time into creating issue like this and calling other to help you - were we simply can't.
Like physically i.e. we don't have access to your environment or time wise - be have to feed our families.
Reference wise to double check on lines you commented and to write this message - cost roughly 75 EURO .
Hence, I like to have this comment as I'll refer to it every other time.

**Comment by Ruslan-B** [comment]
Ah I see now you have images , you should just use command line version of ffmpeg if like to encode images to video. I am moving this question to another repo as it has nothing to do with the binging - rather haw to use ffmpeg api right - which is beyond the scope of this project.
