### ISSUE TITLE
no methods added when targeting FFmpeg 2.7.x

### ISSUE THREAD

**Issue by BrannonKing** [Ruslan-B/FFmpeg.AutoGen#16]
I was attempting to run your generation script on a recent build of FFmpeg. It generates the structs okay but not the methods. I was using MSYS2. I need a custom LGPL build of FFmpeg that has the  --enable-small and I also need the ffmpeg.exe itself included alongside the DLLs. When running the generated code downloaded from this site, I get a memory corruption error in release compiles. Please consider an update here. Thanks.

**Comment by mariodivece** [comment]
I was trying to do the same. I tried compilation from scratch (in Ubuntu) and modifying the generate.py to match FFmpeg 2.8 (including library names and stuff). Generates the structs okay but not the methods. Since this project has not been updated for some time now I just had to stick with a prior version. @Ruslan-B  hopefully you are able to update this awesome project as it is the only true, complete wrapper for .net FFmpeg interop out there.

**Comment by BrannonKing** [comment]
I was able to compile FFmpeg 2.5.8 and it appears to work with the generated wrapper. I'll be using that in the mean time.

**Comment by Ruslan-B** [comment]
To claim my fellow community :). I'm trying to switch generation to CastXML to simplify further support. The switch is quite effort by itself as assembly of CastXML is pretty tedious process, and that's the reason why I not invest time in current updates.

**Comment by superware** [comment]
Ruslan-B, that's great news. I don't want to sound rude, but when do you think we'll be able to start beta testing? :)

**Comment by Ruslan-B** [comment]
@superware, like I said it is tedious process, as for example it took several days just to assemble CastXML and it did appear it is far from what I need.
Right now I'm testing http://www.clangsharp.org so far it looks promising, should be able to get test example running by the end of this week (eta this Saturday). Then I'll create experimental branch as soon example project start working again. 
I'll keep you posted as for progress.

**Comment by Ruslan-B** [comment]
@superware, experimental branch is available for testing.

**Comment by Ruslan-B** [comment]
2.8.1 promoted to master
