### ISSUE TITLE
HDR Support (New Feature)

### ISSUE THREAD

**Issue by SuRGeoNix** [Ruslan-B/FFmpeg.AutoGen#161]
Hey @Ruslan-B 

Hope you doing well! My video player is thirsty for even more quality 😋 

I had a quick look to support BT.2020 and HDR and I've noticed that I don't have access to AVMasteringDisplayMetadata structure. (Not sure if more structures are required yet)

Best Regards,
J

**Comment by Ruslan-B** [comment]
Hi there,, is this API a part of 4.3? 
If so could you please pint point to C header files you looking for support, as blunt search gives zero matches.

**Comment by SuRGeoNix** [comment]
Sure, it seems that's the one!

https://github.com/FFmpeg/FFmpeg/blob/release/4.3/libavutil/mastering_display_metadata.h

**Comment by Ruslan-B** [comment]
right, (I am scratching my heads search in new VS is broken beyond repair :))
give me few hours

**Comment by Ruslan-B** [comment]
Updated package:
https://www.nuget.org/packages/FFmpeg.AutoGen/4.3.2

Closing issue, if something missing from HDR API fell free to reopen

**Comment by SuRGeoNix** [comment]
That was fast, thanks!

I just had a quick look, I was able to get the AVMasteringDisplayMetadata data, however they came with the wrong order. You have an array6[2] instead of array3[2] +array1[2] of AVRationals.

![Untitled](https://user-images.githubusercontent.com/57474895/111885525-07fb1e00-89d1-11eb-9213-18271b5d9e4b.png)


I hit another wall with SharpDX as is deprecated (had to create my own structure to pass to SetHDRMetaData, no errors but it had no effect). I will give it another try but I'm afraid the only way to have HDR on Flyleaf will be by re-coding it in c++

**Comment by Ruslan-B** [comment]
I'll reopen issue as it seems something new with respect to nested arrays. However, can help you with SharpDX.

**Comment by SuRGeoNix** [comment]
Can we even find SharpDX's latest nuget package (4.2.0) source code (github has an older version)?
I might skip true HDR for now and just focus on HDR->SDR as Flyleaf is mainly for PC monitors (usually no HDR)

**Comment by Ruslan-B** [comment]
https://github.com/sharpdx/SharpDX/tree/v4.2.0 this one?

**Comment by SuRGeoNix** [comment]
No, I've checked... for example it misses the Output6 and HdrMetadataHdr10 structure that I'm currently accessing from nuget package (no idea how back it is)

**Comment by Ruslan-B** [comment]
Well I'll fix the bug in generator - I think will be ready tomorrow during day, but cannot do much with respect to SharpDX. 
However I'm using SharpDX.DirectInput for one of my pet projects but novadays I far from FFmpeg, DirectX and OpenGL stuff :).

**Comment by SuRGeoNix** [comment]
There is no rush for the fix. I've left HDR for now as it requires more research and TIME.

DirectX is a pain in the ass (especially in c#, imagine I've started with monogame, now sharpDX and probably soon only .h) and I've not be serious with it yet. Just enough to make the player smooth but it requires a lot of work and has a lot of "secrets" (no documentations/samples) that I would like to mess later on (effects / tone mappers / shaders etc.).

**Comment by Ruslan-B** [comment]
Done Done https://www.nuget.org/packages/FFmpeg.AutoGen/4.3.2.1
