### ISSUE TITLE
Example fails to run with qsv (qsv is not supported as input pixel format)

### ISSUE THREAD

**Issue by jackfrombb** [Ruslan-B/FFmpeg.AutoGen#165]
Hi)
I runing an FFmpeg.AutoGen.Example then select qsv for hardware acceleration and receive Exception __pConvertContext == null_ [(VideoframeConverter.cs)](https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/542c833f470effeb7cda8606c68bf983a5a6309e/FFmpeg.AutoGen.Example/VideoFrameConverter.cs#L24)

In Console:
```
[tcp @ 000001dbb91d6900] Starting connection attempt to 78.46.4.188 port 80
[tcp @ 000001dbb91d6900] Successfully connected to 78.46.4.188 port 80
[h264 @ 000001dbb91db6c0] Reinit context to 640x368, pix_fmt: yuv420p
[AVHWDeviceContext @ 000001dbb926e000] Using D3D9Ex device.
[AVHWDeviceContext @ 000001dbb926dc80] Initialize MFX session: API version is 1.34, implementation version is 1.33
codec name: h264
major_brand = mp42
minor_version = 1
compatible_brands = mp42avc1
creation_time = 2010-02-09T01:55:39.000000Z
[swscaler @ 000001dbb9227140] qsv is not supported as input pixel format
```

Win 10, VS 2019
i5-7300U (Intel HD Graphics 620)

What am I doing wrong?

In russian:
Привет)
Пытаюсь запустить FFmpeg.AutoGen.Example с использованием qsv. После выбора ускорителя вылетает исключение __pConvertContext == null
В консоли последней строчкой qsv is not supported as input pixel format.

В чем может быть проблема? Буду рад любой помощи.

**Comment by Ruslan-B** [comment]
Hi there,
Technically your issue against repo rules, but I give few weeks - maybe someone other reply you, but it is less likely - the only one who can help is likely you :). As with FFMPG you can do dozens things slightly wrong. 
After  few weeks I'll move issue to questions repository.
However, if happens you google around last line you might find this: https://www.google.com/search?q=qsv+pixel+format&rlz=1C1CHBF_enNL878NL878&oq=qsv+pixel+format&aqs=chrome..69i57j0i22i30l3j69i61l3.4393j0j7&sourceid=chrome&ie=UTF-8 
It seems QuickSync pixel format might be unknown to FFmpeg scaler.

**Comment by jackfrombb** [comment]
Thanks. I hope someone will help)

I'm trying to migrate the example from [official docs](https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/qsvdec.c) and noticed that the structure **AVQSVFramesContext**  is missing. But I don't know how to solve it

[The structure is used here](https://github.com/FFmpeg/FFmpeg/blob/3e44bd068fc19baeaab3295fce8379c68e4b2b2a/doc/examples/qsvdec.c#L57)

**Comment by Ruslan-B** [comment]
I'll look for AVQSVFramesContext and try to add it to bindings generator, bear with me :).

**Comment by jackfrombb** [comment]
Can you briefly tell me about the generation?
I will read the assembly instructions and try to build it.
I have already downloaded the Intel [Media SDK](https://software.intel.com/content/www/us/en/develop/tools/media-sdk.html) and now I think where to screw it)
Thank you for your help.

**Comment by jackfrombb** [comment]
I decided that ffmpeg generation was too much for me and I did it a [little easier](https://github.com/jackfrombb/CppSharpUnsafeGenerator/blob/main/IssueSolution.cs)

This works, but the decoding is not surprising with the speed (~+20%).
It is possible that the code needs to be optimized.
CPU load is lower than EmguCV(Tested on Windows Forms).
The QSV decoder takes a long time to initialize.

**Comment by Ruslan-B** [comment]
Glad to hear this. So far help yourself proved to be working advice ;).
