### ISSUE TITLE
Method  DecodeAllFramesToImages in Sample app throws an exception (Invalid parameters) when trying to create a new Bitmap in case custom resolution for example 638x478

### ISSUE THREAD

**Issue by ilchdeveloper** [Ruslan-B/FFmpeg.AutoGen#166]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x ] bug report
  - [x ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
 throws an exception (Invalid parameters) in line 117 on FFmpeg.AutoGen.Example/Program.cs

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
try to use input video file with resolution 638x478

* **What is the expected behavior?**
extract all frames without any exception

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- version: 3.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
Please use version 4.4, if the issue re occurs, please provide a sample file.
