### ISSUE TITLE
Make a stream wall (ffmpeg mosaic)

### ISSUE THREAD

**Issue by jeff9571** [Ruslan-B/FFmpeg.AutoGen#167]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

How to implement a fucntion like stream wall using [Here](url)?

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

* **What is the expected behavior?**

combine multiple rtsp stream to one stream

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- version: 4.4.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
The link is broken.
But, the only way I can classify this issues is - **support request or question**. As you already have an all necessary API to achieve this. So it has nothing to do with bindings.

**Comment by jeff9571** [comment]
I've re set the , [Link](https://trac.ffmpeg.org/wiki/Create%20a%20mosaic%20out%20of%20several%20input%20videos%20using%20xstack) , how can i achieve this using ffmpeg autogen?

**Comment by jeff9571** [comment]
> The link is broken.
> But, the only way I can classify this issue is - **support request or question**. As you already have an all necessary API to achieve this. So it has nothing to do with bindings.

I've re set the  [link](https://trac.ffmpeg.org/wiki/Create%20a%20mosaic%20out%20of%20several%20input%20videos%20using%20xstack) how can i achieve this using ffmpeg autogen?

**Comment by Ruslan-B** [comment]
Yes, I think it is very possible. But, you need to understand the difference between FFmpeg API and ffmpeg.exe.
You have to decode, convert and rescale your video streams (on different threads I guess) and then assemble one canvas by blitting your output of individual channels into one big canvas (bitmap). Provided you have already example and C# skills it should trivial.
