### ISSUE TITLE
HLS demuxer (feature request)

### ISSUE THREAD

**Issue by SuRGeoNix** [Ruslan-B/FFmpeg.AutoGen#168]
Hey @Ruslan-B , hope you are doing well. Yet another request when you are available. Mainly I'm trying to allow users to HLS seek or change playlists/segments which I'm not able to do with the current exposure. By reading ffmpeg's code it all goes down to [hls.c](https://www.ffmpeg.org/doxygen/trunk/hls_8c_source.html#l00192) and HLSContext structure which can be obtain from AVFormatContext->priv_data. No rush, but it will be nice to have!

**Comment by Ruslan-B** [comment]
Hi @SuRGeoNix, I not sure it will be possible to fulfill this request with in the scope of this project . As generation happens against publicly available API (include files, shipped with precompiled binaries) and ```hls.c``` is not a part of public API. 
Means, it should be a high level API available, otherwise, it is internals of FFmpeg implementation.  
There is even section in ```avformat.h```:
```
 * @section lavf_options Passing options to (de)muxers
 * It is possible to configure lavf muxers and demuxers using the @ref avoptions
 * mechanism. Generic (format-independent) libavformat options are provided by
 * AVFormatContext, they can be examined from a user program by calling
 * av_opt_next() / av_opt_find() on an allocated AVFormatContext (or its AVClass
 * from avformat_get_class()). Private (format-specific) options are provided by
 * AVFormatContext.priv_data if and only if AVInputFormat.priv_class /
 * AVOutputFormat.priv_class of the corresponding format struct is non-NULL.
 * Further options may be provided by the @ref AVFormatContext.pb "I/O context",
 * if its AVClass is non-NULL, and the protocols layer. See the discussion on
 * nesting in @ref avoptions documentation to learn how to access those.
 ```

**Comment by SuRGeoNix** [comment]
Yep, can't do much with those... already checked. What I was thinking is, as I can pass "live_start_index" option to HLS demuxer and start the stream from another segment, it would be nice to know how many segments it has and the duration for each one. And that's also a dynamic information. So I guess the only way to access it, it would be through the HLSContext. Feel free to close it as I told you... just a thought!

**Comment by Ruslan-B** [comment]
Well you can try to port this structure by hand. 
Another option custom fork of this project -  just clip what you need from ```hls.c``` - the structure and all dependencies and include into generation process but adding another include file from different location.

**Comment by SuRGeoNix** [comment]
In case someone else needs it I'm attaching the main structures I used to accomplish HLS live seek. After asking ffmpeg devs they confirmed that there is not currently a publicly/proper way of doing this, I might open an issue at track for this. Additionally, AVFMTCTX_UNSEEKABLE  should be removed from ic->ctx_flags to allow seeking.

[HLSContext.txt](https://github.com/Ruslan-B/FFmpeg.AutoGen/files/6924695/HLSContext.txt)
