### ISSUE TITLE
Cannot load  FFmpeg dlls under Docker Linux environment

### ISSUE THREAD

**Issue by Altair7610** [Ruslan-B/FFmpeg.AutoGen#169]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - :white_check_mark: bug report
  - :black_square_button: feature request
  - :black_square_button: support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

* **What is the current behavior?**
I have ASP .NET Core 3.1 LTS Docker environmet. My solution consists of couple of projects. One of them is BLL with injected FFmpeg.AutoGen. As far as it requieres compiled FFmpeg libraries I take it on my own and compiled them in another Docker container  running Ubuntu. I also checked it after compilation and installing - works like a charm. Ok, I take my libraries and put them to folder in my project, so they are copying to output directory and visible there. ffmpeg.Root.Path is app working directory "/app/" containing my dlls. By it can`t load them throwing ```Unable to load DLL``` exception. I tried making symlinks to compiled libs named 'lib{module_name}.so{version}' at "/usr/lib/" and change RootPath to it but also no luck.
Maybe it’s me a fool and you could tell me what I’m doing wrong:confused: (I use it on Windows with dlls compiled by myself and everything is working, but here...) Libs I am using can be found here - https://dropmefiles.com/fYmAB (it is libs i get from Linux container when they are compiled. Firstly I renamed them to format AutoGen expected, but later when trying using symlinks, dlls names are keeping original, symlinks are rightly named)
Symlinks in /usr/lib pointing to /app/
![Безымянный](https://user-images.githubusercontent.com/26084282/127961109-051dc8cf-5cf0-4629-b422-643454c66c5a.png)
/app/ directory
![Безымянный](https://user-images.githubusercontent.com/26084282/127961238-3c57fe26-4352-41a0-b6cd-e470f955517b.png)
/usr/lib symink example
![Безымянный](https://user-images.githubusercontent.com/26084282/127961384-6905fafa-f719-4e4d-80f3-bfc14bce1bed.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
Make example Linux project with FFmpeg .so libs, and call ```ffmpeg.avdevice_register_all();```.

* **What is the expected behavior?**
Loaded libraires.

* **What is the motivation / use case for changing the behavior?**
It`s impossible to use that awesome product in Docker

* **Please tell us about your environment:**

- version: 4.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
Uh oh, I don't think it is a bug. Nonetheless, you indicated you are using 3.4 .net package, right? 
However, versions of ffmpeg binaries looking like they came from ffmpeg 4+.

**Comment by Altair7610** [comment]
@Ruslan-B, sry for misleading, i forget to change it. I am using latest package version latest which avalaible at nuget, 4.4, correct it in first comment

**Comment by Ruslan-B** [comment]
Okay then, and another silly question but did you check permissions?

**Comment by Ruslan-B** [comment]
besides you don't need create symlinks you can overload ffmpeg.GetOrLoadLibrary.
Can you debug your docker as well?

**Comment by Altair7610** [comment]
@Ruslan-B  sure, I can connect to container via VS and bash. I will check dll permission right now, if the resaon is... :scream::boom:

**Comment by Altair7610** [comment]
Checked DLLs permissions right now, set a+rwx to all of them, but it still not loading. Just for fun executed ```System.IO.File.Exists("/app/libavutil.so.56")``` in VS Immediate Windows, it says true)

**Comment by Ruslan-B** [comment]
Well I guess, you need to make sure `your docker has ``libdl.so.2``` if it is then to overload ```ffmpeg.GetOrLoadLibrary``` with your implementation and call ```LinuxNativeMethods.dlopen(libraryName, LinuxNativeMethods.RTLD_NOW)``` and debug it.

**Comment by Altair7610** [comment]
All right, I feel myself very stupid, but i have to sit on it for a while. Its my message for all who as who like me will use self compiled ffmpeg libs in asp net docker container. First of all you need compile them in the same container that they will be run. For me I pick ```mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim``` version. Its the simpliest way, because othewise you must choose linux distributieve that maches GLIBC version. I accidentally saw that the version required by the package is higher than what can be installed in the container. For asp net 3.1 container GLIBC is 2.28.10. And secondly you need to install some dependencies to your container. Just run ```apt-get update -y``` and ```apt-get install -y libva-dev``` to get everything you need. After hours of debug, research and reading linux manuals I get it. @Ruslan-B sorry, for my silly head, its not a bug, everything is working like a charm. Thank you!

**Comment by Ruslan-B** [comment]
@Altair7610 no worries, I am happy. 
As it was constructive conversation, we have a lot of contemplative here - were people cannot express themselves.
Initially it was clear it has nothing to do with the bindings, but hey we have a history to search on.
Good luck!

**Comment by Ruslan-B** [comment]
P.S. Any points to improve the project are welcome - like you need an additional tracing or debug info. As I keep it running for years without feedback and I am not using it for years any more. Quite bizarre but hey it works :)
