### ISSUE TITLE
AccessViolationException while running in multiple threads

### ISSUE THREAD

**Issue by arvindsouza** [Ruslan-B/FFmpeg.AutoGen#170]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

I have a number of IP cameras on a network, I am trying to fetch snapshots from all of them simultaneously using threading. However I am getting the following error 

"Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt"

This error occurs when the VideoStreamDecoder is initialized. Every thread initializes a new instance of the VideoStreamDecoder class
Below is the Initialize method of the VideoStreamDecoder class:

 ```
public VideoStreamDecoder(string url, AVHWDeviceType HWDeviceType = AVHWDeviceType.AV_HWDEVICE_TYPE_NONE) 
{
            string exeDir = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
            ffmpeg.RootPath = $"{exeDir}/x64";

            _pFormatContext = ffmpeg.avformat_alloc_context();
            _receivedFrame = ffmpeg.av_frame_alloc();

            var pFormatContext = _pFormatContext;
            ffmpeg.avformat_open_input(&pFormatContext, url, null, null);
            ffmpeg.avformat_find_stream_info(_pFormatContext, null); // Line that's throwing the error

            AVCodec* codec = null;

            _streamIndex = ffmpeg.av_find_best_stream(_pFormatContext, AVMediaType.AVMEDIA_TYPE_VIDEO, -1, -1, &codec, 0);
            _pCodecContext = ffmpeg.avcodec_alloc_context3(codec);

            ffmpeg.avcodec_parameters_to_context(_pCodecContext, _pFormatContext->streams[_streamIndex]->codecpar);
            ffmpeg.avcodec_open2(_pCodecContext, codec, null);

            CodecName = ffmpeg.avcodec_get_name(codec->id);
            FrameSize = new Size(_pCodecContext->width, _pCodecContext->height);
            PixelFormat = _pCodecContext->pix_fmt;

            _pPacket = ffmpeg.av_packet_alloc();
            _pFrame = ffmpeg.av_frame_alloc();
}
```

The error is thrown on the line `ffmpeg.avformat_find_stream_info(_pFormatContext, null);`
does the VideoStremaDecoder allocate the same block of memory to the _pFormatContext even across multiple threads?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**:

Attempt to initialize VideoStreamDecoder using 
` mVideoStreamDecoder = new VideoStreamDecoder(url,DeviceType);`

on multiple threads simultaneously

* **What is the expected behavior?**

No System.AccessViolation exception, each thread returns an AVFrame object for the specified url

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

.Net Framework 4.6.1
ffmpeg.AutoGen 4.3.0.1

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
Hmm interesting but not connected to bindings though - interop particularity. I think you facing the issue because of managed garbage collection. Keep in mind dotnet threads are paused during GC but unmanaged part of FFmpeg still might be working.
However, without access to your implementation it an educated guess. 
The best possible solution in your case is to spawn processes - not threads or other kind of isolation.
I'll keep this issue open - most-probably  you figure it out yourself - but I can be yellow rubber duck :).

**Comment by Ruslan-B** [comment]
Look into the code - the only place it might fail - it is GetFunctionPointer but hard to imagine it will give different results - it is not thread safe but as I indicated should not create a problem.

**Comment by arvindsouza** [comment]
Hmm what would be the optimal way to poll the same camera on multiple threads at the same time?

I am initializing a new videostreamdecoder on each thread and I have no issues connecting to multiple different streams in parallel

The issue only happens when I attempt to connect to the same ip camera on more than 2 threads simultaneously, maybe it's a limitation of the camera itself?

For now I'm using the same static instance of VideoStreamDecoder across all the threads polling the same camera and using Monitor.Enter to block the threads so these threads so they don't process simultaneously, seems to be working so far

**Comment by Ruslan-B** [comment]
Complicated but did you check this project https://github.com/ispysoftware/iSpy?

**Comment by arvindsouza** [comment]
No, I'll check it out. Thanks for the help, much appreciated :)

**Comment by arvindsouza** [comment]
I resolved this using Monitors to ensure that multiple requests are not processed simultaneously for a given stream url.

One more question. If the specified url is unreachable or the stream is not retrievable, is there a way to check and timeout when initializing the VideoStreamDecoder?

` ffmpeg.avformat_find_stream_info(_pFormatContext, null);` this line throws an AccessViolationException when the specified video stream is irretrievable

**Comment by Ruslan-B** [comment]
By using google :) https://stackoverflow.com/questions/10715170/receiving-rtsp-stream-using-ffmpeg-library
