### ISSUE TITLE
Application dies when the ffmpeg.avformat_find_stream_info() function is called

### ISSUE THREAD

**Issue by Altair7610** [Ruslan-B/FFmpeg.AutoGen#171]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - :white_check_mark: bug report
  - :black_square_button: feature request
  - :black_square_button: support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
I want to request a bug.

* **What is the current behavior?**
I am decoding ip camera rtsp stream and processing frames from it. My app is tested on Windows and everything is running smooth, so I decided to move to Linux and play with it too. My environment is Docker with Ubuntu and CentOS machine. So, everything is ok until I call ```ffmpeg.avformat_find_stream_info(formatContext, null);```. If Docker is running it goes crazy, lacking all his cpu and ram (I let him use 4 cores and 8 gigs), so it just dies with 157 error code (OOM). Linux machine hangs in the same place and killing my app after a few minutes with ```Killed``` message. Do you think this is a bug of the ffmpeg itself? Methods executed before getting stream info are fine (I called ```avdevice_register_all```,  ```avformat_network_init```, ```avformat_alloc_context```, ```avformat_open_input```).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

* **What is the expected behavior?**
Finding stream info and applying it to format context.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- version: 4.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Altair7610** [comment]
So, I compiled AutoGen in degub and checked that pointer to avformat_open_input is not null, so it begins execution, but with unexpected behavior

**Comment by Ruslan-B** [comment]
I assume I don't need to take any action here.
