### ISSUE TITLE
Reducing library's size (feature request)

### ISSUE THREAD

**Issue by SuRGeoNix** [Ruslan-B/FFmpeg.AutoGen#173]
If you are like me and you care even for few KBs you might want to consider adding this feature.
Just tried a very simple trick and reduce it about 100KBs in FFmpeg.functions.export.g.cs:

```csharp
public class PlatformNotSupportedException2 : Exception
        {
            public PlatformNotSupportedException2()
            {
            }

            public PlatformNotSupportedException2(string message)
                : base(message + " is not supported on this platform.")
            {
            }

            public PlatformNotSupportedException2(string message, Exception inner)
                : base(message + " is not supported on this platform.", inner)
            {
            }
        }
```

And then replaced PlatformNotSupportedException with PlatformNotSupportedException2 and replace " is not supported on this platform." with "".

**Comment by Ruslan-B** [comment]
I guess we can replace it with just NotSupportedException but first I have to check if it has positive impact. 
Any reason you’re concerned about extra 100Kb? As total size is about 780Kb.

Cheers,
Ruslan Balanukhin

**Comment by SuRGeoNix** [comment]
Not really, just surprised when I saw that it is that large. I bet it could be 100KB total with similar 'corrections'. No rush, just feature request you might want as well to add.

🍻

**Comment by Ruslan-B** [comment]
Okay, I'll take a look when I get back from vacation.

**Comment by SuRGeoNix** [comment]
Nice enjoy what left of it!

**Comment by Ruslan-B** [comment]
I tried to replace PlatformNotSupportedException with NotSupportedException and later with PlatformNotSupportedException2. I don't observe any change in the library size on any platform.

**Comment by Ruslan-B** [comment]
Technically it possible to create special assembly for windows with dll imports that will reduce the bloat - but... is the effort cost it?

**Comment by SuRGeoNix** [comment]
The example that I gave you it was reducing strings.... when you repeat the same string it will generate different strings in the file. Its not clever enough to 'zip' it. Don't waste too much time on it!

**Comment by Ruslan-B** [comment]
I admit you right, let me time to experiment with string table reduction as  this exception is extremely rare occasion - it will definitely pay back.

**Comment by Ruslan-B** [comment]
Closing issue, tried other ways but the only gain I discovered connected with exception message. It was about 82KB difference - which is implemented in linked PR.

**Comment by SuRGeoNix** [comment]
@Ruslan-B Thanks and I hope you didn't invest a lot of time on this one :)

**Comment by Ruslan-B** [comment]
No worries, I just tried few thing and realised that modern compiler does not create any duplicates in string table, roughly 95% of it reflection metadata.
