### ISSUE TITLE
Two tiers of example.

### ISSUE THREAD

**Issue by kant2002** [Ruslan-B/FFmpeg.AutoGen#178]
Would you consider have two tiers of examples? First tier is one to one FFMpeg examples which show how to use your library in FFMpeg way. Second tier is like your original example, which is more of C#-pish way which obviously easy to start and build upon. Order of tiers is not important. For example it's easy for me produce first kind of examples. But second require much more knowledge of FFmpeg which I currently have.

FFmpeg as a library a bit problematic, in a sense that it's hard to find easy to consume examples how to make it work, and sometimes they are outdated. You library was only library in C# land which allow me create RTSP stream from network stream of images, and it was because I was able to build on FFmpeg samples out there.

I think it can be a mistake providing only convenient wrapper to FFmpeg in examples, given how unforgiving FFmpeg itself.

**Comment by Ruslan-B** [comment]
Andrii , I think you right but we have to balance this as experience of consumers varying from flor to top.  Nonetheless, I looks like to me as great idea do develop this library further on. As used to do similar stuff in the past like [Muxing](https://gist.github.com/Ruslan-B/43d3a4219f39b99f0c9685290dcd23cc).
However some infrastructural convince going to be great asset - to allow run example right after build.

**Comment by kant2002** [comment]
Another suggestion. Maybe it would be practical advertise somewhere `Mono.Unix` package to get list of all POSIX error codes. It was not abvious to me that fmpeg error coded is Posix error codes. This may eliminate needs for PRs like this #180 180

**Comment by Ruslan-B** [comment]
@kant2002 As I learned from past OSX and *nix might have different error codes - like EAGAIN. I guess I can backport darwin header with all standard stuff.

**Comment by kant2002** [comment]
I notice that, and you can see what I was responded by .NET team, https://github.com/dotnet/runtime/issues/61351#issuecomment-963875006

you may not want to deal with all permutations given that .NET working on supporting more platforms then *Nix and Mac. Library produced by Mono team seems pretty standard staff to recommend using, instead of dealing with it yourself.

**Comment by Ruslan-B** [comment]
Well it seems we should scrap Mono atm. As M$ forces us to do so. I guess I can close this issue?
