### ISSUE TITLE
Decode multiple video on GPU

### ISSUE THREAD

**Issue by trancongnam** [Ruslan-B/FFmpeg.AutoGen#184]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug

* **What is the current behavior?**
I want to play multiple camera video streams simultaneously on winform application (up to 100 cameras maybe at a time). Therefore, to offloading for CPU, I would like to decode videos on discrete graphics or QSV.
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
I'm using the basic example in FFmpeg.AutoGen.Example  to decode multiple videos on a GPU. My main function is as follows:
```
 private static void Main(string[] args)
        {
           for (int i = 0; i < 11; i++)
            {
                url = @".\video\test" + i + ".mp4";
                new Thread(() =>
                {
                    DecodeAllFramesToImages(AVHWDeviceType.AV_HWDEVICE_TYPE_D3D11VA, url);
                }).Start();
            }
        }
```
However, an error occurs when i run thread count greater than 10. The error images is as follows:
    "System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory." [https://i.stack.imgur.com/5zJoG.jpg](url)
    And in the console screen there is an error message "Failed to create D3D11VA video decoder" and "Failed setup for format d3d11: hwaccel innitialisation returned error" [https://i.stack.imgur.com/Cj3KS.jpg](url)
* **What is the expected behavior?**
 I'm new to the ffmpeg.autogen library recently, so I don't know the problem very well, I would love to have your help with this error!
* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- version: 4.3.0.3
- CPU: Intel(R) Core(TM) i7-8700
- GPU: AMD radeon R7 430

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
Not a bug, FFmpeg recommends do **multi-process** scaling - not multi-threading. Even though you can try to put locks around falling sections as the most probably using native statics.
