### ISSUE TITLE
create RTSP to MP4 Example

### ISSUE THREAD

**Issue by 183demao** [Ruslan-B/FFmpeg.AutoGen#186]
Hello, could you please tell me how to convert the RSTP stream directly into a web-playable MP4 instead of the original H264? Can you give me an example? I only found the decoder of the original H264 stream in the program

**Comment by Ruslan-B** [comment]
Off topic here - as this kind of questions end up  never being addressed.
You can try search though history - you might find some pointers: 
https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/164#issuecomment-976406634

**Comment by 183demao** [comment]
Thanks
