### ISSUE TITLE
New fork with some modifications

### ISSUE THREAD

**Issue by oysteinkrog** [Ruslan-B/FFmpeg.AutoGen#187]
Hi, 

I forked and modified this nice project, in order to replace our own very old and customized CppSharp-based ffmpeg binding generator. It was still working fine but it was becoming a PITA to use it due to very old dependencies :P
In order to get the same stuff working (in our commercial closed-source application) I had to make some changes:
https://github.com/InitialForce/FFmpeg.AutoGen/commits/master

I am curious if there is any interest in me creating PRs for any of these changes?
Obviously some of it is not relevant (reverted back to normal DllImport etc), but other stuff might be quite relevant:
* Overloads for functions that have double indirection to have one "ref *" version, which is very useful for use with fields.
* Support for GetPinnableReference for use with Span<> for some of the auto-generated array wrapper types
* Implicit ptr* for some of the auto-generated array wrapper types

**Comment by Ruslan-B** [comment]
Hi @oysteinkrog, 
Your works looks awesome, I also like switching back to normal DllImport and I think it would be beneficial to have few nuget versions (or ability to generate custom bindings)- as I already had some complains wrt to package size - string table is huge.
I need to finish this year and do some planning for the next one - with respect to my own company. 
Then I'll get back to your fork in new year and I'll cherry pick changes.
I would love to get some explanations for some of these changes - but I'll form a list first.

**Comment by oysteinkrog** [comment]
@Ruslan-B Yeah, my changes are not that extensive but feel free to reach out when you have time :)
