### ISSUE TITLE
Wrong dll attribute ~

### ISSUE THREAD

**Issue by setimets** [Ruslan-B/FFmpeg.AutoGen#19]
It causes an exception error when I use any of swresample-1.dll functions.
so I've changed FFmpegInvoke.cs file.
like this :

public const string SWRESAMPLE_LIBRARY = "swresample-1";
,,,,
[DllImport(SWRESAMPLE_LIBRARY, EntryPoint = "swr_alloc_set_opts", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]

Sorry for my lack of english.

**Comment by Ruslan-B** [comment]
@setimets thanks for finding, could you please check same on the experimental branch it suppose to work there, as I'm going to discard version on master completely.

**Comment by setimets** [comment]
Thanks for your the experimental branch ! :+1: It works very well ~
The experimental branch makes me amusing ! thanks ~

**Comment by Ruslan-B** [comment]
good, I'll promote it to main at the end of this week. #closing #19
