### ISSUE TITLE
Use hardware acceleration when running example always crash

### ISSUE THREAD

**Issue by ChengYen-Tang** [Ruslan-B/FFmpeg.AutoGen#190]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
* System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
Run example and pull rtsp stream

* **What is the expected behavior?**
Use hardware acceleration to decode rtsp stream.

* **What is the motivation / use case for changing the behavior?**
If not use hardware acceleration decode, it run very well.
But use any hardware acceleration，always crash in the `FFmpeg.AutoGen/FFmpeg.functions.export.g.cs/line:13941`
`return av_hwdevice_ctx_create_fptr(@device_ctx, @type, @device, @opts, @flags);`
![image](https://user-images.githubusercontent.com/32535494/146705799-054a6d71-8e3c-476b-8890-908c4d0951c2.png)

* **Please tell us about your environment:**

- version: 4.4
- Visual studio 2022
- Windows 10
- Windows 11

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by hglee** [comment]
> I have a video with a similar resolution, this video will also cause the program to crash. [https://ionetworktw-my.sharepoint.com/✌️/g/personal/kenneth_ntut_tk/EZwhs8DQpmpDl4nQU4-OSxgBtgREtDb0H28CsY_AVq_7lA?e=a6PNxP](https://ionetworktw-my.sharepoint.com/:v:/g/personal/kenneth_ntut_tk/EZwhs8DQpmpDl4nQU4-OSxgBtgREtDb0H28CsY_AVq_7lA?e=a6PNxP)
> 
> Thank you.

That file was AV_CODEC_ID_MPEG4 and only compatible with CUDA in my PC, not DXVA or D3D11.

You need to check codec compatibility with HW accel. You can check like this.

https://github.com/unosquare/ffmediaelement/blob/a2e414692b06579d791d66f969cf2c1415bf8a0f/Unosquare.FFME/Container/HardwareAccelerator.cs#L59


Anyway I got error on CUDA init with that file, may be width limited to 2032. 

Error log on init:

```
[mpeg4 @ 00000250c32f33c0] Format cuda chosen by get_format(). 
[mpeg4 @ 00000250c32f33c0] Format cuda requires hwaccel initialisation. 
[AVHWFramesContext @ 00000250c32f07c0] CUDA texture alignment: 512 
[AVHWFramesContext @ 00000250c32f0b40] CUDA texture alignment: 512 
[mpeg4 @ 00000250c32f33c0] Loaded lib: nvcuvid.dll 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidGetDecoderCaps 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidCreateDecoder 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidDestroyDecoder 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidDecodePicture 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidGetDecodeStatus 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidReconfigureDecoder 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidMapVideoFrame64 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidUnmapVideoFrame64 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidCtxLockCreate 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidCtxLockDestroy 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidCtxLock 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidCtxUnlock 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidCreateVideoSource 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidCreateVideoSourceW 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidDestroyVideoSource 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidSetVideoSourceState 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidGetVideoSourceState 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidGetSourceVideoFormat 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidGetSourceAudioFormat 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidCreateVideoParser 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidParseVideoData 
[mpeg4 @ 00000250c32f33c0] Loaded sym: cuvidDestroyVideoParser 
[mpeg4 @ 00000250c32f33c0] NVDEC capabilities: 
[mpeg4 @ 00000250c32f33c0] format supported: yes, max_mb_count: 8192 
[mpeg4 @ 00000250c32f33c0] min_width: 48, max_width: 2032 
[mpeg4 @ 00000250c32f33c0] min_height: 16, max_height: 2032 
[mpeg4 @ 00000250c32f33c0] Video width 2560 not within range from 48 to 2032 
[mpeg4 @ 00000250c32f33c0] Failed setup for format cuda: hwaccel initialisation returned error. 
[mpeg4 @ 00000250c32f33c0] Format cuda not usable, retrying get_format() without it. 

```

**Comment by Ruslan-B** [comment]
Closing issue as not related to this project.

**Comment by ChengYen-Tang** [comment]
@hglee, Thank you for the information.
@Ruslan-B, But FFmpeg can decode 4K videos using CUDA.
