### ISSUE TITLE
Is this example code in H264VideoStreamEncoder.cs correct?

### ISSUE THREAD

**Issue by Camel-RD** [Ruslan-B/FFmpeg.AutoGen#191]
H264VideoStreamEncoder.cs method Encode(AVFrame frame) contains this code:

>                 
	do
	{
		ffmpeg.avcodec_send_frame(_pCodecContext, &frame).ThrowExceptionIfError();
		ffmpeg.av_packet_unref(pPacket);
		error = ffmpeg.avcodec_receive_packet(_pCodecContext, pPacket);
	} while (error == ffmpeg.AVERROR(ffmpeg.EAGAIN));

When ffmpeg.avcodec_receive_packet returns EAGAIN it repeats call to avcodec_send_frame. Is this the correct way to do frame encoding? According to FFmpeg documentation when avcodec_receive_packet returns EAGAIN you should call avcodec_send_frame with next frame.

**Comment by Ruslan-B** [comment]
It used to be correct hoverer nothing stands still with FFmpeg . Do you have any problems?

**Comment by Camel-RD** [comment]
I would like to say, this project is incredible (compared to the likes of FFmpeg.Core) for someone who is ready to study ffmpeg documentation and sources. But lazy c# coders like me for starters are searching for working examples and recipes. For now i could make small application for encoding to mp4 with nvenc. But, for example, i dont know how to write matroska file.

Here is how i changed that code fragment from example:

```
public void Encode(AVFrame frame)
{
	if (frame.format != (int)_pCodecContext->pix_fmt)
		throw new ArgumentException("Invalid pixel format.", nameof(frame));
	if (frame.width != _frameSize.Width) throw new ArgumentException("Invalid width.", nameof(frame));
	if (frame.height != _frameSize.Height) throw new ArgumentException("Invalid height.", nameof(frame));

	var pPacket = ffmpeg.av_packet_alloc();

	try
	{
		int error;
		ffmpeg.avcodec_send_frame(_pCodecContext, &frame).ThrowExceptionIfError();

		do
		{
			error = ffmpeg.avcodec_receive_packet(_pCodecContext, pPacket);
			
			if(error == ffmpeg.AVERROR(ffmpeg.EAGAIN))
			{
				ffmpeg.av_packet_free(&pPacket);
				return;
			}

			error.ThrowExceptionIfError();

			using var packetStream = new UnmanagedMemoryStream(pPacket->data, pPacket->size);
			packetStream.CopyTo(_stream);

			ffmpeg.av_packet_unref(pPacket);

		} while (error >= 0);
	}
	finally
	{
		ffmpeg.av_packet_free(&pPacket);
	}
}
```

**Comment by Ruslan-B** [comment]
Can you check this one https://gist.github.com/Ruslan-B/43d3a4219f39b99f0c9685290dcd23cc

**Comment by Camel-RD** [comment]
Its about usefulness and ease of access. When you have many examples for various functionality with nice readme files (for web searching) or maybe some sort of higher level api, it saves a lot of time spent on searching, reading and testing.

**Comment by Ruslan-B** [comment]
@Camel-RD you up to participate - that is how open source works.
