### ISSUE TITLE
Upgrade to ffmpeg 5.0?

### ISSUE THREAD

**Issue by sdcb** [Ruslan-B/FFmpeg.AutoGen#192]
FFmpeg 5.0 was released today:
https://github.com/FFmpeg/FFmpeg/blob/ce4d459db186a7d8ac842685cd6256c9ac1b7f25/Changelog

windows download link: https://github.com/BtbN/FFmpeg-Builds/releases

**Comment by Ruslan-B** [comment]
@NurulloSulaymonov it won't work obviously  :) - in the current nuget bindings are for 4.x .
I'll try to generate new API today.

**Comment by Ruslan-B** [comment]
Done. The nuget package: https://www.nuget.org/packages/FFmpeg.AutoGen/5.0.0

**Comment by NurulloSulaymonov** [comment]
Thanks Ruslan-B
Again a different error
```
Field not found: 'FFmpeg.AutoGen.AVStream.codec'. 

   at FFMediaToolkit.Encoding.Internal.OutputStreamFactory.CreateVideo(OutputContainer container, VideoEncoderSettings config)
   at FFMediaToolkit.Encoding.Internal.OutputContainer.AddVideoStream(VideoEncoderSettings config)
   at FFMediaToolkit.Encoding.MediaBuilder.WithVideo(VideoEncoderSettings settings)
   at TerminalCameraService.Models.Camera.OutputFile(String filename) in C:\Users\admin\Documents\TermCameraService\TerminalCameraService\Models\Camera.cs:line 248
```
![image](https://user-images.githubusercontent.com/48081398/150466080-b36c2a74-2eac-49ff-b181-ced7f09369f6.png)

I think FFMediaToolkit nuget package should be also updated.
Thanks

**Comment by Ruslan-B** [comment]
It is major update so FFmpeg API has some breaking changes. However, it has nothing todo with bindings.

**Comment by Norc89** [comment]
I have try today with AutoGen 5.0 and i get Unable to load DLL 'avutil.57' error. 

If i leave with 4.4 then i get "Unable to load DLL 'avutil.56' error".

**Comment by Ruslan-B** [comment]
Means you are mixing 5.x and 4.x binaries - don't see this an issue but I would recommend to stay away from 5.0 release as I got few instable issues which are connected to bugs in the native code most-likely.

**Comment by Norc89** [comment]
Hi,
I have try with 4.4 version and dlls for 4.4 and also with 5.0 version and dlls for 5.0.

I have the same problem as is mentioned here. 
https://github.com/radek-k/FFMediaToolkit/issues/100

I have try in wpf application and there is FFMediaToolkit working. After nuget instalation only FFMediaToolkit is added.

If i added FFMediaToolkit  in nuget for  .net framework 4.7.2 then also AutoGen packages. And here i get "Unable to load DLL 'avutil.56' error "

**Comment by Ruslan-B** [comment]
That is right you have to use FFmpeg binaries from 4.x build as https://github.com/radek-k/FFMediaToolkit/issues/100 is still open.
