### ISSUE TITLE
C#, Multiple instance of FFmpeg.AutoGen.ffmpeg

### ISSUE THREAD

**Issue by FPGA-KING** [Ruslan-B/FFmpeg.AutoGen#195]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [ ] feature request
  - [X] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

As you already know, FFmpeg.AutoGen.ffmpeg is `static class`
 It can't has multiple FFmpeg.AutoGen.ffmpeg instances.
This means, alreday you predicted, that It can't play multiple
video streams at all.

Yes. I searched known issues. https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/184#issuecomment-971358920
Says that "**FFmpeg recommends do multi-process scaling - not multi-threading**". However, have you any idea to **scaling it as `multi-process` in "C#" ?** 

How could I resolve the issue?
Process.Start Method (System.Diagnostics) ?
**no. This is for running external program, not for running internal function of C# code.**

Rather, I think it would be better to state that this project can only play '1 video' at the same time. 
 
Anyway, My plan is below
Remove FFmpeg.AutoGen at all.
Build FFmpeg and wrapper in C++

**Can you please let me know if there is a better way I can use this program without uninstalling it?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- version: 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
FFmpeg has static API thus all API in C# is also static, however you has to be aware that .NET has GC in place.
However when GC pauses .NET Runtime - managed thread it does impact native treads.
If implemented right you can use managed thread but you have to used pinned or fixed structures when they are in C# memory.

**Comment by FPGA-KING** [comment]
Thanks. Have a good day, bro.
