### ISSUE TITLE
Wrong libavdevice for av_opt_* av_opt_* functions are located under libavutil

### ISSUE THREAD

**Issue by mariodivece** [Ruslan-B/FFmpeg.AutoGen#20]
For some reason, a large amount of methods (specifically those with the prefix av_set, av_opt, etc. have their library set to libavdevice when they should really reference libavutils

**Comment by Ruslan-B** [comment]
@mariodivece did you check experimental? As I'm about to merge them.

**Comment by mariodivece** [comment]
Yes it was on experimental only. It worked ok on master.

Please forgive the brevity and typos. Sent from a mobile device.
________________________________

**Comment by Ruslan-B** [comment]
@mariodivece thank you, I'll double check on that - it should be easy to fix.

**Comment by Ruslan-B** [comment]
fixed and promoted to master
