### ISSUE TITLE
[Question] FFmpeg v4 and v5 in the same package library?

### ISSUE THREAD

**Issue by SuRGeoNix** [Ruslan-B/FFmpeg.AutoGen#200]
Hey @Ruslan-B, long time no speak. Hope you doing well!

I'm planning to support ffmpeg v5 but at the same time I want to keep mainly support for v4. I was just wondering if you have any idea including both of them in a single package with conditions.

Thanks in advance,
John

**Comment by SuRGeoNix** [comment]
No worries. I guess having v4 autogen and the user can update to v5. Compilation will not fail so all good. I just need to create some interfaces for few custom private classes that I use.

**Comment by Ruslan-B** [comment]
Hi @SuRGeoNix yes indeed it is complicated, besides, I have users concerned as for assembly size.
I would say it would be complete fork off if you happens to have both API in place in one process. 
However, there is an elaborative and complex way - create two or an additional application domain which can load same assembly with the different version.

**Comment by SuRGeoNix** [comment]
Just an update for anyone who might interested. The only issue that my implementation had was with AVPixelFormat constants that changed (2 new added after 43 which pushed all the others to +2). So I had to convert those (only above 43) to int and based on the running version to substract 2 if required. eg:-

```csharp
static int AV_PIX_FMT_YUV420P10LE;
static int AV_PIX_FMT_P010LE;
static int AV_PIX_FMT_P010BE;

AV_PIX_FMT_P010LE = (int)AVPixelFormat.AV_PIX_FMT_P010LE;
AV_PIX_FMT_P010BE = (int)AVPixelFormat.AV_PIX_FMT_P010BE;
AV_PIX_FMT_YUV420P10LE = (int)AVPixelFormat.AV_PIX_FMT_YUV420P10LE;

if (Engine.FFmpeg.IsVer5)
{
	AV_PIX_FMT_P010LE -= 2;
	AV_PIX_FMT_P010BE -= 2;
	AV_PIX_FMT_YUV420P10LE -= 2;
}
```

**Comment by Ruslan-B** [comment]
Well, not only you might need to check this commit: https://github.com/Ruslan-B/FFmpeg.AutoGen/commit/2b1af3ab23bc31a4e4dc4ce6e2985b9024d52d2f

**Comment by SuRGeoNix** [comment]
You are right, at least AVCodecID affects me as well. I thought it would be easier :(

**Comment by Ruslan-B** [comment]
Not sure what are you trying to achieve and why do you need two versions of FFmpeg - heard stability of 5.x is questionable topic atm. But in going to be pain in neck in any possible way to keep them running simultaneously.

**Comment by SuRGeoNix** [comment]
I've left FFmpeg.Autogen 4.4.1.1 package in my library but I prepare it to be able to handle FFmpeg.Autogen 5.0.0 package if the user install on his application. This way I can support ffmpeg 5 with few changes at my code and without the need of creating different packages with different dependencies of FFmpeg.Autogen or even if was possible both versions of FFmpeg.Autogen in a single package which would create more size.

I've compiled the ffmpeg's master yday and from my testing it felt better with performance and no issues so far.
