### ISSUE TITLE
ffmpeg 5.1 bindings

### ISSUE THREAD

**Issue by iamcarbon** [Ruslan-B/FFmpeg.AutoGen#208]
ffmpeg 5.1 was released on July 22nd. As usual, updated bindings are always appreciated.

https://ffmpeg.org/index.html#news

**Comment by Ruslan-B** [comment]
On it!

**Comment by Ruslan-B** [comment]
I think it will take a bit of time as seems upgrading to Windows 11 and VS2022 again brought instability with no expiation. After I solve it I am going to build full CI/CD pipeline and start to look for replacement for CppSharp as it feels like it dying project - maybe I wrong - I'll reach Autor first. As I already made a lot of hacks to make it work and that is not a good idea for a long run.

**Comment by Ruslan-B** [comment]
@iamcarbon which version of runtime you are using? As I think I have discard legacy tail in targets - it definitely will simplify support. As even NET 5.0 is not supported. 
And I have even older versions: netstandard2.1;netstandard2.0;net472;net45;net40.

**Comment by iamcarbon** [comment]
We’re on .NET 6.0. 

I would strongly consider dropping all legacy targets and only targeting net6.0 for maintainability.

**Comment by Ruslan-B** [comment]
Okay got it - as it seems to be directions - and I should push others.
@iamcarbon **last question platforms you use?**
and update on the progress - it is quite finicky as I didn't expect that many changes between 5.0 and 5.1.
As FFmpeg team introduced new type conversions which are looking as bug - long double - I had extended discussion with some folks which lead to nowhere as we have to go from headers to implementation (but that we can ignore and wait till some one going to file another bug - but am checking that) 
So this was the first guy:
```
typedef union
{   // pun floating type as integer array
    unsigned short _Sh[4];
    long double _Val;
} _ldouble_val
```
New macroses came as well looking now - as I have to recall what I did 5 years back then in the parsing part.
I'll link PR as soon I have by pass solution. I have to admit CppSharp hadn't had a lot of updates recently and having a chat with the author wise thing - as I need 2017, 2019 and 2022 VS to run generation on my pc and I am scratching a had - I could probably revert all project structures to 2017 - thank you - no go - keep you posted.
**Most important one in bold on the top.**
The rest just emotional.)

**Comment by Ruslan-B** [comment]
Like I said need to figure out the mess with new update to 5.1 as seems errors accumulated to the critical level  :)

**Comment by Ruslan-B** [comment]
To keep updated - I'll publish new package today or tomorrow.

**Comment by Ruslan-B** [comment]
I listed updated package.
