### ISSUE TITLE
generate partial structs to allow struct decoration

### ISSUE THREAD

**Issue by vpenades** [Ruslan-B/FFmpeg.AutoGen#209]
* **I'm submitting a ... **
  - [ ] bug report
  - [X] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

I am trying to do some stuff with the library, and using AVRational struct quite often. I'ts a bit painful not having any support, and having to look into the struct every time I need to see the values (it happens the same with other structures)

Decorating existing structures and classes is not trivial because the code is autogenerated.

So my feature request is to change the code generator so all structs and classes are generated as `partial`, like this:

```c#
public unsafe partial struct AVRational
    {
        /// <summary>Numerator</summary>
        public int @num;
        /// <summary>Denominator</summary>
        public int @den;
    }
```

That way, a future pull request could introduce a non generated partial in another file like this:

```c#
[System.Diagnostics.DebuggerDisplay("{num} / {den}")]
public unsafe partial struct AVRational { }
```

I think changes like these will make the library easier to use.

**Comment by Ruslan-B** [comment]
Nice idea, I'll test the stability and most probably do it in 5.1.

**Comment by vpenades** [comment]
I think that with partials, it could be possible to introduce attributes, properties and even methods manually programmed, which would make the library much easier to use.

**Comment by digivod** [comment]
Another option is to make it a "record struct" instead of plain struct. The compiler then generates some nice default ToString representation. And CLR-wise it's still a plain struct. 
The partial thing does not allow you to "extend" a class in another assembly. So it doesn't help for a Nuget-distributed vanilla FFmpeg.AutoGen

**Comment by vpenades** [comment]
> The partial thing does not allow you to "extend" a class in another assembly. So it doesn't help for a Nuget-distributed vanilla FFmpeg.AutoGen

I was not thinking about extending in another assembly; it's not only not possible (even less for classes) but it's also dangerous, because these structs are usually used to interop with the native code, which requires the structures to match fields.

My idea of extending these structures was to do so in your own library. An obvious example is the ToString() method, but also useful methods that are not autogenerated. Using again the AVRational, it could be possible to add a constructor that takes a float and calculates the rational value.

**Comment by Ruslan-B** [comment]
Folks it is no problem to make all partial - but with the freedom - responsibility came - even now extension methods are available - but you easy can shoot your leg as this are structures of defined size and  it is aligned structures and part of the data beyond GC control.

**Comment by Ruslan-B** [comment]
Means I have to add a disclaimer - you can do wat you like but it started to be more challenging than it was - however, partial works only in compiler mode so we good here :)

**Comment by Ruslan-B** [comment]
I just realized :) - this never work - partial is compile time feature - so your partial definitions has to be included within the same project means you have to do a custom build of FFmpeg.AutoGen with yours extra partials in.

**Comment by vpenades** [comment]
@Ruslan-B you misunderstood my feature request. Of course it is required that the additional code to be included in your project... _as pull request to your repository_

So let's say you make the classes partial;  the very first thing I would do next, with your pemission, would be to add a new file, containing this line of code:

```c#
[System.Diagnostics.DebuggerDisplay("{num} / {den}")]
public unsafe partial struct AVRational { }
```

In other words, it would let other developers to constribute to your repository with pull requests, to make the library easier to use, _without conflicting with the geneated code_

**Comment by Ruslan-B** [comment]
Now I got it - me stupid 🤣. I'll do #197 quickly and then get back to this issue.  I quite convince I'll do everything today.

**Comment by Ruslan-B** [comment]
Okay. Now all is partial - except arrays but for arrays it is better to generate extras if any needed
