### ISSUE TITLE
Update to 2.8.3

### ISSUE THREAD

**Issue by Ruslan-B** [Ruslan-B/FFmpeg.AutoGen#21]

**Comment by catester** [comment]
Hi Ruslan,
Thanks for your efforts for the new generation method, I have not tested it yet but it looks more clean and flexible. I hope this change will allow instant synchronization with ffmpeg releases. For example, I just checked and they have already released v2.8.3 so I think you should change the title already and just skip v2.8.2 :)
![ffmpeg-feynman](https://cloud.githubusercontent.com/assets/3868141/11461391/0a192ac4-970b-11e5-9162-d43fed1305fe.png)

**Comment by Ruslan-B** [comment]
Hi @catester,
Sine I replaced generator, update shouldn't take a lot of time.
I can update to 2.8.2 almost at no time but not to 2.8.3 as main source of binaries and headers is http://ffmpeg.zeranoe.com and they don't have 2.8.3 yet.  
If I'll miss the update myself :) just create an issue here but first it should be available at ffmpeg.zeranoe.com.

**Comment by Ruslan-B** [comment]
![image](https://cloud.githubusercontent.com/assets/3823565/11471289/885a76c8-9764-11e5-84aa-064fb3e207fe.png)

**Comment by catester** [comment]
Yeah, you are right, I forgot you were using the builds from zeranoe. For your information, I build ffmpeg easily with this awesome script cross_compile_ffmpeg.sh (from https://github.com/rdp/ffmpeg-windows-build-helpers). It's fully automatic, i.e. it downloads everything and prepares build environment. I just run it on an Ubuntu virtual machine.

**Comment by Ruslan-B** [comment]
Well it is good to know and I'll keep eye on it, meanwhile try to concentrate on c macro support - as after preprocessing of c/c++ will be completely resolved we have nothing to do here :).

**Comment by Ruslan-B** [comment]
Ok 2.8.3 is available, I'll update it tomorrow.

**Comment by Ruslan-B** [comment]
done
