### ISSUE TITLE
change the inputs for ffmpeg

### ISSUE THREAD

**Issue by pottabathini** [Ruslan-B/FFmpeg.AutoGen#22]
I thank you for your great effort to create very useful plugin. the example you given is generating 100 frames but those are continuous.

I want something like where it generates random meaningful thumbnails, I am little confuse where the code written for giving input to ffmpeg command.

I want to use commands like:
https://trac.ffmpeg.org/wiki/Create%20a%20thumbnail%20image%20every%20X%20seconds%20of%20the%20video

Can you please refer stackoverflow answer here: 
http://superuser.com/questions/538112/meaningful-thumbnails-for-a-video-using-ffmpeg

if you provide example for that, that would be great help for me.

Thank you :-)

**Comment by Ruslan-B** [comment]
Lol what? Please define meaningful. You looking for option "output meaningful thumbnail = true" or what?
I'm wonder how this project connected the question. =)

**Comment by pottabathini** [comment]
I am sorry, may be I given minimal explanation of my requirement. Let me put in other words

<b>FFmpeg.AutoGen.Example</b> in this project on <b>Program.cs</b> class you written code to generate <b>100</b> frames of images from a video(while loop). if I run that program it is giving 100 images which are in sequence like from video start to 100 frames.

I have a requirement like to generate <b>10 images(thumbnails/ frames)</b> from video, those should cover my complete video.

If I use your code to generate <b>10 Frames (thumbnails)</b> I am ended up with very frist 10 frames/thumbnails. 

So I want to extend your logic where it should give 10 images(thumbnails/frames) from the video which should cover my hole(full) video.

I tried but I am not much aware of c# pointers and linked lists so I want you to give a direction/ solution to extend your logic to get 10 frames which covers hole video.

I put some links on top because I wanted to tell you like we can achieve same using command line arguments of ffmpeg.

Thank you.

**Comment by Ruslan-B** [comment]
I see no problem here, but the only way I know requires two stage processing.
During the first step you need to count amount of video frames ffmpeg.av_read_frame, obviously you should omit any decoding or/and converting.
And on the second step you need to read frames then decode them, you can skip conversion step for none lucky 10.
Moreover, optimization, but depending from the format - you actually can recall closest reference or base frame and decode only them or starting from them.
I guess you have pretty much everything in example project. Good luck.
