### ISSUE TITLE
Expose Bitstream Filter functionality

### ISSUE THREAD

**Issue by tobyspark** [Ruslan-B/FFmpeg.AutoGen#222]
Feature request – expose [Bitstream Filter](https://ffmpeg.org/ffmpeg-bitstream-filters.html) functionality, e.g. [bsf.c](https://ffmpeg.org/doxygen/trunk/bsf_8c_source.html). This allows modification of AVPackets, to e.g. set H264 metadata.

ps. This is a heroic project. Thanks for all the work that must have gone into it.

pps. If I have missed something, or you can give me some hints on what I’d need to do to enable this myself as a contribution, please let me know.

**Comment by Ruslan-B** [comment]
Thank you. It will be a part of new API witch will break thing or two  https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/217
Need a time to finalize. Will push new update in few days.
With respect to contribution PR's are welcome  it easy to setup VS 2022  but I am conservative to accept them as there are reasons.
This repo and package is bare bone - C to C#.

**Comment by Ruslan-B** [comment]
Could you please specify what types you are missing now as I started to look and seems everything is included starting from 4.4 I think.

**Comment by Ruslan-B** [comment]
If it is bsf_internal.h - then it is not a part official API.

**Comment by tobyspark** [comment]
I don’t _think_ it’s private, as [bsf.h](https://ffmpeg.org/doxygen/trunk/bsf_8h.html) doesn’t have “internal” or “avpriv” or any of the other markers I’ve seen.

That said, a) generally I find the FFmpeg codebase and how to use it quite confusing so _shrug_ and b) I no longer need this, in no small part because I’ve realised some of the metadata I wanted to set was already there, just most PC browsers seem to ignore it.

I’ll close this now as I suspect both of us have more important things to do, and anyone who was in my position will at least find this issue. Thank you again for your efforts.

**Comment by Ruslan-B** [comment]
@tobyspark submit bug to FFmpeg then. Right now you can port some structs by hand or generate private version of this repo with extras includes.
