### ISSUE TITLE
Could you please add more version tags?

### ISSUE THREAD

**Issue by c72578** [Ruslan-B/FFmpeg.AutoGen#223]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
A *feature* concerning the GitHub repo

* **What is the current behavior?**
Only a few version tags are shown under https://github.com/Ruslan-B/FFmpeg.AutoGen/tags
```
4.3.0.3
4.1.0.4
3.2
3.0
2.8.3
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

* **What is the expected behavior?**
Show more tags here, ideally the same ones as in the NuGet Gallery:
https://www.nuget.org/packages/FFmpeg.AutoGen/#versions-body-tab
```
5.1.1
5.1.0
5.0.0
4.4.1.1
4.4.1
4.4.0
4.3.2.1
4.3.2
4.3.1
4.3.0.3
4.3.0.2
4.3.0.1
4.3.0
4.2.2.2
4.2.2.1
4.2.2
4.2.0
4.1.0.5
4.1.0.4
...
```

* **What is the motivation / use case for changing the behavior?**
The motivation is to have a tag, in order to point to or download releases of FFmpeg.AutoGen from the https://github.com/Ruslan-B/ repo.

* **Please tell us about your environment:**
Windows
- version: 10

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
NA

**Comment by Ruslan-B** [comment]
Please elaborate more why do you need more tags - as I am not releasing any binaries here as it contradicts GPL license. I do realize why need some tags now as I like to create new API packages starting from 4.3. Besides, last digit (position 4) in version means only bug fix or minor improvement in package.

**Comment by c72578** [comment]
Thanks for your reply.
Here is some additional information concerning usage of tags and releases of FFmpeg.AutoGen.
- The last release of FFmpeg.AutoGen here in the git repo is `4.3.0.3` and this currently is also the latest tag.
Release: https://github.com/Ruslan-B/FFmpeg.AutoGen/releases/tag/4.3.0.3
Tag: https://github.com/Ruslan-B/FFmpeg.AutoGen/releases/tag/4.3.0.3
From the tag it is straight forward to identify the commit, which is `typo fix` in this case:
https://github.com/Ruslan-B/FFmpeg.AutoGen/commit/e0d26f8a24e36b6cec25c703336eddb38a6d017e
- As of today (2022-09-18) the latest release of the FFmpeg.AutoGen NuGet package is 5.1.1
https://www.nuget.org/packages/FFmpeg.AutoGen/5.1.1
It is slightly more elaborate to identify the commit for 5.1.1. However, by clicking at README there, the commit message is shown: `Use ICustomMarshaler for missing UnmanagedType.LPUTF8Str in .NET Standard 2.0 or lower`
So, from the commit message, the associated commit can be identified, which is:
https://github.com/Ruslan-B/FFmpeg.AutoGen/commit/44f6558b9b947a6e8d17e41d47bbbb334c0f7582
Having the the tag for 5.1.1 also here in the git repo would simplify identification of the associated commit.

**Comment by Ruslan-B** [comment]
I'll add some tags as I'am going to release newly generated API (legacy and abstract) for 4.3, 4.4, 5.0 and 5.1. And I'll maintain tags from this point.

**Comment by Ruslan-B** [comment]
I started to do so for new packages. I'll publish tagged 4.3 and 4.4 packages as well.

**Comment by c72578** [comment]
Thanks
