### ISSUE TITLE
Latest commit inverts Path.Combine and GetNativeLibraryName calls

### ISSUE THREAD

**Issue by exelix11** [Ruslan-B/FFmpeg.AutoGen#229]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
This was introduced in the latest commit: 
https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/534a3eb0ff295bc9bc8382b311df407180ab5051/FFmpeg.AutoGen/FunctionResolverBase.cs#L74-L76
On linux GetNativeLibraryName prepend `lib` to the full path but it should be added only to the library name

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
N/A. Did not test, just noticed this while reading the code to debug a related issue before realizing i was on an older version from nuget, still worth reporting this.

* **What is the expected behavior?**
The previous implementation was correct
https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/4cba8b60af9bb8b4c51ac9eceea0c66127555b69/FFmpeg.AutoGen/Native/LibraryLoader.cs#L66-L68

**Comment by Ruslan-B** [comment]
Fixed in v5.1.2
