### ISSUE TITLE
avio_alloc_context method signature and also uint8_t type

### ISSUE THREAD

**Issue by catester** [Ruslan-B/FFmpeg.AutoGen#23]
Thanks for the 2.8.3 update (it also works with 2.8.4). I am not sure if it's an error or not but I found that some type conversions are different from the ones you generated before using Clang generation (old FFmpegInvoke).

For example avio_alloc_context function is generated with IntPtr* type for parameters read_packet, write_packet and seek:

```c#
public static extern AVIOContext* avio_alloc_context(
	sbyte* @buffer, 
	int @buffer_size, 
	int @write_flag, 
	void* @opaque, 
	IntPtr* @read_packet, 
	IntPtr* @write_packet, 
	IntPtr* @seek);
```

I changed IntPtr* to IntPtr and it worked ok with my existing code, otherwise it required casting. I did not test if it would work if I did the casting though. The original function signature in the header is 

```c
AVIOContext *avio_alloc_context(
                  unsigned char *buffer,
                  int buffer_size,
                  int write_flag,
                  void *opaque,
                  int (*read_packet)(void *opaque, uint8_t *buf, int buf_size),
                  int (*write_packet)(void *opaque, uint8_t *buf, int buf_size),
                  int64_t (*seek)(void *opaque, int64_t offset, int whence));
```
so I mean IntPtr is already a pointer and IntPtr* seems redundant or wrong in this case?

Also I noticed a change with uint8_t, before Clang it was converted to byte but now to sbyte:

```c#
internal static extern int sws_scale(
	SwsContext* @c, 
	sbyte** @srcSlice, 
	int* @srcStride, 
	int @srcSliceY, 
	int @srcSliceH, 
	sbyte** @dst, 
	int* @dstStride);
```

The original function signature in the header is 

```c
int sws_scale(struct SwsContext *c, const uint8_t *const srcSlice[],
              const int srcStride[], int srcSliceY, int srcSliceH,
              uint8_t *const dst[], const int dstStride[]);
```

Again this also works ok as it is but I think uint8_t is unsigned and sbyte is "signed byte".

Not sure if these would cause problems in future or if they are even considered errors, just documenting differences and letting you know.

**Comment by Ruslan-B** [comment]
HI @catester, I'm not surprised as difference of include files between 2.8.1 and 2.8.3 was really minor, thus we can expect same for 2.8.4.
Thanks for findings. I'll take a look how to deal with IntPtr* as if you have a pointer it is already enough :). 
With respect to byte -> sbyte, it should be a big difference as in bits same size and marshaling does not make any difference. I actually tried to do separation between sbyte and byte but in come cases clang obscure required metadata. I can make everything byte but than we will face cumbersome string marshaling as in .net by some bizarre rezone only sbyte is supported.  
 
I'll keep issue open as a reminder to fix double pointer and recheck byte<->sbyte.

Cheers,
Ruslan

**Comment by catester** [comment]
>  it should (not) be a big difference as in bits same size and marshaling does not make any difference.
 
Ok now this explains it, that's why the function can still work the same with sbyte. Then nevermind, the API (at least the surface I use) already works very good now :)

**Comment by ViToni** [comment]
Regarding `IntPtr*` I found one more function which uses it and maybe shouldn't: `ffmpeg.av_log_set_callback`.

**Comment by ispysoftware** [comment]
also avio_alloc_context intptr* should be IntPtr - amazing project by the way, thanks!

**Comment by Ruslan-B** [comment]
@ViToni thank you. I'll get back after this weekend after update.

**Comment by EchterAgo** [comment]
Also ffmpeg.av_log_set_callback
