### ISSUE TITLE
FFmpeg.AutoGen.CppSharpUnsafeGenerator

### ISSUE THREAD

**Issue by bzmework** [Ruslan-B/FFmpeg.AutoGen#230]
Can you introduce how to use FFmpeg.AutoGen.CppSharpUnsafeGenerator?
I will report an error according to the introduction of CliOptions, for example: fatal: 'errno h' file not found

**Comment by Ruslan-B** [comment]
In case of VS2022 this should be enough:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/3823565/206435149-51c28ef5-7e71-4032-a88d-2f7b33e52a94.png">
<img width="237" alt="image" src="https://user-images.githubusercontent.com/3823565/206435301-3b220487-0f3a-464d-9e29-fbe744ca5523.png">
