### ISSUE TITLE
Do you want to add a push stream demo? 

### ISSUE THREAD

**Issue by chatop2020** [Ruslan-B/FFmpeg.AutoGen#235]
hi, this is a great project, could you please enrich the content of demo
1. Do you want to add a push stream demo? 
2. Compose n pictures into rtmp protocol and flv encapsulation format with fps convention. 
3. Push data to rtmp server in real time? 
4. Beyond that, how to add audio

**Comment by Ruslan-B** [comment]
doesn't original C project does it? You like to contribute I am open.
