### ISSUE TITLE
Muxing exemple ?

### ISSUE THREAD

**Issue by axel588** [Ruslan-B/FFmpeg.AutoGen#237]
Hello,

Is it possible to get an exemple of the muxing exemple : https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/muxing.c
using FFMpeg.Autogen, I translated the code to C# without success.

Thks

**Comment by Ruslan-B** [comment]
https://github.com/stjeong/ffmpeg_autogen_cs
