### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Ruslan-B** [Ruslan-B/FFmpeg.AutoGen#239]

**Comment by 794742233** [comment]
When I have multiple video components inside a window, I find that this causes problems and it runs for a while and reports an error. After debugging, I found that the reason should be that this package is all static classes and cannot open multiple video windows through multiple threads. QAQ

**Comment by Ruslan-B** [comment]
accept it - it is how interop is working in c#, besides FFmpeg API by itself  is fully based on static functions. I don't see any other way - if you do see offer it I am open to suggestions but please validate your thinking.

**Comment by Ruslan-B** [comment]
multiple threads actually you can but some functions are stateful - don't  blame me. FFmpeg philosophy rather process separated - inheritance of *nix system.

**Comment by 794742233** [comment]
> 
Use ReflectDllInjection to be able to use multithreading

**Comment by Ruslan-B** [comment]
We already loading dll's dynamically in the main library - could you explain the problem?

**Comment by 794742233** [comment]
Oh, I made a mistake and forgot to write AVFrame* xxx = ffmpeg.av_frame_alloc(); to the loop and then release it, actually ffmpeg supports multi-threading and it runs fine now.
I'm sorry to have disturbed you.
Forgive me, I have another question about AVIOInterruptCB I want to set the connection timeout and this is my error code.
` 
        private unsafe  static int interrupt_cb(void* c)
        {

            if (ffmpeg.av_gettime() - startime > 40 * 1000 * 1000)
            {
                return ffmpeg.AVERROR_EOF;
            }
            return 0;
        }
        private unsafe void FFmpegStart()
        {
         AVFormatContext* _formatContext = ffmpeg.avformat_alloc_context();
                    AVIOInterruptCB aVIOInterruptCB = new AVIOInterruptCB()
                    {
                       callback = new AVIOInterruptCB_callback(interrupt_cb),
                    }; 
                    _formatContext->interrupt_callback = aVIOInterruptCB;
        ...
        }
`
