### ISSUE TITLE
UnsafeGenerator failing to run due to not locating dependency

### ISSUE THREAD

**Issue by FrostKiwi** [Ruslan-B/FFmpeg.AutoGen#245]
* **I'm submitting a ... **
  - [x] bug report

Trying to generate bindings via `FFmpeg.AutoGen.CppSharpUnsafeGenerator`, but fail to do so due to `Error parsing 'libavutil/avutil.h'` `fatal: 'errno.h' file not found`
```console
Compiler argument: -fms-extensions
Compiler argument: -fms-compatibility
Compiler argument: -fdelayed-template-parsing
Target triple: x86_64-pc-windows-msvc
ignoring nonexistent directory "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt"
ignoring nonexistent directory "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt"
#include "..." search starts here:
#include <...> search starts here:
 C:\Users\<redacted>\source\repos\FFmpeg.AutoGen\FFmpeg\include
 lib\clang\14.0.0\include
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include
 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\atlmfc\include
 C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
 C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um
End of search list.
Error parsing 'libavutil/avutil.h'
C:\Users\<redacted>\source\repos\FFmpeg.AutoGen\FFmpeg\include\libavutil/common.h(33,10): fatal: 'errno.h' file not found
```
## My Setup
Visual Studio 2022, with prerequisites installed as per doc.
![image](https://user-images.githubusercontent.com/60887273/225228024-b6d1deb5-243d-4714-ba24-29d2df9dbb7c.png)
Compiled with plattform set to 64-bit
![image](https://user-images.githubusercontent.com/60887273/225228791-8b3c4dc4-3c7b-4cce-9bd4-acca36e7bf18.png)
Launching the generator via the Debug function in Visual Studio with the following parameters.
![image](https://user-images.githubusercontent.com/60887273/225228317-1862f472-0da7-413b-90c8-4615a8501ce2.png)
(Also tried from within the MSYS2 + MinGW64 environment, since I know the presence and path of those default headers... still the same result.)

What am I doing wrong?

**Comment by Ruslan-B** [comment]
I don't switching target.
Here is my VS2022 installation:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/3823565/225400234-daad8203-8fdf-4bed-8115-82a822a1080d.png">

**Comment by FrostKiwi** [comment]
> I don't switching target. Here is my VS2022 installation: <img alt="image" width="931" src="https://user-images.githubusercontent.com/3823565/225400234-daad8203-8fdf-4bed-8115-82a822a1080d.png">

Did a full repair and made sure I have the same setup as you
![image](https://user-images.githubusercontent.com/60887273/225774727-fbedacf4-518a-4916-a87c-b48eb40e3873.png)

Let's take a step back.
errno.h is part of UCRT. A file search reveals the paths, that were installed by the Windows SDK.
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\errno.h
C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\ucrt\errno.h
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\errno.h
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\km\crt\errno.h
```
In no way does the VS2022 project file in this repo mention any include macros `$(VC_IncludePath);$(WindowsSDK_IncludePath);` or anything else. I guess that those include files are a run-time dependency of `FFmpeg.AutoGen.CppSharpUnsafeGenerator`. So I need to publish the Include path of the Windows SDK in PATH as an environment variable? That is the only logical conclusion I have.

**Comment by FrostKiwi** [comment]
OMG figured it out. Windows is such a trash dev platform.
So, indeed it was the fault of `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0`.
Here is the joke. It was never installed. I even installed and uninstalled it, it still did not remove that path. After manually deleting that path, `C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\` was searched instead and everything worked.

@Ruslan-B could you explain where that search logic comes from? I would like to file a bug report at whatever project is responsible for not having that new style of `\km` search path...

**Comment by Ruslan-B** [comment]
I am afraid it is [CppSharp](https://github.com/mono/CppSharp) quirks. I cannot do much here.
