### ISSUE TITLE
Bitmap save exception 

### ISSUE THREAD

**Issue by wallmat** [Ruslan-B/FFmpeg.AutoGen#25]
If i take your example and let it run for more then 100 frames, using everything as is, I eventually get an exception when trying to save the bitmap. After that happens we start getting the "Could not read frame" exception too. 

Do you have anyway to fix this? Or known ways to work around this.

Side Note:
I changed all the code to be C# safe ( the end goal is to use this in unity3d) and i get the same issue in mine.

**Comment by Ruslan-B** [comment]
Pardon? Original example is working

Cheers,
Ruslan

**Comment by wallmat** [comment]
Did you change the while loop? if you set it to just true for example and
let it run for a while eventually i get those errors.

But I looked more into this today and the most likely cause is writing to
the same file over and over. If i instead write to a new bitmap each time
bitmap_[fameNumber] this issue never comes up.

On Mon, Apr 25, 2016 at 3:37 PM, Ruslan Balanukhin <notifications@github.com
> wrote:

> Pardon? Original example is working
>
> Cheers,
> Ruslan
>

**Comment by Ruslan-B** [comment]
Looks like you found solution :). I'm closing issue then.

**Comment by wallmat** [comment]
I did have one last question if you have time. do you know why the project
wouldn't work in Release mode? the dll path seems correct but it never
finds them.

On Tue, Apr 26, 2016 at 8:14 AM, Ruslan Balanukhin <notifications@github.com

**Comment by Ruslan-B** [comment]
Example project was disabled.
I've pushed updated solution configuration:
https://github.com/Ruslan-B/FFmpeg.AutoGen/commit/c944086bfac4ab7c97aef238e2a4799747f55a49

**Comment by Ruslan-B** [comment]
And with respect to exception you got - 99% you open frame.buffer.jpg in different application and it did locked this file.
