### ISSUE TITLE
[Question] which ffmpeg version this binding lib based on currently?

### ISSUE THREAD

**Issue by jcyuan** [Ruslan-B/FFmpeg.AutoGen#256]
the `libcodec`, i'm using 58 version, and i found that the media info fetched from the `formatContext` / `stream` are all wrong, and if i use `av_dump_format` to print info with my current `formatContext` / `stream` i just got the correct info.
i don't know why, maybe something related to the binding version matching?

![SRE1V)0({KQ%2VRZOJTYEW](https://user-images.githubusercontent.com/850854/227776430-3a1636f6-ef03-418c-99c7-0d108157bbc3.png)
wrong

![929QZ8(C _QHC`H{_9N2UJJ](https://user-images.githubusercontent.com/850854/227776450-f45d0df1-4c42-4cde-a4cb-1096e19bd1af.png)
correct

**Comment by Ruslan-B** [comment]
could you please describe your quest? :) as issue being open and closed must be trivial thing

**Comment by jcyuan** [comment]
> could you please describe your quest? :) as issue being open and closed must be trivial thing

I'm sorry 😅😅😅 because my problem was solved, yes that happened because of a mismatching on binding and native libs. i was using v59 binding & v58 libs and i got the wrong results. now I'm using both v60 libs which solved my problem. 👍. thanks.
