### ISSUE TITLE
[Question] `AVIOInterruptCB_callback_func` how to use this?

### ISSUE THREAD

**Issue by jcyuan** [Ruslan-B/FFmpeg.AutoGen#257]
![image](https://user-images.githubusercontent.com/850854/228319584-d744af46-4f88-4f44-96ee-19c92e4aa1d1.png)
i'm not sure what should i provide for this field.... ain't that a method stub?

the type of this `callback` is actually a struct!.... so how can i bind a callback method to it?
![image](https://user-images.githubusercontent.com/850854/228319791-129727ac-5cc7-4e77-93db-f1d9b3938f49.png)
not sure what is that `Pointer`, and that `operator`....

thanks.

**Comment by zgabi** [comment]
```
_interruptFunc = new AVIOInterruptCB_callback(Interrupt);
                cf->interrupt_callback.callback = _interruptFunc;

        private int Interrupt(void* opaque)
        {
            return 0 or 1;
        }
```

**Comment by zgabi** [comment]
I'm saving the timestamp before every `av_read_frame` call:

```
                    _lastTick = Stopwatch.GetTimestamp();
                    int readResult = av_read_frame(cf, pkt);
                    _lastTick = long.MaxValue;

```
And in the interrupt function:

```
        private int Interrupt(void* opaque)
        {
            if (Stopwatch.GetTimestamp() - _timeoutTicks > _lastTick)
            {
                return 1;
            }

            return 0;
        }
```

It works for me... it is in our production code.

**Comment by jcyuan** [comment]
> 

erh, tested, with both your code and my code the callback won't be triggered in 3secs..... not sure why.
thank you very much.
i think i'd inspect why this happens, because i found that if i add breakpoint in the thread logic (maybe this slows down the process) and this way it won't hang there when the app trying to exit.
