### ISSUE TITLE
Restore LoadedLibraries Property?

### ISSUE THREAD

**Issue by SuRGeoNix** [Ruslan-B/FFmpeg.AutoGen#259]
I think after v5.1.2 the _loadedLibraries (function resolver) became private. I don't think we have another way to check which libraries actually have been loaded. Maybe you should restore this to public? I could do avfilter_version() for example in try catch but it would be better having list with the successfully loaded libraries.

**Comment by Ruslan-B** [comment]
The loading is progressive. If like to probe I think most logical would be call ```FunctionResolverBase.GetOrLoadLibrary(libraryName, false)``` and check if it is null or not.
What do you think?

**Comment by SuRGeoNix** [comment]
Ow, didn't realize that, I thought it was during RootPath. Yes, that's fine then!
