### ISSUE TITLE
av_parser_parse2

### ISSUE THREAD

**Issue by pokernet** [Ruslan-B/FFmpeg.AutoGen#26]
hi

can you implement av_parser_parse2
are do you know any 2nd way to decode frame from memory only .

**Comment by Ruslan-B** [comment]
Hi this is beyond binder support. However, you can take a look through one of my side project here: https://github.com/Ruslan-B/AR.Drone/tree/master/AR.Drone.Video

**Comment by pokernet** [comment]
thanks i will test it

**Comment by pokernet** [comment]
hi thanks for you help
this link help me to find my way
but i have last problem !
ffmpeg.auto use sbyte[] for ffmpeg.sws_scale or more functions
and you demo use bytes[]  for video convert
may be you cajn help me how can i solve this

thanks

**Comment by Ruslan-B** [comment]
No difference just use byte insted of sbyte.

**Comment by pokernet** [comment]
[image: Inline images 1]

i try to use it as is but i get error
i add screenshut for you to see

Thanks for helping
