### ISSUE TITLE
avdevice_register_all removed?

### ISSUE THREAD

**Issue by ispysoftware** [Ruslan-B/FFmpeg.AutoGen#264]
* **I'm submitting a ... **
  - [x] bug report

* **What is the current behavior?**

calling 
ffmpeg.avdevice_register_all(); and av_guess_format(...);
when using ffmpeg v6 is throwing a not supported exception
Message = "Specified method is not supported."
"   at FFmpeg.AutoGen.DynamicallyLoadedBindings.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

use ffmpeg v6, call ffmpeg.avdevice_register_all() and/ or av_guess_format(...);

* **What is the expected behavior?**

does it's thing. I'm not sure if this method has been removed from the API or is obsolete. I couldn't find anything in the ffmpeg code base saying it had been removed. av_guess_format is pretty critical.

* **Please tell us about your environment:**

- version:  latest, latest build of ffmpeg and v6 release build, windows, OSX and Linux. v5.x works fine.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
As I see it still taking same place in code base. Can you double check?

**Comment by ispysoftware** [comment]
Sorry my mistake, wrong path being set to RootPath

**Comment by c72578** [comment]
Shouldn't the message be different in this case?
It says `Specified method is not supported.`
Something like "Library `avdevice` not found" ...

**Comment by Ruslan-B** [comment]
@c72578 it is default behavior as in some configurations some libraries might not present intentionally..
If you like to ensure integrity, you do it before you start any work with ffmpeg by checking libraries presence in the specific location.
