### ISSUE TITLE
is there any good players written in C# using FFmpeg.AutoGen?

### ISSUE THREAD

**Issue by jcyuan** [Ruslan-B/FFmpeg.AutoGen#272]
better can output frame pixel data without rendering?
thanks.

**Comment by Ruslan-B** [comment]
Closing it now,  they are even example does it.

**Comment by jcyuan** [comment]
> 

ok, sorry,

actually i have implemented everything already: demux, decoding, rendering are seperated into different thread.
but just the performance is not very good, it takes some extra CPU, so i wanna know some suggestions.

**Comment by zgabi** [comment]
You should check ffmediaelement: https://github.com/unosquare/ffmediaelement
It is quite good, however not maintained anymore.. it is using ffmeg 4.x

And you should check your code with memory profiler. You should not allocate any object during the the play (after initialization of course)
And you should avoid copying the decoded frame's pixel data. (so decode directly to the required destination memory area)

I'm decoding several fullHD (or bigger) H.265 streams without any noticable cpu usage.

**Comment by jcyuan** [comment]
> You should check ffmediaelement: https://github.com/unosquare/ffmediaelement It is quite good, however not maintained anymore.. it is using ffmeg 4.x
> 
> And you should check your code with memory profiler. You should not allocate any object during the the play (after initialization of course) And you should avoid copying the decoded frame's pixel data. (so decode directly to the required destination memory area)
> 
> I'm decoding several fullHD (or bigger) H.265 streams without any noticable cpu usage.

lovely! thanks so much

**Comment by jcyuan** [comment]
> I think the better you describe the problem and why you need solve one is a key - we might but cannot guess 100% here, as fairly cheap memory to memory copy is not would you can expect in real life as you talking about GPU, has nothing to do with this project rather than expectations.

ok,~ thanks anyway! 😉

**Comment by jcyuan** [comment]
> @jcyuan https://github.com/SuRGeoNix/Flyleaf look this,DirectX instead of OpenGL ，I am also interested in opengl

thanks! ❤
