### ISSUE TITLE
Use fixed-size buffers instead of custom classes

### ISSUE THREAD

**Issue by jgcodes2020** [Ruslan-B/FFmpeg.AutoGen#275]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

Custom classes are used to represent members like `AVFrame::data` and `AVFrame::linesize` (fixed-size arrays)

* **What is the expected behavior?**

These should be mapped to fixed-size buffers:
```c#
public struct AVFrame {
  // ... other stuff above ...
  public fixed byte* data[8];
  // ... other stuff below ...
}
```

* **What is the motivation / use case for changing the behavior?**

Fixed-size buffers are more consistent with the underlying C API, and they decay directly to pointers when used.

* **Please tell us about your environment:**

- version: 6.0.0.2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

- Language reference: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/unsafe-code#fixed-size-buffers

**Comment by jgcodes2020** [comment]
Realized that pointers can't be used with fixed-size buffers.

**Comment by Ruslan-B** [comment]
Close this issue then
