### ISSUE TITLE
Recommendations for container deployment

### ISSUE THREAD

**Issue by CN-HM** [Ruslan-B/FFmpeg.AutoGen#276]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [ *] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
关于在docker linux容器环境下如何使用您的包，我觉得您可以应该在md文件中详细介绍一下。
比如在https://github.com/sdcb/Sdcb.FFmpeg这个项目当中，作者有详细介绍了如何在linux下使用，虽然这个介绍没有太多作用，但是也可以为其他人提供些思路。
以下是我对于docker linux(Debian) 64位环境下使用该包的一些建议，提供给后面使用的人作为一点参考：

1、在dockerfile中复制文件到Debian容器中
>FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
>........... （省略多余代码）
>COPY your_path/FFmpeg/lib/  /usr/lib/x86_64-linux-gnu
>// 此步骤可以省略，复制之后可以使用 ffmpeg -v 命令查看版本
>COPY your_path/FFmpeg/usr_bin/  /usr/bin
>........... （省略多余代码）

2、准备ffmpeg编译后的lib
>编译后的文件可以从该仓库下载：https://github.com/BtbN/FFmpeg-Builds/releases
>选择对应的版本下载即可

3、在项目中注册ffmpeg
>if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
>{
>if (!Directory.Exists(LinuxDefaultDirectory))
>{  
>Console.WriteLine($"{LinuxDefaultDirectory} not found! Register FFmpeg failed!");  
>}          
>            DynamicallyLoadedBindings.LibrariesPath = LinuxDefaultDirectory;
>        }

**Comment by Ruslan-B** [comment]
Please translate to English.

**Comment by CN-HM** [comment]
Ok, I've translated it into English, and your sample code doesn't include code used in the Linux environment, so as a beginner you need to rummage around for information, that's all for the convenience of beginners.

**Comment by Ruslan-B** [comment]
https://letmegooglethat.com/?q=install+ffmpeg+on+debian

**Comment by Ruslan-B** [comment]
I do not ship binaries as you can assemble - None LGPL code - which will be a problem eventually.

**Comment by Ruslan-B** [comment]
Not understand - I clearly mentioned you provide binaries - you can assemble GPL version as you wish. Just specify path to it. How complex it could be? Single command on debian. How it connected to repo - hard to imagine.
