### ISSUE TITLE
Missing some interfaces?

### ISSUE THREAD

**Issue by 794742233** [Ruslan-B/FFmpeg.AutoGen#277]
* **I'm submitting a ... **
  - [x] feature request

* **Missing some interfaces?**
avcodec_decode_video2
avcodec_decode_audio4
 Is it abandoned?

- version: 5.1.2.3

**Comment by Ruslan-B** [comment]
I support only what official api in headers all these functions are
internal and hidden in "c" files
Definition at line 2446
<https://ffmpeg.org/doxygen/2.7/libavcodec_2utils_8c_source.html#l02446> of
file utils.c
<https://ffmpeg.org/doxygen/2.7/libavcodec_2utils_8c_source.html>. to be
precise
FFmpeg is an enormous project - but has reasons to hide and provide
official API.

**Comment by Ruslan-B** [comment]
so far all is up to date - if I start to add internal functions it will blow up complexity of use even more than it is.
