### ISSUE TITLE
FFMpeg.Autogen.dll is failing Strong Name Validation

### ISSUE THREAD

**Issue by jpwkeeper** [Ruslan-B/FFmpeg.AutoGen#279]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [X ] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug.

* **What is the current behavior?**
*
I'm using FFMpeg.Autogen.dll in a .NET 4.8 Framework application.
FFMpeg.Autogen.dll is strongly named, but it is failing strong name validation.  I can verify this on my system with sn.exe -v Ffmpeg.Autogen.dll.  I'm seeing this error on a deployed system where I cannot bypass strong name validation.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
sn.exe -v Ffmpeg.Autogen.dll

* **What is the expected behavior?**
I would expect it to pass validation.  The dependent assemblies that are strongly named and passing validation.

* **What is the motivation / use case for changing the behavior?**
Can't run on deployed system.

* **Please tell us about your environment:**
.NET Framework 4.8, Visual Studio 2017, installed as an MSI file.
- version: 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
Use something like this  [.NET Assembly Strong-Name Signer](https://brutaldev.com/post/net-assembly-strong-name-signer)

**Comment by Ruslan-B** [comment]
Have to enplane a bit myself  a no one cares about it - there complications if you load it in app domain. Hence I don not see any befits of use of use of signed code
