### ISSUE TITLE
stream asx

### ISSUE THREAD

**Issue by wallmat** [Ruslan-B/FFmpeg.AutoGen#28]
When streaming and http that returns an asx it seems to only find one stream, the audio so we are unable to stream. is there a way to parse the asx to get the video stream correctly with your wrapper?

example url,
HTTP://nsx.nvfast.org:80/wme_-_las_vegas_blvd_and_charleston_ 

This is a traffic camera from Las Vegas. This works in VLC (used for testing) but i am not sure how to get the correct data with the autogen project.

**Comment by Ruslan-B** [comment]
How this question released to ffmpeg bindings???
