### ISSUE TITLE
System.NotSupportedException:“Specified method is not supported.”

### ISSUE THREAD

**Issue by huanyi00** [Ruslan-B/FFmpeg.AutoGen#280]
I build ffpeg on windows with mingW64  
run FFmpeg.AutoGen.Example show below 

![image](https://github.com/Ruslan-B/FFmpeg.AutoGen/assets/149284007/e48bf2f5-20bd-49e7-b742-bfc2c8f66e8f)

**Comment by Ruslan-B** [comment]
Means you fail to load ffmpeg dll(s). It works fine with provided but afaik mingW64 creates dependencies to itself wich might not auto resolvable

**Comment by Ruslan-B** [comment]
check path variable in and out - means you in command line and command line of starting example project  without modifications it will search binaries and works as it has all needed
