### ISSUE TITLE
can't get filtering_video.c FFmpeg example migrated to FFmpeg.AutoGen

### ISSUE THREAD

**Issue by KaFo** [Ruslan-B/FFmpeg.AutoGen#281]
I tried to migrate the FFmpeg video filtering example from https://www.ffmpeg.org/doxygen/trunk/filtering_video_8c-example.html to FFmpeg.AutoGen. Most stuff is straightforward, only the fact that [av_opt_set_int_list](https://www.ffmpeg.org/doxygen/trunk/group__opt__set__funcs.html#gac06fc2b2e32f67f067ed7aaec163447f) is a fancy macro rather than a converted function required a bit of work.

However the following call always results in a crash:
if (([ret](https://www.ffmpeg.org/doxygen/trunk/filter__design_8txt.html#af1ec77bdca1b30e8153fc5da88f603db) = [avfilter_graph_parse_ptr](https://www.ffmpeg.org/doxygen/trunk/group__lavfi.html#ga34f4ff420bd58da6747a3ff1fbedd001)([filter_graph](https://www.ffmpeg.org/doxygen/trunk/filtering__video_8c.html#a36c24d3c84d08e2f5a69e7368c211412), filters_descr,
 &[inputs](https://www.ffmpeg.org/doxygen/trunk/filter__design_8txt.html#a45917ba5e6c8b798c6e2ba6ca7301a5d), &[outputs](https://www.ffmpeg.org/doxygen/trunk/af__acontrast_8c.html#a7ddb0b5ac76101c5bee71e9840bf1698), [NULL](https://www.ffmpeg.org/doxygen/trunk/coverity_8c.html#a070d2ce7b6bb7e5c05602aa8c308d0c4))) < 0)

I put my code into a test repository here:
https://github.com/KaFo/FFmpeg.AutoGen.Samples/
(windows FFmpeg dlls included)

Actual relevant .cs code is in this class:
https://github.com/KaFo/FFmpeg.AutoGen.Samples/blob/main/FFmpeg.AutoGen.Samples/FFmpeg.AutoGen.Samples/FFmpegFilteringVideo.cs

Maybe somebody already got the filter stuff working. Any help is appreciated.

**Comment by Ruslan-B** [comment]
On it

**Comment by Ruslan-B** [comment]
@KaFo did you checked this repo https://github.com/stjeong/ffmpeg_autogen_cs btw?

**Comment by Ruslan-B** [comment]
closing topic
