### ISSUE TITLE
AVFrame missing hw_frames_ctx field?

### ISSUE THREAD

**Issue by filoe** [Ruslan-B/FFmpeg.AutoGen#29]
It seems like the AVFrame struct is missing the hw_frames_ctx field.
See http://ffmpeg.org/doxygen/trunk/structAVFrame.html
Am I wrong?

**Comment by Ruslan-B** [comment]
I guess it will be a part of next release. I'm regenerating bindings only for stable minor or major releases.

**Comment by filoe** [comment]
Ahh I see, I've the latest download from the ffmpeg website with compiled binaries and got some strange values in the channels field. So I've had a look at the provided header files and found out that there was missing the mentioned field. Their release management is quite confusing.

**Comment by Ruslan-B** [comment]
Do not say :). I'm grabbing binaries and headers coupled from here: https://ffmpeg.zeranoe.com/builds/win64/dev/
But again only with release number on archive.
