### ISSUE TITLE
Specied method not supported

### ISSUE THREAD

**Issue by Fayyaaz01** [Ruslan-B/FFmpeg.AutoGen#294]
I use a WPF application of .Net framework 4.8. I am trying to use FFmpeg.Autogen 6.1.0. I did as per you example code. I get a runtime error saying Specified method is not supported. 
On stackoverflow someone suggeted to use FFmpeg.Autogen below 6, I used 5.1.2.3. Same issue occured. Kindly guide me

**Comment by Ruslan-B** [comment]
Here we go, you faced not exported method, hence it is all simple you are using most probably mixing native libraries and c# bindings as I don't supply them in pair - legal reason - first thing to check. Usually good start to use GPL binaries from here.

**Comment by Ruslan-B** [comment]
I assume  we can close it safely you have to match nuget version to the point it matches higher two digits with native binaries. Advanced and converted examples are linked in readme.
Native FFmpeg you have to use or GPL or you have to build yours or source them yourself.
