### ISSUE TITLE
Any fileds in AVFrame after crop_top/crop_bottom/crop_left/crop_right cannot fill correctly in 32bit system 

### ISSUE THREAD

**Issue by 29654761** [Ruslan-B/FFmpeg.AutoGen#295]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
AVFrame struct fileds witch after crop_top/crop_bottom/crop_left/crop_right get disorderly order in 32bit

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
For example
AVFrame* frame = ffmpeg.av_frame_alloc();
frame->sample_rate = 48000;
frame->format = (int)AVSampleFormat.AV_SAMPLE_FMT_S16;
frame->nb_samples = 480;
ffmpeg.av_channel_layout_default(&frame->ch_layout, 0);

av_channel_layout_default always return -22 because frame->ch_layout cannot fill correctly.
Any fileds in AVFrame after crop_top/crop_bottom/crop_left/crop_right cannot fill correctly in 32bit system .

* **What is the expected behavior?**
In c++ code crop_top/crop_bottom/crop_left/crop_right are defined with size_t , this sizeof(size_t) is 4 for 32bit system and 8 for 64bit system,
but they are defined ulong in C# code, so alway 8 bytes size.

so please defined nint for crop_top/crop_bottom/crop_left/crop_right.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
I used ffmpeg.autogen in arm32 for android

- version: 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by 29654761** [comment]
After my testing, sizeof(size_t) is always 4 bytes , whatever arm64-v8a or armeabi-v7a
This is difficute to process

**Comment by Ruslan-B** [comment]
I don't support 32bit anymore, however, you can generate your very own version then it might work.
