### ISSUE TITLE
Break change in FFmepg.AutoGen version 7.0.0

### ISSUE THREAD

**Issue by zydjohnHotmail** [Ruslan-B/FFmpeg.AutoGen#304]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

Hi, I am using some kind of HLS download software to test one short HLS live stream, but I got run time errors:
Hi, I have checked the latest version of ffmpeg for Windows, and I found they are brand new, only 4 hours.  So I downloaded the windows binaries and copied them to this folder: G:\VideoFiles>where ffmpeg

C:\Program Files\ffmpeg\ffmpeg.exe => Then I run my test code, but I got the same error: System.Reflection.TargetInvocationException

 HResult=0x80131604
 Message=Exception has been thrown by the target of an invocation.
 Source=System.Private.CoreLib
 StackTrace:
  at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Reflection\MethodBaseInvoker.cs:line 117
  at System.Delegate.DynamicInvokeImpl(Object[] args) in System\Delegate.cs:line 55
  at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
  at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Threading\ExecutionContext.cs:line 154
--- End of stack trace from previous location ---
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Threading\ExecutionContext.cs:line 154
  at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
  at System.Windows.Forms.Control.WndProc(Message& m)
  at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
  at Windows.Win32.PInvoke.DispatchMessage(MSG* lpMsg)
  at System.Windows.Forms.Application.ComponentManager.Microsoft.Office.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
  at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
  at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
  at HLSDownloadTestForm.Program.Main() in D:\RaceOCR\HLSVideo\HLSDownloadTestForm\HLSDownloadTestForm\Program.cs:line 14

 This exception was originally thrown at this call stack:
  FFmpeg.AutoGen.DynamicallyLoadedBindings.Initialize.AnonymousMethod__2_1320(FFmpeg.AutoGen.AVIOContext**, string, int, FFmpeg.AutoGen.AVIOInterruptCB*, FFmpeg.AutoGen.AVDictionary**)
  FFmpeg.AutoGen.DynamicallyLoadedBindings.Initialize.AnonymousMethod__2_609(FFmpeg.AutoGen.AVIOContext**, string, int, FFmpeg.AutoGen.AVIOInterruptCB*, FFmpeg.AutoGen.AVDictionary**)
  FFmpeg.AutoGen.ffmpeg.avio_open2(FFmpeg.AutoGen.AVIOContext**, string, int, FFmpeg.AutoGen.AVIOInterruptCB*, FFmpeg.AutoGen.AVDictionary**)
  HLSDownload.Converter.IOContext.IOContext(string, int) in IOContext.cs
  HLSDownload.Converter.MediaConcatenator.Build() in MediaConcatenator.cs
  HLSDownloadTestForm.Form1.CreateOutputFile(System.Collections.Generic.List<string>, HLSDownload.Grabber.Grabbed.GrabbedHlsStreamMetadata) in Form1.cs
  HLSDownloadTestForm.Form1.Grab(HLSDownload.Grabber.Grabbed.GrabbedHlsStream, HLSDownload.Grabber.Grabbed.GrabbedHlsStreamMetadata, HLSDownload.Grabber.GrabResult) in Form1.cs
  HLSDownloadTestForm.Form1.Grab(System.Uri) in Form1.cs
  HLSDownloadTestForm.Form1.BTNDownload_Click(object, System.EventArgs) in Form1.cs
  System.Threading.Tasks.Task.ThrowAsync.AnonymousMethod__128_0(object) in Task.cs
  ...

  [Call Stack Truncated]

Inner Exception 1:
NotSupportedException: Specified method is not supported.

=> I can show you some related code for this part:     public void Build()
    {
      AVStream*[] streams = new AVStream*[2];
      Dictionary<MediaStreamType, int> stream_dic = [];
      ValidateArguments();
      // create decoders
      Dictionary<MediaStreamType, MediaDecoder> decoders = MakeDecoders();
      try
      {
        // open output iocontext
        using IOContext output = new(OutputPath, ffmpeg.AVIO_FLAG_WRITE);
        // open muxer
        using MediaMuxer muxer = new(output, OutputShortName, OutputMimeType);
        // add streams
        int index = 0;
        foreach (KeyValuePair<MediaStreamType, MediaDecoder> decoderPair in decoders)
        {
          MediaDecoder decoder = decoderPair.Value;
          AVCodecID targetCodec = decoder.CodecId;
          AVCodecContext* decoderCodec = decoder.CodecContext;
          switch (decoderPair.Key)
          {
            case MediaStreamType.Audio:
              if (TargetAudioCodec != null)
                targetCodec = TargetAudioCodec.Value;
              break;
            case MediaStreamType.Video:
              if (TargetVideoCodec != null)
                targetCodec = TargetVideoCodec.Value;
              break;
          }
          AVCodec* encoder = ffmpeg.avcodec_find_encoder(targetCodec);
          AVStream* outStream = muxer.AddStream(encoder);
          AVCodecParameters* param = outStream->codecpar;
          streams[index] = outStream;
          stream_dic.Add(decoderPair.Key, index++);

          AVCodecContext* codecContext = ffmpeg.avcodec_alloc_context3(encoder);
          if (codecContext == null)
          {
            // Handle error
          }

          if (ffmpeg.avcodec_parameters_to_context(codecContext, outStream->codecpar) < 0)
          {
            // Handle error
          }
          if (decoder.CodecId == targetCodec)
          {
            // converting to the same codec
            ffmpeg.avcodec_parameters_from_context(param, codecContext).ThrowOnError();
          }
          else
          {
            // converting to another codec
            switch (decoderPair.Key)
            {
              case MediaStreamType.Audio:
                param->codec_id = targetCodec;
                param->codec_type = AVMediaType.AVMEDIA_TYPE_AUDIO;
                param->sample_rate = decoderCodec->sample_rate;
                outStream->time_base = decoderCodec->time_base;
                break;
              case MediaStreamType.Video:
                throw new NotSupportedException();
            }
          }
          outStream->codecpar->codec_tag = 0;
        }
        // write headers
        muxer.WriteHeader();
        // write packets
        long audio_dts = ffmpeg.AV_NOPTS_VALUE;
        long video_dts = ffmpeg.AV_NOPTS_VALUE;
        long audio_pts = 0, video_pts = 0;
        KeyValuePair<MediaStreamType, MediaDecoder> audio_stream = 
          decoders.Where(pair => pair.Key == MediaStreamType.Audio).First();
        KeyValuePair<MediaStreamType, MediaDecoder> video_stream = 
          decoders.Where(pair => pair.Key == MediaStreamType.Video).First();
        bool any_audio = true, any_video = true;

        while (true)
        {
          bool anyPacket = false;
          while (any_audio || any_video)
          {
            KeyValuePair<MediaStreamType, MediaDecoder> decoderPair;
            // choose a decoder pair
            if (!any_audio)
              decoderPair = video_stream;
            else if (!any_video)
              decoderPair = audio_stream;
            else
            {
              // choose between audio and video
              decoderPair = video_dts < audio_dts ? video_stream : audio_stream;
            }
            // decoder is chosen now,
            // let's read and encode
            MediaDecoder decoder = decoderPair.Value;
            int stream_index = stream_dic[decoderPair.Key];
            AVStream* outputStream = streams[stream_index];
            if (decoder.CodecId == outputStream->codecpar->codec_id)
            {
              // simply copy to target stream
              using MediaPacket inputFrame = decoder.ReadPacket();
              if (inputFrame == null)
              {
                if (decoder == audio_stream.Value)
                  any_audio = false;
                else
                  any_video = false;
                continue;
              }
              AVPacket* pck = inputFrame.Pointer;
              ffmpeg.av_packet_rescale_ts(pck, decoder.TimeBase, outputStream->time_base);
              pck->stream_index = stream_index;
              long* last_dts, last_pts;
              switch (decoder.CodecContext->codec_type)
              {
                case AVMediaType.AVMEDIA_TYPE_AUDIO:
                  last_dts = &audio_dts;
                  last_pts = &audio_pts;
                  break;

                case AVMediaType.AVMEDIA_TYPE_VIDEO:
                  last_dts = &video_dts;
                  last_pts = &video_pts;
                  break;
                default:
                  throw new NotSupportedException();
              }

              if (pck->dts < (*last_dts + ((muxer.FormatContextPtr->oformat->flags & ffmpeg.AVFMT_TS_NONSTRICT) > 0 ? 0 : 1)) && pck->dts != ffmpeg.AV_NOPTS_VALUE && *last_dts != ffmpeg.AV_NOPTS_VALUE)
              {
                long next_dts = (*last_dts) + 1;
                if (pck->pts >= pck->dts && pck->pts != ffmpeg.AV_NOPTS_VALUE)
                  pck->pts = Math.Max(pck->pts, next_dts);
                if (pck->pts == ffmpeg.AV_NOPTS_VALUE)
                  pck->pts = next_dts;
                pck->dts = next_dts;
              }
                (*last_dts) = pck->dts;
              muxer.WritePacket(pck);
              anyPacket = true;
            }
            else
              throw new NotSupportedException("Format conversion is not supported.");
          }
          if (!anyPacket)
            break;
        }

        // write trailer
        muxer.WriteTrailer();
      }

      finally
      {
        // dispose decoders
        foreach (MediaDecoder decoder in decoders.Values)
          decoder.Dispose();
      }
    }

=> I asked AI, and they agree that the issue could be due to break change in new version (7.0.0).  But the old repo used an old version of Ffmpeg.AutoGen (vesion 4.4.1.1), which I think it is too old, so I don't want to downgrade the current version of Ffmepg.AutoGen. 
But is it possible that you know how to fix the related code, so the repo will work with the latest version of Ffmpeg.AutoGen?
Thanks

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- version: 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Ruslan-B** [comment]
Hello there have to drop few example projects, we on 7 now fell free to use 6 generally ffmpeg produces at release something that barely work. AI he as ask - terribly world.

**Comment by Ruslan-B** [comment]
version platform, etc, ffmpeg binaries - however if all used to work why you need switch to 7? proven head ache.

**Comment by Ruslan-B** [comment]
if it about 7.0 days has to come, it will be stable just replace or compile binaries, ho change needed here.

**Comment by zydjohnHotmail** [comment]
Hi,
I don't quite understand your short term sentences.  But from the readme part of this repo, the code seems 2 years ago, when maybe the version of software is 4 or 5, not even 6 yet.  But today, the new version is 7; then I have C# code showing that the new version has some break changes for the current version (version 7.0.0).  But you said just replace or compile binaries, does this sound logic?

**Comment by Ruslan-B** [comment]
It is logic 7.0 means semantic changes they change API not me, read and re read once again - I do not have influence what community stirs ffmpeg. Merrily providing good wrapper that it.

**Comment by Ruslan-B** [comment]
Open source not meant to be free and problem less I have to delete two nice examples as it simply don't compile. No other say word as keep running years. I contacted author no response.

**Comment by Ruslan-B** [comment]
Besides basics are working fine. encode and decode working as well. Main example is okay. Everything up to date. I just give a tool. Question?

**Comment by Ruslan-B** [comment]
you violated rules I established here to help, I have no to time to explain how an what to use, I'll delete this as abuse of open source.

**Comment by Ruslan-B** [comment]
Don’t see reason why to complain, advanced stuff any way broken between releases
