### ISSUE TITLE
It seems `HWDeviceContext` are missing?

### ISSUE THREAD

**Issue by jcyuan** [Ruslan-B/FFmpeg.AutoGen#306]
like, 
    `AVCUDADeviceContext`,
    `AVDXVA2DeviceContext`,
    `AVQSVDeviceContext`,
    `AVVDPAUDeviceContext`
    etc...

currently i have written a simple `AVCUDADeviceContext` by my own to use, but yeah, still prefer official version.
so, any plan sir? thanks so much.

**Comment by Ruslan-B** [comment]
I'll try add them, as they need cuda.h might be an issue - in case of time and research.

**Comment by jcyuan** [comment]
> I'll try add them, as they need `cuda.h` might be an issue - in case of time and research. As it is a rabbit hole means I have add all referenced structures as they are part of the structures not referenced. For refence : `typedef struct AVCUDADeviceContext { CUcontext cuda_ctx; CUstream stream; AVCUDADeviceContextInternal *internal; } AVCUDADeviceContext;`

yes totally understand man, hope it won't take too much of your time. and thanks again.

**Comment by Ruslan-B** [comment]
I'll try to look next week, I'll limit research to Cuda and DirectX - need understand how big is the fish besides how to use it at all and value of adding them.

**Comment by Ruslan-B** [comment]
besides questions has to asked to ffmpeg API creators - they do nasty unnecessary stuff just because they used to it. :)

**Comment by Ruslan-B** [comment]
this one down by now lets open once again desing is bad I cannot bring here all cuda here - will fight can be pointer instead of structure
