### ISSUE TITLE
Will it work in mobile and web platform? 

### ISSUE THREAD

**Issue by Barshan-Mandal** [Ruslan-B/FFmpeg.AutoGen#309]
will it work in latest .net maui platforms and blazor web applications?If yes,show me some examples.

**Comment by Ruslan-B** [comment]
blazor , you kidding - works as mobile native - provided you can assemble ffmpeg binaries  - use case not clear

**Comment by Ruslan-B** [comment]
I'll keep i close but will reply if any other questions
