### ISSUE TITLE
FFmpeg 3.1.1 "Laplace" support

### ISSUE THREAD

**Issue by catester** [Ruslan-B/FFmpeg.AutoGen#32]
If you use FFmpeg 3.1.1 DLLs with current 3.0 bindings **avcodec_find_decoder** method always returns null so it's pretty unusable for opening video files.

So I tried to regenerate the bindings for 3.1.1 exports but it generated some crazy code which is not even compilable, for example:

```
    public unsafe static partial class ffmpeg
    {
        public const int LIBAVCODEC_VERSION_MAJOR = 57;
        public const int LIBAVCODEC_VERSION_MINOR = 48;
        public const int LIBAVCODEC_VERSION_MICRO = 101;
        public const int LIBAVCODEC_VERSION_INT = AV_VERSION_INT(LIBAVCODEC_VERSION_MAJOR,LIBAVCODEC_VERSION_MINOR,LIBAVCODEC_VERSION_MICRO);
        public const int LIBAVCODEC_VERSION = AV_VERSION(LIBAVCODEC_VERSION_MAJOR,LIBAVCODEC_VERSION_MINOR,LIBAVCODEC_VERSION_MICRO);
        public const int LIBAVCODEC_BUILD = LIBAVCODEC_VERSION_INT;
        public const int LIBAVCODEC_IDENT = "Lavc"AV_STRINGIFY(LIBAVCODEC_VERSION);
        public const int FF_API_VIMA_DECODER = (LIBAVCODEC_VERSION_MAJOR<58);
        public const int FF_API_AUDIO_CONVERT = (LIBAVCODEC_VERSION_MAJOR<58);
        public const int FF_API_AVCODEC_RESAMPLE = FF_API_AUDIO_CONVERT;
        public const int FF_API_GETCHROMA = (LIBAVCODEC_VERSION_MAJOR<58);
        public const int FF_API_MISSING_SAMPLE = (LIBAVCODEC_VERSION_MAJOR<58);
```

So it directly puts macros like AV_VERSION_INT (can't resolve it?) and marks all constants int instead of bool.

Note that FFmpeg upto 3.0.2 works good with current 3.0 bindings.

 I hope you can add support for the latest FFmpeg 3.1.1 soon.

**Comment by Ruslan-B** [comment]
I'll update library as soon build appear at https://ffmpeg.zeranoe.com/builds/
And yes it is know problem as #18 and it is also connected with #31.
But for now I fixing macroses manualy.

**Comment by GoaLitiuM** [comment]
Any news/progress on this?

It looks like zeranoe stopped producing versioned builds, and recommends to use the latest git build at all times suggested by the blog posts in the site.

**Comment by Ruslan-B** [comment]
Ok, I'll take a look.

Cheers,
Ruslan

**Comment by Ruslan-B** [comment]
I'll generate new bindings on or before 24-09-2016
