### ISSUE TITLE
av_version_info causes AccessViolationException

### ISSUE THREAD

**Issue by csnewman** [Ruslan-B/FFmpeg.AutoGen#34]
When using the ffmpeg.av_version_info method, I get a "System.AccessViolationException", here are some of the details:
"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."
Stacetrace 
`   at Microsoft.Win32.Win32Native.CoTaskMemFree(IntPtr ptr)`
`   at FFmpeg.AutoGen.ffmpeg.av_version_info()`
`[REMOVED]`

I have found two ways of fixing this, 
- Using a [custom marshaler](http://stackoverflow.com/a/38677638/2547808)
- Changing the return type of av_version_info to char* and then using `Marshal.PtrToStringAnsi((IntPtr) ffmpeg.av_version_info())`

I am unsure if there is a better fix this however the first one could be incorporated directly into this project.

**Comment by Ruslan-B** [comment]
Thank you. I'll take a look on or before 24-09-2016

**Comment by Ruslan-B** [comment]
Thank you I integrated this fix manually by now by I'll add to generation process as well.
