### ISSUE TITLE
Encode2Stream

### ISSUE THREAD

**Issue by anhlunnhaque** [Ruslan-B/FFmpeg.AutoGen#36]
First of all. Great project and I think this is the latest .NET ffmpeg project.

I am new to ffmpeg and was wondering if FFmpeg.AutoGen is able to encode to stream. I would like to read a local file (c:\temp\file.mkv),
encode it into streams then live stream it to a client. The request would go through via MVC WebApi with headers that specify resolution to encode etc..

Any examples would be appreciated.

Thanks,
AL

**Comment by Ruslan-B** [comment]
Hello AL,

Yes it can, there a bunch of examples in C, they portable almost one to one, implying that you know .
If you are looking for specific example I would advice you to ask same thing on stackoverflow.

Cheers,
Ruslan
