### ISSUE TITLE
AvFrame changed from byte[] to sbyte[] ?

### ISSUE THREAD

**Issue by OhSoGood** [Ruslan-B/FFmpeg.AutoGen#37]
Hi,
First a big thank for your work on ffmpeg - I do appreciate it!

My code is using an old version of your wrapper (based on FFmpeg 2.3.6, from 2015-01-06).
I wanted to upgrade to your latest release, but discovered that the AvFrame struct is now using sbyte pointers instead of byte pointers for dataX fields (your commit as of Nov 7, 2015). Yet, all my code in the upper classes uses bytes (byte arrays, Marshal.Copy, etc.) and at the end, when I transform into an image, it is with a byte[].

How would you advice me to do? Should I convert sbyte[] to byte[] as soon as possible in my code? Can I simply do it by using `byte[] byteArray = (byte[])(Array)mySbyteArray` ?

Thank you for your answers!

**Comment by Ruslan-B** [comment]
Hi @OhSoGood ,
The reason behind change - string marshaling you need to duck cast byte* to sbyte* every time, so it just bizarre thing in .net marshaling.
But long story short according to [this post](http://stackoverflow.com/questions/829983/how-to-convert-a-sbyte-to-byte-in-c) you just can duck cast to byte[] it and will work fine.

Cheers,
@Ruslan-B

**Comment by OhSoGood** [comment]
Thanks a lot for the quick reply!
