### ISSUE TITLE
FFmpeg 3.2

### ISSUE THREAD

**Issue by Xcone** [Ruslan-B/FFmpeg.AutoGen#38]
Hi, 

Awesome job on this AutoGen project! It's proven very useful.

My software suffers from a thread-handle leak in an older version of zeraroe FFmpeg. After updating to 3.1.4 (that comes with current version of AutoGen) the leak is still applicable. But when I use the DLL's of version 3.2 the thread handle leak appears fixed. Unfortunately, some random Access Violation may occur after several hours of running and switching streams. I suspect this is because the generated code of FFmpeg 3.1.4 does not match the code for 3.2. 

Unfortunately I run into similar issues as previously reporting in https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/24 when I try to update AutoGen with the 3.2 binaries of Zeranoe FFmpeg by myself. And by the looks of things, some manual steps are required?

So my question is; Will you update AutoGen to make use of the latest FFmpeg in the near future?

With thanks and regards,
Koen Visser

**Comment by Ruslan-B** [comment]
Hi Koen,
Yes, some manual steps are needed - some macros needs to be fixed manually (or dropped). I'll update library by the end of tomorrow.
Cheers,
Ruslan

**Comment by Xcone** [comment]
Hi Ruslan!

I see you already processed the update. Amazing!
I'll grab the update and give my tests another try to see if I have more success now.

Thanks!
Koen Visser
