### ISSUE TITLE
images to mp4

### ISSUE THREAD

**Issue by ChenZhaobin** [Ruslan-B/FFmpeg.AutoGen#40]
I am very appreciate for your wonderful work ,since I am not familar with your lib yet,could you give us an example of how to use autogen to convert images to mp4?

**Comment by Ruslan-B** [comment]
@ChenZhaobin I truly appreciate your interests, but I would advice you to move this question to stackoverflow.com or search for an example in c(lang) with some effort you can convert to c# as ffmpeg functions and structures are equal.

**Comment by ChenZhaobin** [comment]
Thanks !
