### ISSUE TITLE
Issue streaming H264 video via RTP

### ISSUE THREAD

**Issue by mdimaculangan** [Ruslan-B/FFmpeg.AutoGen#41]
Currently, we cannot stream H264 video sent via RTP. We we're able to get the input and stream info but we have gotPicture always set to 0 when we decode. 

We are wondering if we are missing anything in the configuration to make this work. We also found some old articles that suggest to remove first the RTP header and reconstruct the fragments before decoding the byte[].

**Comment by Ruslan-B** [comment]
I simply cant help here and would advice you to move this question to stackoverflow.com.
