### ISSUE TITLE
Access AVFrame data

### ISSUE THREAD

**Issue by GoelBiju** [Ruslan-B/FFmpeg.AutoGen#43]
Hi,

I am quite new to FFmpeg and the AutoGen library and was wondering as to how I can access the data within an allocated AVFrame.

I allocated an AVFrame via 

```C#
AVFrame* encodedFrame = ffmpeg.av_frame_alloc();
```

However I cannot access the data when calling:
```C#
encodedFrame->data;
```
since doesn't exist, I only have access to data0 up until data7. 

I was trying to encode pixel data which was gained from decoding a JPEG image via av_send_packet() and av_receive_frame(). And I wanted to encode the RGB data into YUV_420P to get make sure I can create an FLV1 frame (ffmpeg.AVCodec.AV_CODEC_ID_FLV1).

**Comment by Ruslan-B** [comment]
Hello, I would advice you to move this question to stackoverflow.com or search for an example in c(lang) with some effort you can convert to c# as ffmpeg functions and structures are equal.
