### ISSUE TITLE
AVFrame.data contruct

### ISSUE THREAD

**Issue by GoelBiju** [Ruslan-B/FFmpeg.AutoGen#44]
Hi Mr. @Ruslan-B ,

I posted a week before saying how I had no access to AVFrame.data and that I could only use AVFrame.data0 - AVFrame.data7. Would it be possible if we could access AVFrame.data by just constructing a list of the pointers to the data from data0 to data7?

Thank you.

**Comment by Ruslan-B** [comment]
Well, short answer no, as data0 - data7 is a lesser common evil. The long one this just limitation of c# interop as you cannot use fixed array here because pointer is not an interop blessed type for fixed arrays.
Technically it is possible to generate an extension here but you can do it yourself as well.
Could you please provide a use case here?

**Comment by GoelBiju** [comment]
Thanks for the reply Mr. @Ruslan-B ,

I had made a sample program to try to encode an image file into 1 frame of video data. [Here](https://github.com/GoelBiju/FFmpeg.AutoGen.Samples/blob/master/samples/FFmpeg.AutoGen.Samples/Program.cs#L270) is the main issue, I cannot seem to access sbyte*[] pointers to get the AVFrame.data and to get the AVFrame.linesize. This has been an issue especially when using functions like sws_scale or setting up a context to convert pixel formats e.g. from YUVJ422P to YUV420P.

**Comment by Ruslan-B** [comment]
Well in the example I see decoding not encoding.
Any way if you deduce the type you will get something like this ```sbyte** src = &pDecodedFrame->data0;```.
You should read it like **address of** pDecodedFrame->data0 - which is a pointer to a pointer of data0.

Thus if you would like to access a frame data you need write something like this:
```csharp             
var data = new sbyte[pDecodedFrame->linesize[0] * pDecodedFrame->height];
for (int i = 0; i < data.Length; i++)
{
        data[i] = *(pDecodedFrame->data0 + i);
}
```
If you would like to pass a data from c# size you just need to pin a managed array:
```
var data = new sbyte[pDecodedFrame->linesize[0] * pDecodedFrame->height];
fixed (sbyte* pData = data)
{
    pDecodedFrame->data0 = pData;
```

Besides here is the quote from original documentation:
```c
 /**
     * pointer to the picture/channel planes.
     * This might be different from the first allocated byte
     *
     * Some decoders access areas outside 0,0 - width,height, please
     * see avcodec_align_dimensions2(). Some filters and swscale can read
     * up to 16 bytes beyond the planes, if these filters are to be used,
     * then 16 extra bytes must be allocated.
     *
     * NOTE: Except for hwaccel formats, pointers not needed by the format
     * MUST be set to NULL.
     */
    uint8_t *data[AV_NUM_DATA_POINTERS];
```

Does it make any scene?

**Comment by GoelBiju** [comment]
Thanks for the help Mr. @Ruslan-B , I will give this a try and sorry it was decoding. I was trying to make the image file from YUVJ422P to YUV420P so then I can encode that via the flv1 encoder in FFmpeg.

**Comment by Ruslan-B** [comment]
Okey, than I'm going to close this issue, if any need any help just send an email.

**Comment by GoelBiju** [comment]
Sure, again thank you Mr. @Ruslan-B .
