### ISSUE TITLE
replace intptr with StringBuilder in avutil.g.cs

### ISSUE THREAD

**Issue by ispysoftware** [Ruslan-B/FFmpeg.AutoGen#48]
In avutil.g.cs, should be 

        [DllImport(libavutil, EntryPoint = "av_log_format_line", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern void av_log_format_line(void* @ptr, int @level, [MarshalAs(UnmanagedType.LPStr)] string @fmt, sbyte* @vl, StringBuilder @line, int @line_size, int* @print_prefix);
        
        [DllImport(libavutil, EntryPoint = "av_log_format_line2", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern int av_log_format_line2(void* @ptr, int @level, [MarshalAs(UnmanagedType.LPStr)] string @fmt, sbyte* @vl, StringBuilder @line, int @line_size, int* @print_prefix);

**Comment by Ruslan-B** [comment]
I'm not quite convinced that you should use managed StringBuilder here as this is receiving buffer.
Besides trying to guess why do you even need to call these functions from C#.
Could you please elaborate?

**Comment by ispysoftware** [comment]
Hello yes, I'm using it to log ffmpeg output. Converting the signature
IntPtr to a StringBuilder was the only way I could get it to work - and it
does work fine.


     private static IntPtr _delegatePtr;
     private static AvFormatLogCallback _avLogCallback;

     public static unsafe void SetFfmpegLogging(bool log)
   {
       if (log)
       {
           ffmpeg.av_log_set_level(ffmpeg.AV_LOG_INFO);
           _avLogCallback = AvFormatLogFunc;
           _delegatePtr =
Marshal.GetFunctionPointerForDelegate(_avLogCallback);
           ffmpeg.av_log_set_callback(_delegatePtr);
       }
       else
       {
           ffmpeg.av_log_set_level(ffmpeg.AV_LOG_QUIET);
                ffmpeg.av_log_set_callback(IntPtr.Zero);
       }

   }


        public static unsafe void AvFormatLogFunc(void* ptr, int level,
string fmt, sbyte* vl)
        {
            if (level > ffmpeg.av_log_get_level()) { return; }
            fmt = fmt.Trim();
            if (string.IsNullOrEmpty(fmt)) { return; }
            StringBuilder line = new StringBuilder(1024);
            int printPrefix = 1;
            ffmpeg.av_log_format_line(ptr, level, fmt, vl, line,
line.Capacity,
                    &printPrefix);

            Logger.LogFfmpeg(line.ToString());
        }

**Comment by Ruslan-B** [comment]
Well, the byte buffer should work in the same way, then you can convert it to string.
I know it is not optimal, but I think you can't just replace all ```char *``` to the ```StringBuilder```.

**Comment by Ruslan-B** [comment]
I'll try to address in current migration to CppSharp.

**Comment by ispysoftware** [comment]
It's fine, i modified our code to use a byte array and it's working ok.
Just means you have to use GC or unsafe.

On Tue, Feb 14, 2017 at 5:48 AM, Ruslan Balanukhin <notifications@github.com

**Comment by Ruslan-B** [comment]
After reworking of the binding generation. I reviewed your code once again.
This my unsafe version:
```csharp
ffmpeg.av_log_set_level(ffmpeg.AV_LOG_VERBOSE);
av_log_set_callback_callback logCallback = (p0, level, format, vl) =>
{
    if (level > ffmpeg.av_log_get_level()) return;
                
    var lineSize = 1024;
    var lineBuffer = stackalloc byte[lineSize];
    var printPrefix = 1;
    ffmpeg.av_log_format_line(p0, level, format, vl, lineBuffer, lineSize, &printPrefix);
    var line = Marshal.PtrToStringAnsi((IntPtr) lineBuffer);
    Console.Write(line);
};
ffmpeg.av_log_set_callback(logCallback);
```
I also integrated this pice into example.
