### ISSUE TITLE
Example error on hi resulotion like 1920x1080 Crash !!!!

### ISSUE THREAD

**Issue by pokrnet** [Ruslan-B/FFmpeg.AutoGen#50]
var convertedFrameBuffer = stackalloc byte[convertedFrameBufferSize]; stackoverflow error ?

**Comment by Ruslan-B** [comment]
Quite obvious stack size has limits - allocate array and pin it.

**Comment by pokernet** [comment]
hi ruslan,
thanks for the answer
may be you can fix the example to support high resulotion or my be you can give me example how to fix this

**Comment by pokernet** [comment]
ok i find the fix 👍 
if any one need to use it with high resolution  buffer this is working ->

-->
 var dataArray_onvertedFrameBuffer = new byte[convertedFrameBufferSize];
            var dstData = new byte_ptrArray4();
            var dstLinesize = new int_array4();
            fixed (byte* array = dataArray_onvertedFrameBuffer)
            {
ffmpeg.av_image_fill_arrays(ref dstData, ref dstLinesize, array, destinationPixFmt, width, height, 1);
...
...
...


}

**Comment by Ruslan-B** [comment]
yes, that it

**Comment by Ruslan-B** [comment]
Fix in https://github.com/Ruslan-B/FFmpeg.AutoGen/commit/a793077628cb772e9e7fb4faca1528516424cd0d.
