### ISSUE TITLE
License for the generated files?

### ISSUE THREAD

**Issue by xupefei** [Ruslan-B/FFmpeg.AutoGen#51]
Hi, thanks for this wonderful tool. We now have a project which is using the output from this tool, and we want to publish it to NuGet by either MS-Pl or MIT(discussion [here](https://github.com/unosquare/ffmediaelement/issues/1)). One remaining block ahead is the license issue: we are not sure about the license of the output from your AutoGen program because [the output of a GPL program is not automatically protected by GPL](https://www.gnu.org/licenses/gpl-faq.en.html#WhatCaseIsOutputGPL). Therefore could you add a license to the generated file, so we'll know how to use it correctly?

Thanks!

**Comment by Ruslan-B** [comment]
Hi, I'm not a licensing guru but the input files (ffmpeg headers) are licensed under LGPL v2 and the only legal action is to link dynamically using these files.
Strictly speaking, the generator creates a derivative work as it copies pretty much everything preserving macroses, names and comments were possible and some if that stuff might fall under copyright.
Thus to avoid any collisions I'm using compatible LGPL v3 for the entire repository including generated output. 
So you cannot re-license the generated output under MS-Pl or MIT. 
Thus, in case you would like to be fully complaint and keep your project you under MS-Pl or MIT you need to consume the FFmpeg.AutoGen as a dynamic library. 
Nevertheless you also depending on ffmpeg which is already LGPL v2.
Please also take in to account that you cannot use default binaries from zeranoe as the do include GPL libraries linked statically.

**Comment by mariodivece** [comment]
Thank you @Ruslan-B , it looks like I will have to copy your LGPLv3 license for the generated code and deploy it as a separate assembly, plus not provide any sort of FFmpeg binaries in the NuGet package in order to keep it as MS-PL or MIT. Thanks again for keeping this project updated!

**Comment by xupefei** [comment]
Thanks @Ruslan-B for the explanation. I think the issue can now be closed 👍
