### ISSUE TITLE
Access to TimeCode functions?

### ISSUE THREAD

**Issue by MrBean2016** [Ruslan-B/FFmpeg.AutoGen#53]
I cannot find the functions for timecode conversion like av_timecode_get_smpte_from_framenum

https://www.ffmpeg.org/doxygen/2.1/libavutil_2timecode_8h.html

Where can I find them?
thanks,

**Comment by Ruslan-B** [comment]
This header file wasn't included. Now it is. I also updated ffmpeg version to 3.3.2.

**Comment by MrBean2016** [comment]
Great! Thanks
