### ISSUE TITLE
Add more library to FFmpeg.Autogen

### ISSUE THREAD

**Issue by dinhle2010** [Ruslan-B/FFmpeg.AutoGen#56]
Hi Ruslan,

The project FFmpeg.Autogen is helpfull for me, but it only simple function. I want to add more function same FFmpeg.exe tool. How i can do that. Please help me.

Thanks,

**Comment by mariodivece** [comment]
You will need to port ffmpeg.c 
The source is all on GitHub. Good luck :S

**Comment by dinhle2010** [comment]
Hi @mariodivece,
How about c#. I only know c# :)
Thanks,

**Comment by Ruslan-B** [comment]
You **need** to know both languages. Closing Issue as to it is generic question.
