### ISSUE TITLE
Crashing on close

### ISSUE THREAD

**Issue by gnsx** [Ruslan-B/FFmpeg.AutoGen#6]
FFmpegInvoke.avformat_close_input(&pFormatcurrent);
causes a crash.
I am u using ffmpeg.autogen.dll in unity to decode a stream and then output. well the decoding and output works good but after the operation when i do close_input the application freezes.

**Comment by qqJoker** [comment]
I also encountered this problem, I am using .net Framework 4.7 environment, the program freezes when using avformat_close_input, how did you solve this problem
