### ISSUE TITLE
Include Documentation in NuGet Package

### ISSUE THREAD

**Issue by mariodivece** [Ruslan-B/FFmpeg.AutoGen#60]
All that beautiful documentation is now gone when referencing the NuGet package. Could you please include the XML file as posted here?
https://stackoverflow.com/questions/5205738/how-do-you-include-xml-docs-for-a-class-library-in-a-nuget-package

Thanks!

**Comment by Ruslan-B** [comment]
Ops I forgot about this. Fixed.
Install-Package FFmpeg.AutoGen -Version 3.3.3.2

**Comment by mariodivece** [comment]
Thank!!!
