### ISSUE TITLE
AVHWDeviceType Incomplete

### ISSUE THREAD

**Issue by mariodivece** [Ruslan-B/FFmpeg.AutoGen#61]
From the source code I can see that FFMPEG defines the following:

```csharp
namespace FFmpeg.AutoGen
{
    public enum AVHWDeviceType
    {
        AV_HWDEVICE_TYPE_VDPAU = 0,
        AV_HWDEVICE_TYPE_CUDA = 1,
        AV_HWDEVICE_TYPE_VAAPI = 2,
        AV_HWDEVICE_TYPE_DXVA2 = 3,
        AV_HWDEVICE_TYPE_QSV = 4
    }
}
```
But in FFMPEG's source code I see many other defined
https://github.com/FFmpeg/FFmpeg/blob/ec1573f879b1974050c68fdcb69b654e500efdfa/libavutil/hwcontext.h#L27
```c
enum AVHWDeviceType {
    AV_HWDEVICE_TYPE_VDPAU,
    AV_HWDEVICE_TYPE_CUDA,
    AV_HWDEVICE_TYPE_VAAPI,
    AV_HWDEVICE_TYPE_DXVA2,
    AV_HWDEVICE_TYPE_QSV,
    AV_HWDEVICE_TYPE_VIDEOTOOLBOX,
    AV_HWDEVICE_TYPE_NONE,
    AV_HWDEVICE_TYPE_D3D11VA,
    AV_HWDEVICE_TYPE_DRM,
};
```
Is there any reason why?
I also see the constant ```AV_PIX_FMT_FLAG_HWACCEL``` defined in FFMPEG but not in AutoGen. This is not a big deal as this is simply:
```public static readonly int AV_PIX_FMT_FLAG_HWACCEL = 1 << 3;```

**Comment by mariodivece** [comment]
Also AVPixelFormat seems incomplete. For example, D3D11 Pixel format is not available. Only the legacy D3D11VA_VLD
See: https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/pixfmt.h#L327

**Comment by Ruslan-B** [comment]
I think there is two issues:

- First, you are looking at the dev version of ffmpeg but the bindings generated over stable release 3.3 thus you have dependency in enums. Thus for reference it is better to use headers included with the bindings. With respect to AVPixelFormat indeed it has some conditional items inside but I see these members are generated so it looks complete to me.
- Second issue is really strange as I see structures being generated from pixfmt.h but not the macroses and I don't see any conditional flags. I'll take a look.

**Comment by Ruslan-B** [comment]
I added missing constants. With respect to incomplete enums I would advice to do not use none stable version of ffmpeg as from my experience it is asking for problems.
