### ISSUE TITLE
How to handle the decode/encode function return AVERROR_EOF

### ISSUE THREAD

**Issue by dxball** [Ruslan-B/FFmpeg.AutoGen#63]
The ffmpeg [document](https://www.ffmpeg.org/doxygen/3.1/group__lavc__encdec.html) says 

> Call avcodec_receive_frame() (decoding) or avcodec_receive_packet() (encoding) in a loop until AVERROR_EOF is returned. The functions will not return AVERROR(EAGAIN), unless you forgot to enter draining mode.

but I can't find the macro "AVERROR_EOF", how can I deal with the return value?

**Comment by Ruslan-B** [comment]
It is known to me. However, these kind of macroses are extremely hard to generate as they build as polymorfic inline functions. I have few ideas how to do so but it going to take some time to validate them. I’ll keep this issue open but I would recommend to search for constant value for now as a temporary solution.

**Comment by ispysoftware** [comment]
Brilliant, Thank you.
