### ISSUE TITLE
avformat_open_input change between ffmepg version?

### ISSUE THREAD

**Issue by OhSoGood** [Ruslan-B/FFmpeg.AutoGen#67]
Hi,

With the same SDP files (see example below), I used to open video stream with avformat_open_input without problem with the old libraries I was using: ffmpeg 2.2.3 (!) with avformat-55.dll and FFmpeg.AutoGen of that time. Now, I've tried to upgrade ffmpeg and FFmpeg.AutoGen to the latest (3.3.3 and 3.3.3.4 respectively), and my call to avformat_open_input returns an AVERROR of -1094995529. I was not even able to understand that error value even reading ffmepg doc.

Do anybody has an idea about what's wrong?
Thanks a lot for any idea or suggestion, they'll be welcome!
Regards
OSG

My code is:
```
AVFormatContext* pFormatContext = FFmpegInvoke.avformat_alloc_context();
// filename of type "file://pathtosdp/sdpfile
int result = FFmpegInvoke.avformat_open_input(&pFormatContext, filename, null, null);
// ffmpeg 2.2.3 was returning 0 (ok), version 3.3.3 now fails with value -1094995529
```
and the sdp file contains:
```
c=IN IP4 192.168.1.1
m=video 12000 RTP/AVP 96
a=rtpmap:96 H264/90000
```

**Comment by Ruslan-B** [comment]
I would suggest to duplicate this question on stackowerflow and put the link back.

**Comment by Ruslan-B** [comment]
Closing this as it is not bug or feature related to bindings. Please use stackoverflow.com in future.
