### ISSUE TITLE
Avcodec_open2 returns -22

### ISSUE THREAD

**Issue by debendramodi** [Ruslan-B/FFmpeg.AutoGen#68]
Hi Ruslan

Thanks for this .net wrapper.  This has been very helpful to me in my projects.

I am trying to encode g711 audio avpackets to aac.  The avcodec_open2 method returns -22.

This error indicates Invalid parameter.

                   AVCodec* codec = ffmpeg.avcodec_find_encoder(AVCodecID.AV_CODEC_ID_AAC);
                    if (codec == null) { _log.Info("Could not find codec: AV_CODEC_ID_AAC"); break; }
                    AVCodecContext* audioCodec = ffmpeg.avcodec_alloc_context3(codec);
                    audioCodec->bit_rate = 64000;
                    audioCodec->sample_fmt = AVSampleFormat.AV_SAMPLE_FMT_S16;
                    audioCodec->sample_rate = 8000;
                    audioCodec->channels = 1;
                    audioCodec->time_base.num = 1;
                    audioCodec->time_base.den = 8000;
                    audioCodec->strict_std_compliance = ffmpeg.FF_COMPLIANCE_EXPERIMENTAL;
                    ret = ffmpeg.avcodec_open2(audioCodec, codec, null);

Do you know what is causing this error ?

Thanks in advance for your help.

**Comment by Ruslan-B** [comment]
@debendramodi 
Your code snippet writes to log (you can check example project): ```Specified sample format s16 is invalid or not supported```. Hope it helps.
Please use stackoverflow.com in future. As it is not bug or feature related to bindings.
