### ISSUE TITLE
Some AVERROR_* values are wrong

### ISSUE THREAD

**Issue by qmfrederik** [Ruslan-B/FFmpeg.AutoGen#70]
The values of most of the `AVERROR_*` macros are wrong.

For example, `AVERROR_HTTP_SERVER_ERROR` has a value of `0xa7a7ca08` whereas it should be `0xa7a7caf8` (note the last byte is `08` instead of `f8`).

This appears to be an issue with the code which generates the macros. From the generated code:

```csharp
/// <summary>AVERROR_HTTP_SERVER_ERROR = FFERRTAG(0xF8,&apos;5&apos;,&apos;X&apos;,&apos;X&apos;)</summary>
public static int AVERROR_HTTP_SERVER_ERROR = FFERRTAG(0x8, '5', 'X', 'X');
```

The generated code should have been:

```csharp
AVERROR_HTTP_SERVER_ERROR = FFERRTAG(0xF8, '5', 'X', 'X');
```

instead of

```csharp
AVERROR_HTTP_SERVER_ERROR = FFERRTAG(0x8, '5', 'X', 'X');
```

I discovered this when calling `ffmpeg.av_strerror`; it returns -1 for `0xa7a7ca08` and 0 for `0xa7a7caf8`

**Comment by qmfrederik** [comment]
And as a special case:

```
/// <summary>AVERROR_EXPERIMENTAL = (-0x2bb2afa8)</summary>
public const int AVERROR_EXPERIMENTAL = -0x2bb2aa8;
```

**Comment by Ruslan-B** [comment]
@qmfrederik good catch, indeed it was bug in the parser. I added some extra unit tests and found and fix some other issues as well.
