### ISSUE TITLE
Native library names are different on Linux and macOS

### ISSUE THREAD

**Issue by qmfrederik** [Ruslan-B/FFmpeg.AutoGen#71]
Currently the P/Invoke statements look like this:

```csharp
[DllImport("avcodec-57", EntryPoint = "audio_resample", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
public static extern int audio_resample(ReSampleContext* @s, short* @output, short* @input, int @nb_samples);
```

However, `avcodec` is named `libavcodec.57.so` on Linux and `libavcodec.57.dylib` on macOS. The `lib` prefix is not an issue - .NET will add it automatically, but the problem is that the version suffix uses a dot instead of a dash (e.g. `.57` instead of `-57`).

One way to add support for macOS and Linux could look like this:

1 Store the names of the libraries in a const in a separate file
2 Have two versions of this file, one for Windows and one for Unix; for example:
3 Build two versions of FFmpeg.AutoGen, one for Windows and one for Unix.

I know how to do step 1-2 and I know .NET Core does 3, will look into how they do that.

Would you be open to a PR which implements something like this?

**Comment by qmfrederik** [comment]
Correction, there's a difference between Linux and macOS: on Linux, the version number comes after the `.so` extension whereas on macOS it comes before the `.dylib` extension:

- `avcodec-57.dll`
- `libavcodec.57.dylib`
- `libavcodec.so.57`

**Comment by Ruslan-B** [comment]
Yes, I'm confirming this.  
Besides, it was a way to workaround this for mono but it does not work on .NET Core. 
So, it looks like we have two options here manually load libraries (the way you propose previously) or to have a build per platform.
Effort wise I think it is not that much difference. 
So. @qmfrederik which way wold be better way to go?

**Comment by qmfrederik** [comment]
Perhaps manually loading the libraries is the better way to go. Two advantages I can see:
- You don't need to build a separate assembly per platform. I don't think `dotnet build` and `dotnet pack` have native support for this.
- On Linux, if you use ffmpeg from the package manager, you may get all different kind versions of ffmpeg depending on which distro you are running on (and naming conventions may vary slightly). So this gives libraries that use FFmpeg the ability to override the filenames of the ffmpeg `.so` files on Linux.

**Comment by Ruslan-B** [comment]
Well multiple configurations will do the trick I think, but it is quite cumbersome. I'll reiterate previous enhancement then. I'll keep you posted.

**Comment by Ruslan-B** [comment]
@qmfrederik thank for the all hard work.
I implemented lazy load for libraries and fictions and updated nuget packages as well.  With respect to ```av_sdp_create``` I create another issue here #75.  
I think can close the issue then.

**Comment by Ruslan-B** [comment]
However, in example project I'm using FFmpeg.Native package in case you comment out this line  ```FFmpegBinariesHelper.RegisterFFmpegBinaries();``` it does not work but I don't think it is connected with this change.

**Comment by ispysoftware** [comment]
I'm unable to get this working on OSX with net core. All I get is "could not find the entry point for avdevice_register_all". I've followed the instructions in the readme to the letter.

**Comment by ispysoftware** [comment]
Is this supposed to work on osx with net core 2? I'm just getting entrypoint not found exceptions (with the new Native loader code)

**Comment by qmfrederik** [comment]
@ispysoftware Yes, it works with OS X on .NET Core. I use the FFmpeg build from the `FFmpeg.Native.H264`  NuGet package and use this code to glue the native libraries with the AutoGen library:

First, before you use the FFmpeg API, update the delegate:

```
ffmpeg.GetOrLoadLibrary = GetOrLoadLibrary;
```

And this is the implementation for GetOrLoadLibrary

```csharp

/// <summary>
/// Loads a native library into memory, and returns a handle to that library.
/// </summary>
/// <param name="libraryName">
/// The name of the library to load.
/// </param>
/// <param name="version">
/// The version of the library to load. This value is ignored.
/// </param>
/// <returns>
/// A handle to the native library, or a null pointer on error.
/// </returns>
private static IntPtr GetOrLoadLibrary(string libraryName, int version)
{
    LoadLibraries();

    if (!libraryHandles.ContainsKey(libraryName))
    {
        return IntPtr.Zero;
    }

    return libraryHandles[libraryName];
}

/// <summary>
/// Loads the native FFmpeg libraries and populates the <see cref="libraryHandles"/> dictionary.
/// </summary>
private static void LoadLibraries()
{
    if (librariesLoaded)
    {
        return;
    }

    var path = FFmpegBinaries.FindFFmpegLibrary("avutil");

    if (path == null)
    {
        librariesLoaded = true;
        return;
    }

    // Normalize names
    path = Path.GetFullPath(path);

    var directory = Path.GetDirectoryName(path);

    // Make sure we load libwinpthread-1.dll, too
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    {
        var pthread = Path.Combine(directory, "libwinpthread-1.dll");
        var pthreadHandle = LibraryLoader.LoadNativeLibrary(pthread);
        libraryHandles.Add("winpthread", pthreadHandle);
    }

    // And libkvazaar
    string kvazaarName = null;

    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    {
        kvazaarName = "libkvazaar-3.dll";
    }
    else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
    {
        kvazaarName = "libkvazaar.3.dylib";
    }
    else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
    {
        kvazaarName = "libkvazaar.so.3";
    }

    var kvazaar = Path.Combine(directory, kvazaarName);
    var kvazaarHandle = LibraryLoader.LoadNativeLibrary(kvazaar);
    libraryHandles.Add("libkvazaar", kvazaarHandle);

    var librariesToLoad = new string[] { "avutil", "avcodec", "avformat", "swscale" };
    foreach (var libraryToLoad in librariesToLoad)
    {
        var libraryPath = FFmpegBinaries.FindFFmpegLibrary(libraryToLoad);
        libraryPath = Path.GetFullPath(libraryPath);

        var libraryHandle = LibraryLoader.LoadNativeLibrary(libraryPath);
        libraryHandles.Add(libraryToLoad, libraryHandle);
    }

    librariesLoaded = true;
}
```

It should not be very difficult to bring the FFmpeg.Native package up to date with the work that went into FFmpeg.Native.H264, it's just that I use the H264 project and didn't get round to migrating that work, yet.

**Comment by ispysoftware** [comment]
Brilliant, thanks for that :)

**Comment by tuxuser** [comment]
Could somebody please reflect the changes for library loading in the __FFmpeg.AutoGen.Example__

Very appreciated, thanks!

My System: OSX 10.13.2
VS for Mac: 7.3.3
Compile Target: Debug / x64
FFmpeg / Libav installed via brew

Running the Example currently produces this:
```
__ERROR:__ EntryPointNotFoundException: Could not find the entrypoint for av_register_all

FFmpeg.AutoGen.Native.FunctionLoader.GetFunctionDelegate<FFmpeg.AutoGen.ffmpeg.av_register_all_delegate>(System.IntPtr nativeLibraryHandle, string functionName, bool throwOnError) Line 32 in /Users/nona/Desktop/FFmpeg.AutoGen/FFmpeg.AutoGen/Native/FunctionLoader.cs:32
FFmpeg.AutoGen.ffmpeg.GetFunctionDelegate<FFmpeg.AutoGen.ffmpeg.av_register_all_delegate>(System.IntPtr libraryHandle, string functionName) Line 50 in /Users/nona/Desktop/FFmpeg.AutoGen/FFmpeg.AutoGen/FFmpeg.cs:50
FFmpeg.AutoGen.ffmpeg..cctor.AnonymousMethod__8_605() Line 6693 in /Users/nona/Desktop/FFmpeg.AutoGen/FFmpeg.AutoGen/FFmpeg.functions.g.cs:6693
FFmpeg.AutoGen.ffmpeg.av_register_all() Line 6706 in /Users/nona/Desktop/FFmpeg.AutoGen/FFmpeg.AutoGen/FFmpeg.functions.g.cs:6706
FFmpeg.AutoGen.Example.Program.Main(string[] args) Line 17 in /Users/nona/Desktop/FFmpeg.AutoGen/FFmpeg.AutoGen.Example/Program.cs:17
[External Code] in 
```

**Comment by Ruslan-B** [comment]
@tuxuser you can try to specify static ```ffmpeg.RootPath``` with absolute path to ffmpeg binaries?
Besides, it is quite confusing that it says line 32 which is windows library loader.

**Comment by tuxuser** [comment]
```
diff --git a/FFmpeg.AutoGen.Example/Program.cs b/FFmpeg.AutoGen.Example/Program.cs
index b95f2e0..9b1f21e 100644
--- a/FFmpeg.AutoGen.Example/Program.cs
+++ b/FFmpeg.AutoGen.Example/Program.cs
@@ -12,6 +12,8 @@ private static unsafe void Main(string[] args)
             Console.WriteLine(@"Current directory: " + Environment.CurrentDirectory);
             Console.WriteLine(@"Runnung in {0}-bit mode.", Environment.Is64BitProcess ? @"64" : @"32");

+            ffmpeg.RootPath = "/usr/local/lib";
+
             FFmpegBinariesHelper.RegisterFFmpegBinaries();

             ffmpeg.av_register_all();
```
Still produces the same error..

**Line 32** of FunctionLoader.cs seems like the base library-loading wrapper, not windows specific ?

**Comment by Ruslan-B** [comment]
My bad it is indeed platform agnostic function. I would suggest to debug entire sequence starting from library loading (```LibraryLoader.LoadNativeLibraryUsingPlatformNamingConvention```) as looks like it fails to load library in first place.
And the reason why might quite different e.g.: invalid path to binaries, different naming conventions for libraries, Mono vs .NET Core, 32 vs 64, etc.
As especially in case of Mono you might need to path ```FFmpeg.AutoGen.dll.config``` as well.

**Comment by Ruslan-B** [comment]
I'm closing this issue as I think we fix the main problem. 
@tuxuser if you need any help further it is okay to use this thread.

**Comment by Ruslan-B** [comment]
I think it might be the case that we are not adding lib prefix any more.

**Comment by Ruslan-B** [comment]
@tuxuser could you please test this 
```diff
@@ -39,7 +39,7 @@ public static IntPtr LoadNativeLibraryUsingPlatformNamingConvention(string path,
             }
             if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
             {
-                var fullName = Path.Combine(path, $"{libraryName}.{version}.dylib");
+                var fullName = Path.Combine(path, $"lib{libraryName}.{version}.dylib");
                 return LoadNativeLibrary(fullName);
             }
             throw new PlatformNotSupportedException();
```

**Comment by tuxuser** [comment]
@Ruslan-B just want make sure we are on the same page:
The Ffmpeg.Autogen.Sample never calls "GetOrLoadLibrary" actively, so that underlying function you told me to replace, is never called either.

The example still uses "RegisterFFmpegLibraries" aka. The old way.

From my understanding, there has to be at least a place which holds name and version for the libraries that need to be loaded, like @qmfrederik 's code snippet.

I got it working with his example btw, by adding a hackish "FindFFmpegBinary" method..

**Comment by Ruslan-B** [comment]
Good, I'll integrate the fix then.

**Comment by tuxuser** [comment]
How about a little addition, to be more descriptive? Something like this:
```diff
diff --git a/FFmpeg.AutoGen/FFmpeg.cs b/FFmpeg.AutoGen/FFmpeg.cs
index f58c41d..050785b 100644
--- a/FFmpeg.AutoGen/FFmpeg.cs
+++ b/FFmpeg.AutoGen/FFmpeg.cs
@@ -40,6 +40,9 @@ static ffmpeg()
                     loadedLibraries.Add(key, ptr);
                 }

+                if (ptr == IntPtr.Zero)
+                    throw new Exception($"Failed to load library {name} {version}, path: {RootPath}");
+
                 return ptr;
             };
         }
```

**Comment by Ruslan-B** [comment]
@tuxuser I added DllNotFoundException and updated nuget package as well.

**Comment by qmfrederik** [comment]
Hi everyone on this thread,

The long-term solution for this was dotnet/corefx#17135, which enables dynamic loading of native libraries on .NET Core, but I learned today that this won't make it for .NET Core 2.1.

If you're using .NET Core and System.Drawing, would you mind voting for that issue (clicking the 'thumbs up' emoji at the issue description would o it)?

Thanks!
