### ISSUE TITLE
Generate new version

### ISSUE THREAD

**Issue by Booster2ooo** [Ruslan-B/FFmpeg.AutoGen#8]
Hello Ruslan,

I've been using your library for a little while but today, I need to use a newer version of libav. 
I downloaded the packages at Zeranoe and replaced the bin & include folders.
When I try to generate the new .cs file using the python script, this error got raised (which was not raised with the older version) :

Status: Preprocessing d:\temp\tmpv8qtyr.h
Status: gcc -v -E -U __GNUC__ -dD -I./FFmpeg/include "-Dinline=" "-D__inline__=" "-D__extension__=" "-D__const=const" "-D__asm__(x)=" "-D__asm(x)=" "-DCTYPESGEN=1" "d:\temp\tmpv8qtyr.h"
Error: gcc -v -E: Using built-in specs.
Error: gcc -v -E: COLLECT_GCC=gcc
Error: gcc -v -E: Target: mingw32
Error: gcc -v -E: Configured with: ../gcc-4.8.1/configure --prefix=/mingw --host=mingw32 --build=mingw32 --without-pic --enable-shared --enable-static --with-gnu-ld --enable-lto --enable-libssp --disable-multilib --enable-languages=c,c++,fortran,objc,obj-c++,ada --disable-sjlj-exceptions --with-dwarf2 --disable-win32-registry --enable-libstdcxx-debug --enable-version-specific-runtime-libs --with-gmp=/usr/src/pkg/gmp-5.1.2-1-mingw32-src/bld --with-mpc=/usr/src/pkg/mpc-1.0.1-1-mingw32-src/bld --with-mpfr= --with-system-zlib --with-gnu-as --enable-decimal-float=yes --enable-libgomp --enable-threads --with-libiconv-prefix=/mingw32 --with-libintl-prefix=/mingw --disable-bootstrap LDFLAGS=-s CFLAGS=-D_USE_32BIT_TIME_T
Error: gcc -v -E: Thread model: win32
Error: gcc -v -E: gcc version 4.8.1 (GCC) 
Error: gcc -v -E: COLLECT_GCC_OPTIONS='-v' '-E' '-U' '__GNUC__' '-dD' '-I' './FFmpeg/include' '-D' 'inline=' '-D' '__inline__=' '-D' '__extension__=' '-D' '__const=const' '-D' '__asm__(x)=' '-D' '__asm(x)=' '-D' 'CTYPESGEN=1' '-mtune=generic' '-march=pentiumpro'
Error: gcc -v -E:  c:/mingw/bin/../libexec/gcc/mingw32/4.8.1/cc1.exe -E -quiet -v -I ./FFmpeg/include -iprefix c:\mingw\bin\../lib/gcc/mingw32/4.8.1/ -U __GNUC__ -D inline= -D __inline__= -D __extension__= -D __const=const -D __asm__(x)= -D __asm(x)= -D CTYPESGEN=1 d:\temp\tmpv8qtyr.h -mtune=generic -march=pentiumpro -dD
Error: gcc -v -E: ignoring duplicate directory "c:/mingw/lib/gcc/../../lib/gcc/mingw32/4.8.1/include"
Error: gcc -v -E: ignoring duplicate directory "c:/mingw/lib/gcc/../../lib/gcc/mingw32/4.8.1/../../../../include"
Error: gcc -v -E: ignoring duplicate directory "/mingw/include"
Error: gcc -v -E: ignoring duplicate directory "c:/mingw/lib/gcc/../../lib/gcc/mingw32/4.8.1/include-fixed"
Error: gcc -v -E: ignoring duplicate directory "c:/mingw/lib/gcc/../../lib/gcc/mingw32/4.8.1/../../../../mingw32/include"
Error: gcc -v -E: ignoring duplicate directory "/mingw/include"
Error: gcc -v -E: #include "..." search starts here:
Error: gcc -v -E: #include <...> search starts here:
Error: gcc -v -E:  ./FFmpeg/include
Error: gcc -v -E:  c:\mingw\bin\../lib/gcc/mingw32/4.8.1/include
Error: gcc -v -E:  c:\mingw\bin\../lib/gcc/mingw32/4.8.1/../../../../include
Error: gcc -v -E:  c:\mingw\bin\../lib/gcc/mingw32/4.8.1/include-fixed
Error: gcc -v -E:  c:\mingw\bin\../lib/gcc/mingw32/4.8.1/../../../../mingw32/include
Error: gcc -v -E: End of search list.
Error: gcc -v -E: COMPILER_PATH=c:/mingw/bin/../libexec/gcc/mingw32/4.8.1/;c:/mingw/bin/../libexec/gcc/;c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/
Error: gcc -v -E: LIBRARY_PATH=c:/mingw/bin/../lib/gcc/mingw32/4.8.1/;c:/mingw/bin/../lib/gcc/;c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/lib/;c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../
Error: gcc -v -E: COLLECT_GCC_OPTIONS='-v' '-E' '-U' '__GNUC__' '-dD' '-I' './FFmpeg/include' '-D' 'inline=' '-D' '__inline__=' '-D' '__extension__=' '-D' '__const=const' '-D' '__asm__(x)=' '-D' '__asm(x)=' '-D' 'CTYPESGEN=1' '-mtune=generic' '-march=pentiumpro'
Status: Parsing d:\temp\tmpv8qtyr.h
Error: c:\\mingw\\include\\inttypes.h:275: Syntax error at 'nptr'
Error: c:\\mingw\\include\\inttypes.h:276: Syntax error at 'endptr'
Error: c:\\mingw\\include\\inttypes.h:277: Syntax error at 'nptr'
Error: c:\\mingw\\include\\inttypes.h:278: Syntax error at 'endptr'
Error: c:\\mingw\\include\\inttypes.h:280: Syntax error at 'nptr'
Error: c:\\mingw\\include\\inttypes.h:281: Syntax error at 'endptr'
Error: c:\\mingw\\include\\inttypes.h:282: Syntax error at 'nptr'
Error: c:\\mingw\\include\\inttypes.h:283: Syntax error at 'endptr'
Error: c:\\mingw\\lib\\gcc\\mingw32\\4.8.1\\include\\stdarg.h:40: Syntax error at '__gnuc_va_list'
Error: c:\\mingw\\include\\sys\\types.h:27: Syntax error at '__time32_t'
Error: c:\\mingw\\include\\stdlib.h:313: Syntax error at '__nptr'
Error: c:\\mingw\\include\\stdlib.h:313: Syntax error at '__endptr'
Error: c:\\mingw\\include\\stdlib.h:427: Syntax error at '_atoi64'
Error: c:\\mingw\\include\\stdlib.h:428: Syntax error at 'char'
Error: c:\\mingw\\include\\stdlib.h:430: Syntax error at '_wtoi64'
Error: c:\\mingw\\include\\stdlib.h:431: Syntax error at 'wchar_t'
Error: c:\\mingw\\lib\\gcc\\mingw32\\4.8.1\\include\\stdarg.h:98: Syntax error at 'va_list'
Error: ./FFmpeg/include/libavutil/log.h:246: Syntax error at 'va_list'
Error: ./FFmpeg/include/libavutil/log.h:276: Syntax error at 'va_list'
Error: ./FFmpeg/include/libavutil/log.h:292: Syntax error at 'va_list'
Error: ./FFmpeg/include/libavutil/log.h:311: Syntax error at 'va_list'
Error: ./FFmpeg/include/libavutil/log.h:312: Syntax error at 'int'
Error: ./FFmpeg/include/libavutil/log.h:312: Syntax error at ')'
Error: c:\\mingw\\include\\time.h:102: Syntax error at 'time'
Error: c:\\mingw\\include\\time.h:104: Syntax error at 'mktime'
Error: c:\\mingw\\include\\time.h:119: Syntax error at '*'
Error: c:\\mingw\\include\\time.h:120: Syntax error at '*'
Error: c:\\mingw\\include\\time.h:121: Syntax error at '*'
Error: c:\\mingw\\include\\time.h:252: Syntax error at '*'
Status: Processing description list.
Traceback (most recent call last):
  File "C:\Users\Booster\Desktop\Bar\FFmpeg.AutoGen-master\FFmpeg.AutoGen-master\generate.py", line 512, in <module>
    ctypesgencore.processor.process(descriptions, options)
  File "C:\Users\Booster\Desktop\Bar\FFmpeg.AutoGen-master\FFmpeg.AutoGen-master\ctypesgencore\processor\pipeline.py", line 53, in process
    find_source_libraries(data,options)
  File "C:\Users\Booster\Desktop\Bar\FFmpeg.AutoGen-master\FFmpeg.AutoGen-master\ctypesgencore\processor\operations.py", line 191, in find_source_libraries
    library=ctypesgencore.libraryloader.load_library(library_name)
  File "C:\Users\Booster\Desktop\Bar\FFmpeg.AutoGen-master\FFmpeg.AutoGen-master\ctypesgencore\libraryloader.py", line 239, in load_library
    result = LibraryLoader.load_library(self, libname)
  File "C:\Users\Booster\Desktop\Bar\FFmpeg.AutoGen-master\FFmpeg.AutoGen-master\ctypesgencore\libraryloader.py", line 56, in load_library
    return self.load(path)
  File "C:\Users\Booster\Desktop\Bar\FFmpeg.AutoGen-master\FFmpeg.AutoGen-master\ctypesgencore\libraryloader.py", line 260, in load
    return _WindowsLibrary(path)
  File "C:\Users\Booster\Desktop\Bar\FFmpeg.AutoGen-master\FFmpeg.AutoGen-master\ctypesgencore\libraryloader.py", line 224, in __init__
    self.cdll = ctypes.cdll.LoadLibrary(path)
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 n’est pas une application Win32 valide // [Error 193] %1 is not a valid Win32 application

If you could help me with that, I would be pleased :)

**Comment by Ruslan-B** [comment]
Hi there,

I see your pain :). Generation indeed is a messy process and very sensitive to environment. I can update it to newer version at no time if you don't mind. Besides I'm going switch python generator to gccxml+F# which is going to less sensitive to environment setup.    

Cheers,
Ruslan

**Comment by Ruslan-B** [comment]
I've pushed update to 2.5.2 to master branch.

**Comment by Booster2ooo** [comment]
Thank you very much :)
