### ISSUE TITLE
Add missing Hardware Acceleration Methods, Structs, and Enums

### ISSUE THREAD

**Issue by mariodivece** [Ruslan-B/FFmpeg.AutoGen#82]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
NuGet package 3.4.0.2 not exposing APIs like  ``` avcodec_get_hw_config``` or structs like `AVCodecHWConfig`, and `AV_CODEC_HW_CONFIG_METHOD_*` enum. I am trying to implement hardware decoding. Please see: https://github.com/unosquare/ffmediaelement/issues/69

* **What is the expected behavior?**
Hardware APIs and structs should be available

* **What is the motivation / use case for changing the behavior?**
Getting access to HW accelerated decoding. The goal is to be able to implement fuctionality as described in this example code: http://ffmpeg.org/doxygen/trunk/hw_decode_8c-example.html

* **Please tell us about your environment:**
https://github.com/unosquare/ffmediaelement/

- version: 3.4

**Comment by Ruslan-B** [comment]
@mariodivece these functions and structures are present only in master branch of ffmpeg (ongoing development) and not present in stable release (3.4.1 atm). As usual I would suggest to wait for the next official release.

**Comment by mariodivece** [comment]
Well that was a little dumb of me to not check the version. I guess we'll have to wait a little more for the HW acceleration API to be available :(

**Comment by Ruslan-B** [comment]
@mariodivece I've updated the nuget with 4.0 release. Could you please check if it going to be sufficient - if yes please close the issue.

**Comment by mariodivece** [comment]
I am precisely working on the 4.0 branch of FFME and looking into the new HW accel support. Thanks for the fast API updates @Ruslan-B !

**Comment by Ruslan-B** [comment]
@mariodivece thank for the update. As this issue to broad I can assume it is safe to close it. Fell free to reopen.
