### ISSUE TITLE
Invalid mapping of linux libraries

### ISSUE THREAD

**Issue by vlaldis** [Ruslan-B/FFmpeg.AutoGen#86]
There is missing dot in the logic for loading .so libraries on linux. This results to "library not found" on Ubuntu 16.4

LibraryLoader.cs -> LoadNativeLibraryUsingPlatformNamingConvention() at line 37
  
```
var fullName = Path.Combine(path, $"lib{libraryName}.so{version}");
```

should contain dot before {version}

```
var fullName = Path.Combine(path, $"lib{libraryName}.so.{version}");
```

**Comment by Ruslan-B** [comment]
Nice catch! I updated package.
