### ISSUE TITLE
Wrong signature for: av_get_channel_layout_string

### ISSUE THREAD

**Issue by ViToni** [Ruslan-B/FFmpeg.AutoGen#9]
`av_get_channel_layout_string` is supposed to write the found channel layout into `buf`, which doesn't work for me with the given signature:

```c#
// Action<String, int, int, ulong>
[DllImport(AVUTIL_LIBRARY, EntryPoint="av_get_channel_layout_string", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
public static extern void av_get_channel_layout_string(String buf, int buf_size, int nb_channels, ulong channel_layout);
```

After changing the code to:
```c#
// Action<String, int, int, ulong>
[DllImport(AVUTIL_LIBRARY, EntryPoint = "av_get_channel_layout_string", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
public static extern void av_get_channel_layout_string(sbyte* buf, int buf_size, int nb_channels, ulong channel_layout);
```
the channel layout can be retrieved easily via:
```c#
public static String av_get_channel_layout_string(int nb_channels, ulong channel_layout)
{
    int len = 20;
    sbyte[] buffer = new sbyte[len];

    fixed (sbyte* buf = buffer)  {
        av_get_channel_layout_string(buf, len, nb_channels, channel_layout);

        return new String(buf);
    }
}
```

**Comment by Ruslan-B** [comment]
Thank you for reporting. I'll take a look, most-likely it is a generic bug in C# generator.

**Comment by ViToni** [comment]
Thanks for checking.

It's great you have created the wrapper! I tried other wrapper libraries which didn't work at all or only in parts.
Your approach with an generated wrapper seems promising in regards to the ongoing ffmpeg API changes.

**Comment by Ruslan-B** [comment]
Thank you :), well on the other hand this wrapper is not for everybody.
I've checked generator and looks like it works fine till you meet this function and indeed System.String cannot be correctly marshaled in this case.
Looks like I need to introduce exclusion for this specific function.
Otherwise you need to explicitly convert strings everywhere like this:
```csharp
string url = @"http://....";
IntPtr pUrl = Marshal.StringToHGlobalAnsi(url);
if (FFmpegInvoke.avformat_open_input(&pFormatContext, (byte *)pUrl, null, null) != 0)     
```

**Comment by Ruslan-B** [comment]
The argument type String this set functions forced to byte*:
	'av_strerror',
        'av_strndup',
        'av_log_format_line',
        'av_get_codec_tag_string',
        'av_get_sample_fmt_string',
        'av_get_channel_layout_string',
        'avcodec_string',
        'av_get_string',
        'avio_get_str',
        'avio_get_str16le',
        'avio_get_str16be',
        'av_url_split',
        'av_get_frame_filename',
        'av_sdp_create',
        'avfilter_process_command'

**Comment by ViToni** [comment]
You are fast ;)
I agree using System.String is convenient most of the time and should be the default for input variables.
Your change seems to catch all instances where `char*` has ben used for output (and therefore needs to be mapped to `byte*`).

**Comment by Ruslan-B** [comment]
Will see :), they constantly changing things.

**Comment by ViToni** [comment]
Tested your change. Works.

Thanks a lot for your good work!

One suggestion still: using `sbyte* buf` instead of `byte* buf` would save the casting in
`return new String((sbyte*)buf);`

**Comment by Ruslan-B** [comment]
Indeed it is more convenient. I wonder why three no byte* constructor... :)
I've changed generation rules with respect to char (string) based types thus it is affects not only methods but entire wrapper.

**Comment by ViToni** [comment]
Tested & it works. Great!

**Comment by ViToni** [comment]
If dug deeper into the code an it seems as if `av_strndup` uses the len argument onyl to indicate which part of the string to copy.
Having `String av_strndup(String, int)` would be just fine.

(BTW: 
* Would you like me open a new issue for such input or do you consider it belonging to the original issue?
* Can the generator be configured to treat parameters differently on the same method?
  * Example: the last `sbyte*` of `av_url_split` is onyl input and could be `string`

)

**Comment by ViToni** [comment]
My guess on `sbyte` is because ASCII is only well defined for the first 128 characters...
The "top" 128 characters were used for vendor specific code pages.

**Comment by Ruslan-B** [comment]
Looks like you are only one who is using all these functions :). I'll take a look what can be done with respect to different parameters. However, it is already clear that there are two ways:
first to supply additional metadata, for api user convenience;
and second just to use common denominator.

**Comment by ViToni** [comment]
Hopefully not, your wrapper is great!
And in contrast to other wrappers I found, it work's:)

I am digging deep because I try to write a C# version of ffprobe. It's working but is still rough.
I am using my version of ffprobe as a starting point to see if it's feasible to get transcoding to work from within C#.

One obstacle I have found so far (not a shortcoming of your project) is that the log callback used inside `libavutil` is difficult or impossible to implement in C# because of the `vargs` used.

**Comment by Ruslan-B** [comment]
I reverted av_strndup to string. I'll take a look how hand it will be to create additional set of rules.

**Comment by Ruslan-B** [comment]
recheck on #experemental

**Comment by Ruslan-B** [comment]
merged to master
