### ISSUE TITLE
Improove interop perfomance

### ISSUE THREAD

**Issue by mcdis** [Ruslan-B/FFmpeg.AutoGen#90]
At this moment, when native function is invoking you do like this:
```
  ffmpeg.av_frame_unref_fptr = ffmpeg.GetFunctionDelegate<ffmpeg.av_frame_unref_delegate>(ffmpeg.GetOrLoadLibrary("avutil", 56), "av_frame_unref");
      ffmpeg.av_frame_unref_fptr(frame);
```
May be using Interlocked.Exchange + Interlocked.CompareAndExchange to cache delegate will be better solution instead constructing delegate on each call

**Comment by Ruslan-B** [comment]
I guess it happens only once as all functions are delegates and the body redefines the delegate.
Potentially function location might be executed few times in heavy multi thread environment but it should not impact performance in any significant way.
Or I'm missing something?

**Comment by mcdis** [comment]
I agree and closing the issue
