### ISSUE TITLE
CppSharpUnsafeGenerator does not work

### ISSUE THREAD

**Issue by springy76** [Ruslan-B/FFmpeg.AutoGen#91]
I just git checked out the latest sources from May 2018, everything compiled fine (despite a warning that CppSharpUnsafeGenerator is targetting AnyCPU while consuming X64 assemblies).

On first run it failed with not finding input files; I debugged and finally removed one `..\` from the `solutionDir` constant in `CliOptions.Normalize()`.

Now it fails on the first file `g.Parse("libavutil/avutil.h");`:

> Error parsing 'libavutil/avutil.h'
> ~\ffmpeg\include\libavutil/common.h(33,10) : fatal: 'errno.h' file not found

Did I miss something important? I remember doing the same April 2016 (over 2 years ago) with success but the result files were totally different and did not compile at all afterwards.

**Comment by springy76** [comment]
I was sure I did because the new SSD was twice as large as the one before, but you are right, this was missing. (but there is still one ".." too much in `solutionDir`).

I additionally had to insert `CultureInfo.CurrentCulture = CultureInfo.CreateSpecificCulture("en");` at the beginning of `Main()` because without that some constants did use invalid syntax because not in every culture the floating point separator is a dot.

**Comment by Ruslan-B** [comment]
With respect to solutionDir if you recall you got the warning in the begining :), so you have to pick x64 as a platform as by default it is set to AnyCPU. 
I'm pretty sure that any float or double parsing uses InvariantCulture internally. 
However, (and you right!) generation is not protected and going to use default culture for writing numbers.
I'll submit a proper fix.

**Comment by springy76** [comment]
Using a fresh machine and a fresh checkout (April 2019) I still have to eliminate this `..\` (and disable `Prefer32Bit`) for CppSharpUnsafeGenerator to work at all.

```diff
@@ -58,7 +58,7 @@ public static CliOptions ParseArgumentsStrict(string[] args)
        private void Normalize()
        {
            // Support for the original path setup
-            const string solutionDir = "../../../../";
+            const string solutionDir = "../../../";
 
 
```

**Comment by Ruslan-B** [comment]
you most probably using 'Any CPU' asa target for generator you have to pick x64 :) otherwise it will be impossible to extract exports from ddl's.

**Comment by springy76** [comment]
I'm just confused that I always have to change several things to get it compile at all, and when it finally runs the "generated" output always changes, but I meanwhile noticed there is already an issue for this (#106).

**Comment by Ruslan-B** [comment]
you right here, not perfect and requires some manual effort mostly in discarding changes. As for #106 I decided to wait for next release as it seems to unreasonable to invest time when there is no api change on the ffmpeg side.
