### ISSUE TITLE
Whats the matter with AVDictionary?

### ISSUE THREAD

**Issue by springy76** [Ruslan-B/FFmpeg.AutoGen#92]
It is just declared as

```
    public unsafe struct AVDictionary
    {
    }
```

back in April 2016 when the declaration used the `partial` keyword I just added this code in a separate file to get it working:

```
	public unsafe partial struct AVDictionary
	{
		public int count;
		public AVDictionaryEntry* elems;
	}
```

Too complicated? I created thousands of `Dictionary<string, string>` objects from this without a single memory access problem or garbled data.

Now without `partial` I would have to reapply a patch on each update.

**Comment by Ruslan-B** [comment]
Well, you created a hack which is working in your case. The public FFmpeg API does not expose AVDictionary structure details. Hence, it meant to be used as strongly typed pointer only.
To conclude I would rather avoid the way of use you choose to access AVDictionary, as FFmpeg developers might change something in their implementation without any notice. My advice in your situation is to create a wrapper class with implicit conversion from AVDictionary* and use it as a substitute.

**Comment by springy76** [comment]
I have to admit I'm unable to really understand C(++) code since I always used very high level languages like Delphi and C#.

Even after you now told me "public FFmpeg API does not expose AVDictionary" I'm unable to see why [this](https://www.ffmpeg.org/doxygen/4.0/dict_8c_source.html#l00030) is private. I'm not expecting you to teach me C ;) but to prevent further similar questions please give me a hint.

**Comment by Ruslan-B** [comment]
I can understand the confusion. The name of the file `dict.c` refers implementation (private details) not to the official API which is exposed in form of include files `*.h`. Hence, you are browsing implementation source code.  For some reason, authors decided to hide this detail from the API consumers. 
I hope it helps to clarify the rationale background. 
Any questions are welcome.

**Comment by Ruslan-B** [comment]
Any questions left? Otherwise, I'll close the issue.

**Comment by mariodivece** [comment]
For whatever is worth, try the following:
https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME.Common/Core/FFDictionary.cs
https://github.com/unosquare/ffmediaelement/blob/master/Unosquare.FFME.Common/Core/FFDictionaryEntry.cs
