### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by superware** [Ruslan-B/FFmpeg.AutoGen#93]
Would be great if libavutil/time.h (av_gettime, av_gettime_relative, av_gettime_relative_is_monotonic, av_usleep) were also included in the bindings.

Plus, av_q2d will be very helpful and eliminate custom additions, almost without change except for omitting "inline" and adding "public":

```
public static double av_q2d(AVRational a)
{
	return a.num / (double)a.den;
}
```

Can CppSharp handle that?

**Comment by Ruslan-B** [comment]
yes, I know, the are inline function and could handy, but function body is exposed as string in CppSharp even though AST is avaliable in native C++ . Hence, without extending CppSharp it is not a trivial task (extending CppSharp as well :) ). 
There is an easy alternative to add this functions as not generated code but then it is going to be maintenance burden.

**Comment by superware** [comment]
Is it possible to manually map CppSharp function body string to the corresponding C# method body, and in the generation/build process check that the CppSharp string hasn't changed?

So "static inline double av_q2d(AVRational a){ return a.num / (double) a.den; }" is manually mapped to "public static double av_q2d(AVRational a){ return a.num / (double) a.den; }", and there's a check verifying that av_q2d's function body string hasn't changed, if it did the generation process will fail and force maintenance.

Note av_q2d was [last changed](https://github.com/FFmpeg/FFmpeg/blame/release/4.0/libavutil/rational.h#L104) 15 years ago :-)

**Comment by Ruslan-B** [comment]
I really like the idea, I think it is feasible, I'll definitely try to explore it. Besides, I already have macro parser, maybe it will be easy to extend it to get at-least basic functions being autogenerated. On top of it in case of av_q2d all inputs and outputs are known if I just use the same function body it will be valid C#.

**Comment by superware** [comment]
Wow, that's great! And what about av_gettime_relative and friends? :)

**Comment by Ruslan-B** [comment]
It should cover most of the inline functions. I would be rather conservative here just to say all of them :).

**Comment by superware** [comment]
But av_gettime_relative isn't inline :) please see time.h

**Comment by Ruslan-B** [comment]
Oh I see now. It is different story - `time.h` is not included in the generator. This one should be easy to fix. Any others?

**Comment by Ruslan-B** [comment]
I updated nuget package to 4.0.0.4.

**Comment by superware** [comment]
That's awesome, now only av_q2d (rational.h) left, since av_q2d is so common, and the body is actually valid C#... :-)

**Comment by Ruslan-B** [comment]
Work in progress... 😝 There are a lot of inline functions and I ready encountered some of the in the past as well.

**Comment by superware** [comment]
Isn't FFmpeg 4.0.2 worth advancing?

**Comment by Ruslan-B** [comment]
Using semantic versioning means there’s no api changes (only bug fixes), thus bindings are binary compatible, however I’ll double check on this.

Cheers,
Ruslan

**Comment by superware** [comment]
Hello @Ruslan-B, will you be able to incorporate the following in the 4.1 update?

```
public static double av_q2d(AVRational a)
{
	return a.num / (double)a.den;
}
```

Much appreciated.

**Comment by Ruslan-B** [comment]
Will do this weekend.

**Comment by Ruslan-B** [comment]
@superware I've pushed the fist revision of the inline methods. I fixed them by hands so it would be great if you can review the implementation. 
For now I'll keep this issue open as I still would like to implement some kind of persistence as right now hand coded methods will be wiped during regeneration.

**Comment by superware** [comment]
@Ruslan-B is it possible the latest release doesn't have av_gettime_relative? :o

**Comment by Ruslan-B** [comment]
rats! I show off time.h :(

**Comment by Ruslan-B** [comment]
should work now, feel free to reopen.
