### ISSUE TITLE
Invoke ffmpeg.avformat_open_input() throw “No such file or directory” error

### ISSUE THREAD

**Issue by Heak-GSC** [Ruslan-B/FFmpeg.AutoGen#94]
AVFormatContext* _pCodecContext = ffmpeg.avformat_alloc_context();
                AVDictionary* _avDic = null;
                ffmpeg.av_dict_set(&_avDic, "list_devices", "true", 0);
                AVInputFormat* _inputFormat = ffmpeg.av_find_input_format("dshow");
                ffmpeg.avformat_open_input(&_pCodecContext, "video=dummy", _inputFormat, &_avDic).ThrowExceptionIfError();

**Comment by Ruslan-B** [comment]
@Heak-GSC it stackowerflow question type.
