### ISSUE TITLE
How can i Play RTSP Stream Audio With Video

### ISSUE THREAD

**Issue by choiseonho** [Ruslan-B/FFmpeg.AutoGen#98]
Thank you.....

i making rtsp stream player to use opencv..

example Project is wonderful.

But that is with not Sound T_T

Can you help me???

i Added thid Code and i think i found Audio Stream Number... But i don't know next step T_T
Help me....

        private readonly AVCodecContext* _aCodecContext;
        private readonly AVFormatContext* _aFormatContext;
        private readonly int _a_streamIndex;

        public VideoStreamDecoder(string url)
        {
            _vFormatContext = ffmpeg.avformat_alloc_context();

            var pFormatContext = _vFormatContext;
            ffmpeg.avformat_open_input(&pFormatContext, url, null, null).ThrowExceptionIfError();

            ffmpeg.avformat_find_stream_info(_vFormatContext, null).ThrowExceptionIfError();

            // find the first video stream
            AVStream* vStream = null;
            for (var i = 0; i < _vFormatContext->nb_streams; i++)
                if (_vFormatContext->streams[i]->codec->codec_type == AVMediaType.AVMEDIA_TYPE_VIDEO)
                {
                    vStream = _vFormatContext->streams[i];
                    break;
                }

            // find Audio stream
            AVStream* aStream = null;
            for (var i = 0; i < _vFormatContext->nb_streams; i++)
                if (_vFormatContext->streams[i]->codec->codec_type == AVMediaType.AVMEDIA_TYPE_AUDIO)
                {
                    aStream = _vFormatContext->streams[i];
                    break;
                }

            if (vStream == null) throw new InvalidOperationException("Could not found video stream.");

            _v_streamIndex = vStream->index;
            _vCodecContext = vStream->codec;

            _a_streamIndex = aStream->index;
            _aCodecContext = aStream->codec;

            var vcodecId = _vCodecContext->codec_id;
            var vCodec = ffmpeg.avcodec_find_decoder(vcodecId);

            var acodecId = _aCodecContext->codec_id;
            var aCodec = ffmpeg.avcodec_find_decoder(acodecId);

            if (vCodec == null) throw new InvalidOperationException("Unsupported codec.");

            ffmpeg.avcodec_open2(_vCodecContext, vCodec, null).ThrowExceptionIfError();
            ffmpeg.avcodec_open2(_aCodecContext, aCodec, null).ThrowExceptionIfError();

            vCodecName = ffmpeg.avcodec_get_name(vcodecId);
            aCodecName = ffmpeg.avcodec_get_name(acodecId);
            FrameSize = new Size(_vCodecContext->width, _vCodecContext->height);
            PixelFormat = _vCodecContext->pix_fmt;

            _pPacket = ffmpeg.av_packet_alloc();
            _pFrame = ffmpeg.av_frame_alloc();
        }

**Comment by Ruslan-B** [comment]
Hi @choiseonho, please post your question on stackoverflow.
