### ISSUE TITLE
"max delay reached" Error... rtsp Stream

### ISSUE THREAD

**Issue by choiseonho** [Ruslan-B/FFmpeg.AutoGen#99]
I try Get Packet from Axis IP Camera... ( h264 / 1280x720 / 20Mbps / rtsp )

But...  "max delay reached" Error T_T

i found this...

https://superuser.com/questions/1282794/ffmpeg-passthrough-of-mpeg-transport-stream-causes-errorsglitches-in-stream

because -re Command....

Can you Fix that for me?

![image](https://user-images.githubusercontent.com/17864839/46793311-5fb4ea00-cd80-11e8-89eb-bf10473161c2.png)

**Comment by Ruslan-B** [comment]
No I don't. Besides, if you keep ignoring issue template I'll ban you from this repo.

**Comment by BBUBBA** [comment]
Sorry !!!!!!T.T

**Comment by Ruslan-B** [comment]
I'll repeat one more time for clarity:
**The FFmpeg API is vast and complex and this project exposes it with minimum modifications - support is very limited.
Please consider to ask *how to* questions on [stackoverflow.com](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen). 
The community may be able to offer some assistance but you will largely be on your own.
As another option you can search for a solution in C(lang) as with some effort you can convert it to C#.**

**Comment by BBUBBA** [comment]
I solve this Trouble Now.

Thank you Ruslan-B !!!
Have a Nice Day ^^

1. Convert Function Move UI Thread (Async Processing)
2. Send Data -> UI thread (Event)

                    while (vsd.TryDecodeNextFrame(out var frame))
                    {

                        // Call Event UI Thread
                        // Convert Function => Move UI Thread
                        //var convertedFrame = vfc.Convert(frame);

                        //using (var bitmap = new Bitmap(convertedFrame.width, convertedFrame.height, convertedFrame.linesize[0], PixelFormat.Format24bppRgb, (IntPtr) convertedFrame.data[0]))
                        //    bitmap.Save($"frame.{frameNumber:D8}.jpg", ImageFormat.Jpeg);

                        Console.WriteLine($"frame: {frameNumber}");
                        frameNumber++;

                    }
